import test from "node:test";
import assert from "node:assert/strict";

import { buildSeedDataset } from "@/lib/seed";
import { getCalendarCompletionForecast } from "@/lib/analytics/metrics";
import { expandReservedCommitmentWindowsForWeek } from "@/lib/scheduler/free-slots";
import { generateStudyPlanHorizon, shouldPreserveStudyBlockOnRegeneration } from "@/lib/scheduler/generator";
import {
  getActiveSickDaySeverity,
  isReservedCommitmentRuleActiveOnDate,
  resolveDailyScheduleProfile,
} from "@/lib/scheduler/schedule-regime";
import { buildTaskCandidates } from "@/lib/scheduler/task-candidates";
import { validateGeneratedHorizon } from "@/lib/scheduler/validation";
import type { StudyBlock, Topic, WeeklyPlan } from "@/lib/types/planner";

function createStudyBlock(overrides: Partial<StudyBlock> = {}): StudyBlock {
  return {
    id: "block-1",
    weekStart: "2026-03-09",
    date: "2026-03-10",
    start: "2026-03-10T08:00:00.000Z",
    end: "2026-03-10T09:00:00.000Z",
    subjectId: "physics-hl",
    topicId: "topic-1",
    title: "Test block",
    sessionSummary: null,
    paperCode: null,
    unitTitle: null,
    blockType: "standard_focus",
    intensity: "moderate",
    generatedReason: "test",
    scoreBreakdown: {
      priorityWeight: 0,
      deadlineUrgency: 0,
      remainingWorkloadPressure: 0,
      lowMasteryBonus: 0,
      reviewDueBonus: 0,
      neglectedSubjectBonus: 0,
      olympiadSlotBonus: 0,
      badSlotFitPenalty: 0,
      fragmentationPenalty: 0,
      total: 0,
    },
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: [],
    slotEnergy: "steady",
    estimatedMinutes: 60,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
    ...overrides,
  };
}

function createWeeklyPlan(overrides: Partial<WeeklyPlan> = {}): WeeklyPlan {
  return {
    weekStart: "2026-03-09",
    requiredHoursBySubject: { "physics-hl": 4 },
    deadlinePaceHoursBySubject: { "physics-hl": 4 },
    assignedHoursBySubject: { "physics-hl": 2 },
    completedHoursBySubject: { "physics-hl": 0 },
    remainingHoursBySubject: { "physics-hl": 6 },
    coverageGapHoursBySubject: { "physics-hl": 2 },
    scheduledToGoalHoursBySubject: { "physics-hl": 4 },
    underplannedSubjectIds: ["physics-hl"],
    slackMinutes: 120,
    carryOverBlockIds: [],
    feasibilityScore: 60,
    riskFlag: "medium",
    feasibilityWarnings: [],
    forcedCoverageMinutes: 0,
    usedSundayMinutes: 0,
    overloadMinutes: 0,
    coverageComplete: false,
    weeksRemainingToDeadline: 10,
    horizonEndDate: "2026-07-31",
    generatedAt: "2026-03-13T00:00:00.000Z",
    ...overrides,
  };
}

test("paired paper reviews retain their dependency scheduling window", () => {
  const dataset = buildSeedDataset(new Date("2026-03-13T08:00:00"));
  const reviewTopic = dataset.topics.find(
    (topic) => topic.id === "physics-past-papers-week-8-paper-2-review",
  );

  assert.ok(reviewTopic, "expected seeded review topic");
  assert.equal(reviewTopic.maxDaysAfterDependency, 7);

  const existingPracticeBlock = createStudyBlock({
    id: "practice-1",
    weekStart: "2026-09-21",
    date: "2026-09-22",
    start: "2026-09-22T08:00:00.000Z",
    end: "2026-09-22T10:30:00.000Z",
    topicId: "physics-past-papers-week-8-paper-2",
    title: "Physics HL Week 8 - Paper 2",
    estimatedMinutes: 150,
  });

  const candidates = buildTaskCandidates({
    topics: [reviewTopic as Topic],
    existingPlannedBlocks: [existingPracticeBlock],
    referenceDate: new Date("2026-09-21T08:00:00"),
    subjectDeadlinesById: { "physics-hl": "2027-06-30" },
  });
  const reviewCandidate = candidates.find((candidate) => candidate.topicId === reviewTopic.id);

  assert.ok(reviewCandidate, "expected a schedulable review candidate");
  assert.equal(reviewCandidate?.paperCode, "PHY-W08-P2");
  assert.equal(reviewCandidate?.availableAt?.slice(0, 10), "2026-09-23");
  assert.equal(reviewCandidate?.latestAt?.slice(0, 10), "2026-09-29");
});

test("maths HL-book topics stay blocked until the SL book sequence is complete", () => {
  const dataset = buildSeedDataset(new Date("2026-03-14T08:00:00"));
  const hlBookTopic = dataset.topics.find(
    (topic) => topic.id === "maths-topic1-complex-numbers",
  );

  assert.ok(hlBookTopic, "expected a seeded HL-book maths topic");
  assert.equal(hlBookTopic.dependsOnTopicId, "maths-topic5-integration-core");

  const blockedCandidates = buildTaskCandidates({
    topics: [hlBookTopic as Topic],
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-14T08:00:00"),
    subjectDeadlinesById: { "maths-aa-hl": "2027-06-30" },
  });

  assert.equal(blockedCandidates.length, 0);

  const slBoundaryBlock = createStudyBlock({
    id: "integration-boundary",
    subjectId: "maths-aa-hl",
    topicId: "maths-topic5-integration-core",
    title: "Core integration",
    start: "2026-06-01T08:00:00.000Z",
    end: "2026-06-01T09:30:00.000Z",
    estimatedMinutes: 90,
  });

  const unlockedCandidates = buildTaskCandidates({
    topics: [hlBookTopic as Topic],
    existingPlannedBlocks: [slBoundaryBlock],
    referenceDate: new Date("2026-06-02T08:00:00"),
    subjectDeadlinesById: { "maths-aa-hl": "2027-06-30" },
  });

  assert.equal(unlockedCandidates.length, 1);
  assert.equal(unlockedCandidates[0]?.topicId, "maths-topic1-complex-numbers");
});

test("calendar completion forecast distinguishes impossible from simply underplanned", () => {
  const dataset = buildSeedDataset(new Date("2026-03-13T08:00:00"));
  const subject = dataset.subjects.find((candidate) => candidate.id === "physics-hl");
  assert.ok(subject, "expected physics subject");

  const underplannedForecast = getCalendarCompletionForecast({
    subject,
    topics: dataset.topics,
    goals: dataset.goals,
    studyBlocks: [],
    weeklyPlans: [createWeeklyPlan()],
    referenceDate: new Date("2026-03-13T08:00:00"),
  });

  assert.equal(underplannedForecast.isCalendarImpossible, false);
  assert.equal(underplannedForecast.needsMoreBlocks, true);

  const impossibleForecast = getCalendarCompletionForecast({
    subject,
    topics: dataset.topics,
    goals: dataset.goals,
    studyBlocks: [],
    weeklyPlans: [createWeeklyPlan({ slackMinutes: 0 })],
    referenceDate: new Date("2026-03-13T08:00:00"),
  });

  assert.equal(impossibleForecast.isCalendarImpossible, true);
});

test("regeneration preserves user-touched future blocks", () => {
  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        isAutoGenerated: false,
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        notes: "Keep this slot for tutoring notes",
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        rescheduleCount: 1,
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        status: "planned",
        notes: "",
        rescheduleCount: 0,
        isAutoGenerated: true,
      }),
    ),
    false,
  );
});

test("generated horizon passes core validation checks for a short seeded window", () => {
  const referenceDate = new Date("2026-03-13T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-09T00:00:00"),
    endWeek: new Date("2026-03-30T00:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    preferences: dataset.preferences,
  });

  const issues = validateGeneratedHorizon({
    studyBlocks: result.studyBlocks,
    topics: dataset.topics,
    weeklyPlans: result.weeklyPlans,
  });

  const errorIssues = issues.filter((issue) => issue.severity === "error");
  assert.deepEqual(
    errorIssues,
    [],
    `expected no blocking validation issues, got: ${errorIssues.map((issue) => issue.message).join(" | ")}`,
  );
});

test("overlapping sick-day ranges resolve to the highest active severity", () => {
  const severity = getActiveSickDaySeverity(new Date("2026-03-18T10:00:00"), [
    {
      id: "light-range",
      startDate: "2026-03-17",
      endDate: "2026-03-20",
      severity: "light",
    },
    {
      id: "severe-range",
      startDate: "2026-03-18",
      endDate: "2026-03-18",
      severity: "severe",
    },
  ]);

  assert.equal(severity, "severe");
});

test("sick-day severity lightens capacity and keeps homework while reducing piano", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
  };

  const lightProfile = resolveDailyScheduleProfile(
    new Date("2026-03-17T10:00:00"),
    preferences,
    [],
  );
  const reducedLightProfile = resolveDailyScheduleProfile(
    new Date("2026-03-17T10:00:00"),
    preferences,
    [
      {
        id: "light",
        startDate: "2026-03-17",
        endDate: "2026-03-17",
        severity: "light",
      },
    ],
  );

  assert.equal(reducedLightProfile.maxHeavySessionsPerDay, 1);
  assert.ok(reducedLightProfile.maxStudyHoursPerDay < lightProfile.maxStudyHoursPerDay);

  const lightCommitments = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [
      {
        id: "light",
        startDate: "2026-03-17",
        endDate: "2026-03-17",
        severity: "light",
      },
    ],
  ).filter((window) => window.start.startsWith("2026-03-17"));

  const pianoCommitment = lightCommitments.find((window) => window.label === "Piano");
  const homeworkCommitment = lightCommitments.find((window) => window.label === "Homework");

  assert.ok(pianoCommitment);
  assert.equal(
    Math.round(
      (new Date(pianoCommitment!.end).getTime() - new Date(pianoCommitment!.start).getTime()) /
        60000,
    ),
    30,
  );
  assert.ok(homeworkCommitment);
  assert.equal(
    Math.round(
      (new Date(homeworkCommitment!.end).getTime() - new Date(homeworkCommitment!.start).getTime()) /
        60000,
    ),
    90,
  );
});

test("moderate and severe sick days remove piano and restrict heavier study modes", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
  };

  const moderateProfile = resolveDailyScheduleProfile(
    new Date("2026-03-18T10:00:00"),
    preferences,
    [
      {
        id: "moderate",
        startDate: "2026-03-18",
        endDate: "2026-03-18",
        severity: "moderate",
      },
    ],
  );
  const severeProfile = resolveDailyScheduleProfile(
    new Date("2026-03-19T10:00:00"),
    preferences,
    [
      {
        id: "severe",
        startDate: "2026-03-19",
        endDate: "2026-03-19",
        severity: "severe",
      },
    ],
  );

  assert.equal(moderateProfile.maxHeavySessionsPerDay, 0);
  assert.deepEqual(moderateProfile.allowedBlockTypes, ["standard_focus", "drill", "review", "recovery"]);
  assert.equal(severeProfile.maxHeavySessionsPerDay, 0);
  assert.deepEqual(severeProfile.allowedBlockTypes, ["drill", "review", "recovery"]);

  const moderateCommitments = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [
      {
        id: "moderate",
        startDate: "2026-03-18",
        endDate: "2026-03-18",
        severity: "moderate",
      },
    ],
  ).filter((window) => window.start.startsWith("2026-03-18"));

  assert.equal(
    moderateCommitments.some((window) => window.label === "Piano"),
    false,
  );
  assert.equal(
    moderateCommitments.some((window) => window.label === "Homework"),
    true,
  );
});

test("piano commitment rules support single-day additions and removals", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const pianoRule = dataset.preferences.reservedCommitmentRules.find(
    (rule) => rule.id === "piano-practice",
  );

  assert.ok(pianoRule, "expected seeded piano rule");

  const monday = new Date("2026-03-16T10:00:00");
  const tuesday = new Date("2026-03-17T10:00:00");

  assert.equal(isReservedCommitmentRuleActiveOnDate(pianoRule!, monday, false), false);
  assert.equal(isReservedCommitmentRuleActiveOnDate(pianoRule!, tuesday, false), true);

  const withMondayAddition = {
    ...pianoRule!,
    additionalDates: ["2026-03-16"],
  };
  const withTuesdayRemoval = {
    ...pianoRule!,
    excludedDates: ["2026-03-17"],
  };

  assert.equal(isReservedCommitmentRuleActiveOnDate(withMondayAddition, monday, false), true);
  assert.equal(isReservedCommitmentRuleActiveOnDate(withTuesdayRemoval, tuesday, false), false);
});

test("homework commitment rules can be explicitly added outside normal school-term dates", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const homeworkRule = dataset.preferences.reservedCommitmentRules.find(
    (rule) => rule.id === "term-homework",
  );

  assert.ok(homeworkRule, "expected seeded homework rule");

  const holidayDate = new Date("2026-07-10T10:00:00");
  assert.equal(isReservedCommitmentRuleActiveOnDate(homeworkRule!, holidayDate, false), false);

  const withHolidayAddition = {
    ...homeworkRule!,
    additionalDates: ["2026-07-10"],
  };

  assert.equal(isReservedCommitmentRuleActiveOnDate(withHolidayAddition, holidayDate, false), true);
});

test("homework duration overrides change the reserved commitment length for one date", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
    reservedCommitmentRules: dataset.preferences.reservedCommitmentRules.map((rule) =>
      rule.id === "term-homework"
        ? {
            ...rule,
            durationOverrides: {
              ...(rule.durationOverrides ?? {}),
              "2026-03-17": 120,
            },
          }
        : rule,
    ),
  };

  const commitment = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [],
  ).find(
    (window) => window.label === "Homework" && window.start.startsWith("2026-03-17"),
  );

  assert.ok(commitment);
  assert.equal(
    Math.round(
      (new Date(commitment!.end).getTime() - new Date(commitment!.start).getTime()) / 60000,
    ),
    120,
  );
});
