import test from "node:test";
import assert from "node:assert/strict";
import { addDays } from "date-fns";

import { buildSeedDataset } from "@/lib/seed";
import { getCalendarCompletionForecast, getSubjectProgress } from "@/lib/analytics/metrics";
import { createDateAtTime, fromDateKey, startOfPlannerWeek, toDateKey } from "@/lib/dates/helpers";
import {
  calculateFreeSlots,
  expandLockedRecoveryWindowsForWeek,
  expandReservedCommitmentWindowsForWeek,
} from "@/lib/scheduler/free-slots";
import {
  generateStudyPlanForWeek,
  generateStudyPlanHorizon,
  getInlineBreakMinutes,
  shouldPreserveStudyBlockOnRegeneration,
} from "@/lib/scheduler/generator";
import {
  getActiveSickDaySeverity,
  isReservedCommitmentRuleActiveOnDate,
  resolveDailyScheduleProfile,
} from "@/lib/scheduler/schedule-regime";
import {
  collectInvalidFutureOlympiadBlockIds,
  getOlympiadNumberTheoryFrontierStatus,
} from "@/lib/scheduler/olympiad-stage-gates";
import {
  buildTaskCandidates,
  getAssignableTaskCandidatesForBlock,
} from "@/lib/scheduler/task-candidates";
import { validateGeneratedHorizon } from "@/lib/scheduler/validation";
import type { StudyBlock, Topic, WeeklyPlan } from "@/lib/types/planner";

function createStudyBlock(overrides: Partial<StudyBlock> = {}): StudyBlock {
  return {
    id: "block-1",
    weekStart: "2026-03-09",
    date: "2026-03-10",
    start: "2026-03-10T08:00:00.000Z",
    end: "2026-03-10T09:00:00.000Z",
    subjectId: "physics-hl",
    topicId: "topic-1",
    title: "Test block",
    sessionSummary: null,
    paperCode: null,
    unitTitle: null,
    blockType: "standard_focus",
    intensity: "moderate",
    generatedReason: "test",
    scoreBreakdown: {
      priorityWeight: 0,
      deadlineUrgency: 0,
      remainingWorkloadPressure: 0,
      lowMasteryBonus: 0,
      reviewDueBonus: 0,
      neglectedSubjectBonus: 0,
      olympiadSlotBonus: 0,
      focusDayBonus: 0,
      badSlotFitPenalty: 0,
      fragmentationPenalty: 0,
      total: 0,
    },
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: [],
    slotEnergy: "steady",
    estimatedMinutes: 60,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
    assignmentLocked: false,
    assignmentEditedAt: null,
    ...overrides,
  };
}

function createWeeklyPlan(overrides: Partial<WeeklyPlan> = {}): WeeklyPlan {
  return {
    weekStart: "2026-03-09",
    requiredHoursBySubject: { "physics-hl": 4 },
    deadlinePaceHoursBySubject: { "physics-hl": 4 },
    assignedHoursBySubject: { "physics-hl": 2 },
    completedHoursBySubject: { "physics-hl": 0 },
    remainingHoursBySubject: { "physics-hl": 6 },
    coverageGapHoursBySubject: { "physics-hl": 2 },
    scheduledToGoalHoursBySubject: { "physics-hl": 4 },
    underplannedSubjectIds: ["physics-hl"],
    slackMinutes: 120,
    carryOverBlockIds: [],
    feasibilityScore: 60,
    riskFlag: "medium",
    feasibilityWarnings: [],
    forcedCoverageMinutes: 0,
    usedSundayMinutes: 0,
    overloadMinutes: 0,
    coverageComplete: false,
    weeksRemainingToDeadline: 10,
    horizonEndDate: "2026-07-31",
    generatedAt: "2026-03-13T00:00:00.000Z",
    ...overrides,
  };
}

test("paired paper reviews retain their dependency scheduling window", () => {
  const dataset = buildSeedDataset(new Date("2026-03-13T08:00:00"));
  const reviewTopic = dataset.topics.find(
    (topic) => topic.id === "physics-past-papers-week-8-paper-2-review",
  );

  assert.ok(reviewTopic, "expected seeded review topic");
  assert.equal(reviewTopic.maxDaysAfterDependency, 7);

  const existingPracticeBlock = createStudyBlock({
    id: "practice-1",
    weekStart: "2026-09-21",
    date: "2026-09-22",
    start: "2026-09-22T08:00:00.000Z",
    end: "2026-09-22T10:30:00.000Z",
    topicId: "physics-past-papers-week-8-paper-2",
    title: "Physics HL Week 8 - Paper 2",
    estimatedMinutes: 150,
  });

  const candidates = buildTaskCandidates({
    topics: [reviewTopic as Topic],
    existingPlannedBlocks: [existingPracticeBlock],
    referenceDate: new Date("2026-09-21T08:00:00"),
    subjectDeadlinesById: { "physics-hl": "2027-06-30" },
  });
  const reviewCandidate = candidates.find((candidate) => candidate.topicId === reviewTopic.id);

  assert.ok(reviewCandidate, "expected a schedulable review candidate");
  assert.equal(reviewCandidate?.paperCode, "PHY-W08-P2");
  assert.equal(reviewCandidate?.availableAt?.slice(0, 10), "2026-09-23");
  assert.equal(reviewCandidate?.latestAt?.slice(0, 10), "2026-09-29");
});

test("dedicated past-paper review topics do not spawn extra review-of-review candidates", () => {
  const dataset = buildSeedDataset(new Date("2026-09-21T08:00:00"));
  const reviewTopic = dataset.topics.find(
    (topic) => topic.id === "physics-past-papers-week-8-paper-2-review",
  );

  assert.ok(reviewTopic, "expected seeded review topic");

  const existingReviewBlock = createStudyBlock({
    id: "review-1",
    weekStart: "2026-09-21",
    date: "2026-09-24",
    start: "2026-09-24T08:00:00.000Z",
    end: "2026-09-24T09:15:00.000Z",
    subjectId: "physics-hl",
    topicId: "physics-past-papers-week-8-paper-2-review",
    title: "Physics HL Week 8 - Paper 2 review",
    blockType: "review",
    estimatedMinutes: 75,
  });

  const candidates = buildTaskCandidates({
    topics: [reviewTopic as Topic],
    existingPlannedBlocks: [existingReviewBlock],
    referenceDate: new Date("2026-09-24T10:00:00"),
    subjectDeadlinesById: { "physics-hl": "2027-06-30" },
  });

  assert.equal(candidates.length, 0);
});

test("maths topics stay hard-gated in seeded order", () => {
  const dataset = buildSeedDataset(new Date("2026-03-14T08:00:00"));
  const hlBookTopic = dataset.topics.find(
    (topic) => topic.id === "maths-topic1-complex-numbers",
  );

  assert.ok(hlBookTopic, "expected a seeded HL-book maths topic");
  assert.equal(hlBookTopic.dependsOnTopicId, "maths-topic1-proof");

  const blockedCandidates = buildTaskCandidates({
    topics: [hlBookTopic as Topic],
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-14T08:00:00"),
    subjectDeadlinesById: { "maths-aa-hl": "2027-06-30" },
  });

  assert.equal(blockedCandidates.length, 0);

  const slBoundaryBlock = createStudyBlock({
    id: "proof-boundary",
    subjectId: "maths-aa-hl",
    topicId: "maths-topic1-proof",
    title: "Mathematical proof",
    start: "2026-06-01T08:00:00.000Z",
    end: "2026-06-01T09:30:00.000Z",
    estimatedMinutes: 300,
  });

  const unlockedCandidates = buildTaskCandidates({
    topics: [hlBookTopic as Topic],
    existingPlannedBlocks: [slBoundaryBlock],
    referenceDate: new Date("2026-06-02T08:00:00"),
    subjectDeadlinesById: { "maths-aa-hl": "2027-06-30" },
  });

  assert.equal(unlockedCandidates.length, 1);
  assert.equal(unlockedCandidates[0]?.topicId, "maths-topic1-complex-numbers");
});

test("physics topics are hard-gated in seeded syllabus order", () => {
  const dataset = buildSeedDataset(new Date("2026-03-19T08:00:00"));
  const a2 = dataset.topics.find((topic) => topic.id === "physics-a2-forces-momentum");
  const b1 = dataset.topics.find((topic) => topic.id === "physics-b1-thermal-transfers");
  const e4 = dataset.topics.find((topic) => topic.id === "physics-e4-fission");

  assert.ok(a2);
  assert.ok(b1);
  assert.ok(e4);
  assert.equal(a2?.dependsOnTopicId, "physics-a1-kinematics");
  assert.equal(b1?.dependsOnTopicId, "physics-a5-relativity");
  assert.equal(e4?.dependsOnTopicId, "physics-e3-radioactive-decay");
});

test("maths, chemistry, olympiad, and c++ also follow seeded prerequisite order", () => {
  const dataset = buildSeedDataset(new Date("2026-03-19T08:00:00"));

  assert.equal(
    dataset.topics.find((topic) => topic.id === "maths-topic1-sequences-series")?.dependsOnTopicId,
    "maths-topic1-exponents-logs",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "chem-structure-1-2-nuclear-atom")?.dependsOnTopicId,
    "chem-structure-1-1-particulate",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-number-theory-congruence")?.dependsOnTopicId,
    "olympiad-number-theory-divisibility",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-number-theory-divisibility")?.sequenceGroup,
    "olympiad-nt",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-number-theory-divisibility")?.sequenceStage,
    "foundation",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-number-theory-valuations")?.dependsOnTopicId,
    "olympiad-number-theory-congruence",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-number-theory-valuations")?.sequenceStage,
    "advanced",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-geometry-points-lines-polygons")?.dependsOnTopicId ?? null,
    null,
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-geometry-points-lines-polygons")?.sequenceGroup,
    "olympiad-geo",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-geometry-points-lines-polygons")?.sequenceStage,
    "foundation",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-geometry-coordinate-complex")?.dependsOnTopicId,
    "olympiad-geometry-advanced-theorems",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-geometry-coordinate-complex")?.sequenceStage,
    "advanced",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-algebra-sequences-series")?.dependsOnTopicId ?? null,
    null,
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-algebra-sequences-series")?.sequenceGroup,
    "olympiad-alg",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-algebra-sequences-series")?.sequenceStage,
    "foundation",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-combinatorics-counting-induction")?.dependsOnTopicId ?? null,
    null,
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-combinatorics-counting-induction")?.sequenceGroup,
    "olympiad-combi",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "olympiad-combinatorics-graph-theory")?.sequenceStage,
    "advanced",
  );
  assert.equal(
    dataset.topics.find((topic) => topic.id === "cpp-book-ch1-hello-world")?.dependsOnTopicId,
    "cpp-book-ch0-notes-to-reader",
  );
  assert.equal(
    dataset.topics.filter((topic) => topic.subjectId === "geography-transition").length,
    0,
  );
});

test("calendar completion forecast distinguishes impossible from simply underplanned", () => {
  const dataset = buildSeedDataset(new Date("2026-03-13T08:00:00"));
  const subject = dataset.subjects.find((candidate) => candidate.id === "physics-hl");
  assert.ok(subject, "expected physics subject");

  const underplannedForecast = getCalendarCompletionForecast({
    subject,
    topics: dataset.topics,
    goals: dataset.goals,
    studyBlocks: [],
    weeklyPlans: [createWeeklyPlan()],
    referenceDate: new Date("2026-03-13T08:00:00"),
  });

  assert.equal(underplannedForecast.isCalendarImpossible, false);
  assert.equal(underplannedForecast.needsMoreBlocks, true);

  const impossibleForecast = getCalendarCompletionForecast({
    subject,
    topics: dataset.topics,
    goals: dataset.goals,
    studyBlocks: [],
    weeklyPlans: [createWeeklyPlan({ slackMinutes: 0 })],
    referenceDate: new Date("2026-03-13T08:00:00"),
  });

  assert.equal(impossibleForecast.isCalendarImpossible, true);
});

test("subject progress distinguishes already planned work from truly unscheduled work", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiad = dataset.subjects.find((subject) => subject.id === "olympiad");
  const numberTheoryCongruence = dataset.topics.find(
    (topic) => topic.id === "olympiad-number-theory-congruence",
  );

  assert.ok(olympiad, "expected olympiad subject");
  assert.ok(numberTheoryCongruence, "expected seeded number theory topic");

  const plannedBlock = createStudyBlock({
    id: "olympiad-foundation-plan",
    weekStart: "2026-03-23",
    date: "2026-03-24",
    start: "2026-03-24T08:00:00.000Z",
    end: "2026-03-24T10:00:00.000Z",
    subjectId: "olympiad",
    topicId: "olympiad-number-theory-congruence",
    title: numberTheoryCongruence.title,
    estimatedMinutes: 120,
  });

  const progress = getSubjectProgress(
    olympiad,
    dataset.topics,
    [plannedBlock],
    new Date("2026-03-20T08:00:00"),
  );

  assert.equal(progress.plannedFutureHoursByTopic["olympiad-number-theory-congruence"], 2);
  assert.equal(progress.unscheduledHours < progress.remainingHours, true);
});

test("subject progress does not count synthetic follow-up review blocks as core topic coverage", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiad = dataset.subjects.find((subject) => subject.id === "olympiad");
  const topic = dataset.topics.find((candidate) => candidate.id === "olympiad-number-theory-congruence");

  assert.ok(olympiad, "expected olympiad subject");
  assert.ok(topic, "expected seeded topic");

  const reviewBlock = createStudyBlock({
    id: "synthetic-review",
    weekStart: "2026-03-23",
    date: "2026-03-24",
    start: "2026-03-24T08:00:00.000Z",
    end: "2026-03-24T08:45:00.000Z",
    subjectId: "olympiad",
    topicId: topic.id,
    title: `${topic.title} review`,
    blockType: "review",
    estimatedMinutes: 45,
  });

  const progress = getSubjectProgress(
    olympiad,
    dataset.topics,
    [reviewBlock],
    new Date("2026-03-20T08:00:00"),
  );

  assert.equal(progress.plannedFutureHoursByTopic[topic.id] ?? 0, 0);
  assert.equal(progress.unscheduledHours, progress.remainingHours);
});

test("horizon generation fully places remaining topic hours when future capacity exists", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const subject = dataset.subjects.find((candidate) => candidate.id === "physics-hl");

  assert.ok(subject, "expected physics subject");

  const customTopics: Topic[] = [
    {
      ...dataset.topics.find((topic) => topic.id === "physics-a1-kinematics")!,
      estHours: 2,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      dependsOnTopicId: null,
      availableFrom: null,
    },
    {
      ...dataset.topics.find((topic) => topic.id === "physics-a2-forces-momentum")!,
      estHours: 2,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      dependsOnTopicId: "physics-a1-kinematics",
      availableFrom: null,
    },
    {
      ...dataset.topics.find((topic) => topic.id === "physics-a3-work-energy-power")!,
      estHours: 2,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      dependsOnTopicId: "physics-a2-forces-momentum",
      availableFrom: null,
    },
  ];

  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-20T08:00:00"),
    endWeek: new Date("2026-04-03T08:00:00"),
    goals: [
      {
        id: "goal-physics-custom",
        title: "Finish the custom physics subset",
        subjectId: "physics-hl",
        deadline: "2027-06-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [subject],
    topics: customTopics,
    fixedEvents: dataset.fixedEvents,
    sickDays: [],
    focusedDays: [],
    preferences: dataset.preferences,
    existingStudyBlocks: [],
  });

  const progress = getSubjectProgress(
    subject,
    customTopics,
    result.studyBlocks,
    new Date("2026-03-20T08:00:00"),
  );

  assert.equal(progress.scheduledFutureHours, 6);
  assert.equal(progress.unscheduledHours, 0);
});

test("weekly allocation keeps filling after sequential topics unlock midweek", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const subject = dataset.subjects.find((candidate) => candidate.id === "physics-hl");

  assert.ok(subject, "expected physics subject");

  const sequentialTopics: Topic[] = [
    {
      ...dataset.topics.find((topic) => topic.id === "physics-a1-kinematics")!,
      estHours: 6,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      dependsOnTopicId: null,
      availableFrom: null,
    },
    {
      ...dataset.topics.find((topic) => topic.id === "physics-a2-forces-momentum")!,
      estHours: 6,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      dependsOnTopicId: "physics-a1-kinematics",
      availableFrom: null,
    },
  ];

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T08:00:00"),
    goals: [
      {
        id: "goal-physics-sequential",
        title: "Finish sequential physics topics",
        subjectId: "physics-hl",
        deadline: "2027-06-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [subject],
    topics: sequentialTopics,
    fixedEvents: [],
    sickDays: [],
    focusedDays: [],
    preferences: dataset.preferences,
    lockedBlocks: [],
    existingPlannedBlocks: [],
    horizonStartDate: new Date("2026-03-20T08:00:00"),
  });

  const scheduledHours = result.studyBlocks
    .filter((block) => block.subjectId === "physics-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0) / 60;

  assert.equal(scheduledHours >= 12, true);
  assert.equal(
    result.studyBlocks.some((block) => block.topicId === "physics-a2-forces-momentum"),
    true,
  );
});

test("topics with remaining hours are still schedulable even if a stale status says strong", () => {
  const candidates = buildTaskCandidates({
    topics: [
      {
        id: "nt-foundation-stale-strong",
        subjectId: "olympiad",
        unitId: "olympiad-number-theory-1",
        unitTitle: "Olympiad - Number Theory Foundations",
        title: "NT Foundations stale strong",
        order: 1,
        estHours: 5.4,
        completedHours: 0,
        mastery: 4,
        status: "strong",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: null,
        sequenceGroup: "olympiad-nt",
        sequenceStage: "foundation",
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 3,
        preferredBlockTypes: ["standard_focus"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
    ],
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-20T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(candidates.length, 1);
  assert.equal(candidates[0]?.topicId, "nt-foundation-stale-strong");
});

test("olympiad advanced candidates stay blocked until same-strand foundations are fully completed", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiadTopics = dataset.topics.filter((topic) => topic.subjectId === "olympiad");

  const blockedCandidates = buildTaskCandidates({
    topics: olympiadTopics,
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-20T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    blockedCandidates.some((candidate) => candidate.topicId === "olympiad-number-theory-valuations"),
    false,
  );

  const completedFoundations = olympiadTopics.map((topic) => {
    if (topic.sequenceStage === "foundation") {
      return {
        ...topic,
        completedHours: topic.estHours,
        mastery: 5,
        status: "strong" as const,
      };
    }

    return topic;
  });

  const unlockedCandidates = buildTaskCandidates({
    topics: completedFoundations,
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-20T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });
  const advancedCandidate = unlockedCandidates.find(
    (candidate) => candidate.topicId === "olympiad-number-theory-valuations",
  );

  assert.ok(advancedCandidate, "expected number theory advanced candidate once foundations are completed");
  assert.equal(advancedCandidate?.availableAt, null);
});

test("olympiad advanced and gold-phase candidates unlock once foundations are fully placed earlier", () => {
  const dataset = buildSeedDataset(new Date("2026-03-23T08:00:00"));
  const olympiadTopics = dataset.topics.filter((topic) => topic.subjectId === "olympiad");
  const foundationTopics = olympiadTopics.filter((topic) => topic.sequenceStage === "foundation");
  const foundationBlocks = foundationTopics.map((topic, index) =>
    {
      const day = addDays(new Date("2026-03-24T00:00:00.000Z"), index);
      const start = createDateAtTime(day, "08:00");
      const end = createDateAtTime(day, "14:00");

      return createStudyBlock({
        id: `foundation-${topic.id}`,
        weekStart: day < new Date("2026-03-30T00:00:00.000Z") ? "2026-03-23" : "2026-03-30",
        date: start.toISOString().slice(0, 10),
        start: start.toISOString(),
        end: end.toISOString(),
        subjectId: "olympiad",
        topicId: topic.id,
        title: topic.title,
        estimatedMinutes: Math.round(topic.estHours * 60),
      });
    },
  );

  const advancedCandidates = buildTaskCandidates({
    topics: olympiadTopics,
    existingPlannedBlocks: foundationBlocks,
    referenceDate: new Date("2026-03-30T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  const numberTheoryAdvanced = advancedCandidates.find(
    (candidate) => candidate.topicId === "olympiad-number-theory-valuations",
  );

  assert.ok(numberTheoryAdvanced, "expected advanced Olympiad topic once the foundation frontier is placed");
  assert.equal(numberTheoryAdvanced?.availableAt?.slice(0, 10), "2026-03-31");

  const goldCandidates = buildTaskCandidates({
    topics: olympiadTopics,
    existingPlannedBlocks: foundationBlocks,
    referenceDate: new Date("2026-07-06T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    goldCandidates.some((candidate) => candidate.topicId === "olympiad-gold-phase-week-1-mon"),
    true,
  );
});

test("horizon generation places olympiad advanced only after the foundation frontier is scheduled earlier", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiad = dataset.subjects.find((subject) => subject.id === "olympiad");

  assert.ok(olympiad, "expected olympiad subject");

  const customTopics: Topic[] = [
    {
      id: "olympiad-foundation-a",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad Foundations",
      title: "Foundation A",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 1.5,
      completedHours: 0,
      difficulty: 3,
      status: "learning",
      mastery: 3,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      order: 1,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-foundation-b",
      subjectId: "olympiad",
      unitId: "olympiad-geometry-1",
      unitTitle: "Olympiad Foundations",
      title: "Foundation B",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: "olympiad-foundation-a",
      sequenceGroup: "olympiad-geo",
      sequenceStage: "foundation",
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 1.5,
      completedHours: 0,
      difficulty: 3,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      order: 2,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-advanced-a",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-2",
      unitTitle: "Olympiad Advanced",
      title: "Advanced A",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: "olympiad-foundation-b",
      sequenceGroup: "olympiad-nt",
      sequenceStage: "advanced",
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 1.5,
      completedHours: 0,
      difficulty: 4,
      status: "not_started",
      mastery: 1,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      order: 3,
      paperCode: null,
      notes: "",
    },
  ];

  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-20T08:00:00"),
    endWeek: new Date("2026-04-13T08:00:00"),
    goals: [
      {
        id: "goal-olympiad-custom",
        title: "Finish custom olympiad frontier",
        subjectId: "olympiad",
        deadline: "2026-06-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [olympiad],
    topics: customTopics,
    fixedEvents: dataset.fixedEvents,
    sickDays: [],
    focusedDays: [],
    preferences: dataset.preferences,
    existingStudyBlocks: [],
  });

  const advancedBlock = result.studyBlocks.find((block) => block.topicId === "olympiad-advanced-a");
  const lastFoundationEnd = result.studyBlocks
    .filter((block) => block.topicId === "olympiad-foundation-a" || block.topicId === "olympiad-foundation-b")
    .map((block) => new Date(block.end).getTime())
    .sort((left, right) => right - left)[0];

  assert.ok(advancedBlock, "expected advanced Olympiad work to appear later in the horizon");
  assert.ok(lastFoundationEnd, "expected foundation blocks to be scheduled");
  assert.equal(new Date(advancedBlock.start).getTime() >= lastFoundationEnd, true);
});

test("seeded horizon keeps olympiad present week to week instead of dropping it for long gaps", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-20T08:00:00"),
    endWeek: new Date("2026-06-29T08:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    sickDays: dataset.sickDays,
    focusedDays: dataset.focusedDays,
    preferences: dataset.preferences,
    existingStudyBlocks: [],
  });

  const olympiadWeekStarts = new Set(
    result.studyBlocks
      .filter((block) => block.subjectId === "olympiad")
      .map((block) => toDateKey(startOfPlannerWeek(new Date(block.start)))),
  );

  const expectedWeeks = [
    "2026-03-30",
    "2026-04-06",
    "2026-04-13",
    "2026-04-20",
    "2026-04-27",
    "2026-05-04",
    "2026-05-11",
    "2026-05-18",
    "2026-05-25",
    "2026-06-01",
    "2026-06-08",
    "2026-06-15",
    "2026-06-22",
    "2026-06-29",
  ];

  expectedWeeks.forEach((weekStart) => {
    assert.equal(
      olympiadWeekStarts.has(weekStart),
      true,
      `expected Olympiad work during week starting ${weekStart}`,
    );
  });
});

test("gold-phase olympiad sessions are distributed across the actual week instead of bunching at the start", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-20T08:00:00"),
    endWeek: new Date("2026-07-20T08:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    sickDays: dataset.sickDays,
    focusedDays: dataset.focusedDays,
    preferences: dataset.preferences,
    existingStudyBlocks: [],
  });

  const julyDates = ["2026-07-15", "2026-07-16", "2026-07-17", "2026-07-18"];

  julyDates.forEach((dateKey) => {
    assert.equal(
      result.studyBlocks.some(
        (block) => block.date === dateKey && block.subjectId === "olympiad",
      ),
      true,
      `expected Olympiad work on ${dateKey} during the gold phase`,
    );
  });
});

test("stale future later number theory and advanced olympiad blocks are purged when the frontier is still incomplete", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const invalidLaterFoundationBlock = createStudyBlock({
    id: "nt-later-foundation-stale",
    subjectId: "olympiad",
    topicId: "olympiad-number-theory-congruence",
    title: "Modular arithmetic, inverses, orders, and CRT",
    weekStart: "2026-03-16",
    date: "2026-03-20",
    start: "2026-03-20T13:00:00.000Z",
    end: "2026-03-20T15:00:00.000Z",
    estimatedMinutes: 120,
  });
  const invalidAdvancedBlock = createStudyBlock({
    id: "nt-advanced-stale",
    subjectId: "olympiad",
    topicId: "olympiad-number-theory-valuations",
    title: "p-adic valuations, LTE, and divisibility depth",
    weekStart: "2026-03-16",
    date: "2026-03-20",
    start: "2026-03-20T16:00:00.000Z",
    end: "2026-03-20T18:00:00.000Z",
    estimatedMinutes: 120,
  });

  const validFoundationBlock = createStudyBlock({
    id: "nt-foundation-preserved",
    subjectId: "olympiad",
    topicId: "olympiad-number-theory-divisibility",
    title: "gcd structure, Euclidean algorithm, and divisibility control",
    weekStart: "2026-03-16",
    date: "2026-03-20",
    start: "2026-03-20T08:00:00.000Z",
    end: "2026-03-20T10:00:00.000Z",
    estimatedMinutes: 120,
  });

  const invalidIds = collectInvalidFutureOlympiadBlockIds({
    topics: dataset.topics,
    blocks: [invalidLaterFoundationBlock, invalidAdvancedBlock, validFoundationBlock],
    referenceDate: new Date("2026-03-20T08:00:00"),
  });

  assert.deepEqual(invalidIds, ["nt-later-foundation-stale", "nt-advanced-stale"]);
});

test("number theory frontier keeps later number theory topics blocked until the current frontier is placed earlier", () => {
  const topics: Topic[] = [
    {
      id: "olympiad-number-theory-divisibility",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "gcd structure, Euclidean algorithm, and divisibility control",
      order: 1,
      estHours: 6.5,
      completedHours: 3.9,
      mastery: 4,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      difficulty: 4,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-number-theory-congruence",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "Modular arithmetic, inverses, orders, and CRT",
      order: 2,
      estHours: 7,
      completedHours: 0,
      mastery: 2,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-divisibility",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      difficulty: 5,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
  ];

  const beforeFrontierCandidates = buildTaskCandidates({
    topics,
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-23T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    beforeFrontierCandidates.some((candidate) => candidate.topicId === "olympiad-number-theory-divisibility"),
    true,
  );
  assert.equal(
    beforeFrontierCandidates.some((candidate) => candidate.topicId === "olympiad-number-theory-congruence"),
    false,
  );

  const frontierCompletionBlock = createStudyBlock({
    id: "nt-divisibility-frontier",
    subjectId: "olympiad",
    topicId: "olympiad-number-theory-divisibility",
    title: "gcd structure, Euclidean algorithm, and divisibility control",
    weekStart: "2026-03-23",
    date: "2026-03-23",
    start: "2026-03-23T08:00:00.000Z",
    end: "2026-03-23T10:40:00.000Z",
    estimatedMinutes: 160,
  });

  const afterFrontierCandidates = buildTaskCandidates({
    topics,
    existingPlannedBlocks: [frontierCompletionBlock],
    referenceDate: new Date("2026-03-23T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    afterFrontierCandidates.some((candidate) => candidate.topicId === "olympiad-number-theory-congruence"),
    true,
  );
});

test("the first olympiad block of the day follows the current number theory frontier", () => {
  const referenceDate = new Date("2026-03-23T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const olympiadSubject = dataset.subjects.find((subject) => subject.id === "olympiad");

  assert.ok(olympiadSubject);

  const olympiadTopics: Topic[] = [
    {
      id: "olympiad-number-theory-divisibility",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "gcd structure, Euclidean algorithm, and divisibility control",
      order: 1,
      estHours: 6.5,
      completedHours: 3.9,
      mastery: 4,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      difficulty: 4,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-number-theory-congruence",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "Modular arithmetic, inverses, orders, and CRT",
      order: 2,
      estHours: 7,
      completedHours: 0,
      mastery: 2,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-divisibility",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      difficulty: 5,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-geometry-points-lines-polygons",
      subjectId: "olympiad",
      unitId: "olympiad-geometry-1",
      unitTitle: "Olympiad - Geometry Foundations",
      title: "Directed angles, cyclicity, similarity, and clean angle chase",
      order: 3,
      estHours: 6.5,
      completedHours: 0,
      mastery: 0,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      difficulty: 5,
      sequenceGroup: "olympiad-geo",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
  ];

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: [
      {
        id: "goal-olympiad",
        title: "Olympiad frontier goal",
        subjectId: "olympiad",
        deadline: "2027-06-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [olympiadSubject!],
    topics: olympiadTopics,
    fixedEvents: [],
    preferences: dataset.preferences,
  });

  const firstOlympiadBlock = result.studyBlocks.find((block) => block.subjectId === "olympiad");

  assert.ok(firstOlympiadBlock);
  assert.equal(firstOlympiadBlock?.topicId, "olympiad-number-theory-divisibility");
});

test("unfinished number theory frontier keeps olympiad on number theory until that strand is covered", () => {
  const referenceDate = new Date("2026-03-23T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const olympiadSubject = dataset.subjects.find((subject) => subject.id === "olympiad");

  assert.ok(olympiadSubject);

  const olympiadTopics: Topic[] = [
    {
      id: "olympiad-number-theory-divisibility",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "gcd structure, Euclidean algorithm, and divisibility control",
      order: 1,
      estHours: 6.5,
      completedHours: 3.9,
      mastery: 4,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      difficulty: 4,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-number-theory-congruence",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "Modular arithmetic, inverses, orders, and CRT",
      order: 2,
      estHours: 7,
      completedHours: 0,
      mastery: 2,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-divisibility",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      difficulty: 5,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-geometry-points-lines-polygons",
      subjectId: "olympiad",
      unitId: "olympiad-geometry-1",
      unitTitle: "Olympiad - Geometry Foundations",
      title: "Directed angles, cyclicity, similarity, and clean angle chase",
      order: 3,
      estHours: 6.5,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      difficulty: 5,
      sequenceGroup: "olympiad-geo",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
  ];

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: [
      {
        id: "goal-olympiad",
        title: "Olympiad frontier goal",
        subjectId: "olympiad",
        deadline: "2027-06-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [olympiadSubject!],
    topics: olympiadTopics,
    fixedEvents: [],
    preferences: dataset.preferences,
  });

  const olympiadBlocks = result.studyBlocks.filter((block) => block.subjectId === "olympiad");
  const firstNonNumberTheoryIndex = olympiadBlocks.findIndex(
    (block) => !block.topicId?.startsWith("olympiad-number-theory-"),
  );

  assert.equal(olympiadBlocks.length > 0, true);
  assert.notEqual(firstNonNumberTheoryIndex, -1);
  assert.equal(
    olympiadBlocks
      .slice(0, firstNonNumberTheoryIndex)
      .every((block) => block.topicId?.startsWith("olympiad-number-theory-")),
    true,
  );
});

test("partial number theory foundations still get concrete future coverage before later olympiad strands", () => {
  const referenceDate = new Date("2026-03-20T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const olympiadSubject = dataset.subjects.find((subject) => subject.id === "olympiad");

  assert.ok(olympiadSubject);

  const topics = dataset.topics.map((topic) => {
    if (topic.id === "olympiad-number-theory-divisibility") {
      return {
        ...topic,
        completedHours: 3.9,
        mastery: 4,
        status: "learning" as const,
      };
    }

    if (topic.id === "olympiad-number-theory-congruence") {
      return {
        ...topic,
        completedHours: 0,
        mastery: 2,
        status: "not_started" as const,
      };
    }

    return topic;
  });

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-16T00:00:00"),
    goals: dataset.goals.filter((goal) => goal.subjectId === "olympiad"),
    subjects: [olympiadSubject!],
    topics: topics.filter((topic) => topic.subjectId === "olympiad"),
    fixedEvents: [],
    preferences: dataset.preferences,
    lockedBlocks: [],
    existingPlannedBlocks: [],
    horizonStartDate: referenceDate,
  });

  const divisibilityBlocks = result.studyBlocks.filter(
    (block) => block.topicId === "olympiad-number-theory-divisibility",
  );
  const firstNonNumberTheoryBlock = result.studyBlocks.find(
    (block) =>
      block.subjectId === "olympiad" &&
      !block.topicId?.startsWith("olympiad-number-theory-"),
  );
  const progress = getSubjectProgress(
    olympiadSubject!,
    topics.filter((topic) => topic.subjectId === "olympiad"),
    result.studyBlocks,
    referenceDate,
  );

  assert.equal(divisibilityBlocks.length > 0, true);
  assert.equal(
    (progress.plannedFutureHoursByTopic["olympiad-number-theory-divisibility"] ?? 0) > 0,
    true,
  );

  if (firstNonNumberTheoryBlock) {
    const lastDivisibilityBlock = divisibilityBlocks.at(-1);
    assert.ok(lastDivisibilityBlock);
    assert.equal(
      new Date(lastDivisibilityBlock!.end).getTime() <=
        new Date(firstNonNumberTheoryBlock.start).getTime(),
      true,
    );
  }
});

test("number theory frontier top-off does not stretch into a giant overallocated block", () => {
  const referenceDate = new Date("2026-03-20T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const olympiadSubject = dataset.subjects.find((subject) => subject.id === "olympiad");

  assert.ok(olympiadSubject);

  const topics = [
    {
      ...dataset.topics.find((topic) => topic.id === "olympiad-number-theory-divisibility")!,
      completedHours: 6.5,
      mastery: 5,
      status: "strong" as const,
    },
    {
      ...dataset.topics.find((topic) => topic.id === "olympiad-number-theory-congruence")!,
      completedHours: 6.7,
      mastery: 4,
      status: "learning" as const,
    },
  ];

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: dataset.goals.filter((goal) => goal.subjectId === "olympiad"),
    subjects: [olympiadSubject!],
    topics,
    fixedEvents: [],
    preferences: dataset.preferences,
    lockedBlocks: [],
    existingPlannedBlocks: [],
    horizonStartDate: referenceDate,
  });

  const congruenceMinutes = result.studyBlocks
    .filter((block) => block.topicId === "olympiad-number-theory-congruence")
    .reduce((total, block) => total + block.estimatedMinutes, 0);

  assert.equal(congruenceMinutes <= 30, true);
});

test("subject progress caps already-planned-later hours at the topic's true remaining hours", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiad = dataset.subjects.find((subject) => subject.id === "olympiad");
  const congruence = dataset.topics.find((topic) => topic.id === "olympiad-number-theory-congruence");

  assert.ok(olympiad);
  assert.ok(congruence);

  const oversizedPlannedBlock = createStudyBlock({
    id: "oversized-congruence",
    weekStart: "2026-03-23",
    date: "2026-03-24",
    start: "2026-03-24T08:00:00.000Z",
    end: "2026-03-24T14:00:00.000Z",
    subjectId: "olympiad",
    topicId: congruence!.id,
    title: congruence!.title,
    estimatedMinutes: 360,
  });

  const progress = getSubjectProgress(
    olympiad!,
    dataset.topics,
    [oversizedPlannedBlock],
    new Date("2026-03-20T08:00:00"),
  );

  assert.equal(
    progress.plannedFutureHoursByTopic[congruence!.id],
    Number(Math.min(congruence!.estHours - congruence!.completedHours, 6).toFixed(1)),
  );
});

test("number theory frontier status tracks the earliest unfinished foundation topic", () => {
  const topics: Topic[] = [
    {
      id: "olympiad-number-theory-divisibility",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "Divisibility",
      order: 1,
      estHours: 6.5,
      completedHours: 3.9,
      mastery: 4,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      difficulty: 4,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
    {
      id: "olympiad-number-theory-congruence",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "Congruence",
      order: 2,
      estHours: 7,
      completedHours: 0,
      mastery: 1,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-divisibility",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      difficulty: 5,
      sequenceGroup: "olympiad-nt",
      sequenceStage: "foundation",
      sessionMode: "flexible",
      exactSessionMinutes: null,
      paperCode: null,
      notes: "",
    },
  ];

  const status = getOlympiadNumberTheoryFrontierStatus({
    topics,
    blocks: [],
  });

  assert.equal(status.frontierTopicId, "olympiad-number-theory-divisibility");
  assert.equal(status.blocked, true);
  assert.ok(status.remainingMinutes >= 150);
});

test("olympiad stage gating still works when legacy local topics are missing sequence metadata", () => {
  const legacyTopics: Topic[] = [
    {
      id: "olympiad-number-theory-divisibility",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "NT Foundations 1",
      order: 1,
      estHours: 2,
      completedHours: 0,
      mastery: 2,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: null,
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      difficulty: 3,
      preferredBlockTypes: ["standard_focus"],
      paperCode: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
    },
    {
      id: "olympiad-number-theory-congruence",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-1",
      unitTitle: "Olympiad - Number Theory Foundations",
      title: "NT Foundations 2",
      order: 2,
      estHours: 2,
      completedHours: 0,
      mastery: 2,
      status: "learning",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-divisibility",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      difficulty: 3,
      preferredBlockTypes: ["standard_focus"],
      paperCode: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
    },
    {
      id: "olympiad-number-theory-valuations",
      subjectId: "olympiad",
      unitId: "olympiad-number-theory-2",
      unitTitle: "Olympiad - Number Theory Advanced",
      title: "NT Advanced 1",
      order: 3,
      estHours: 2,
      completedHours: 0,
      mastery: 2,
      status: "not_started",
      reviewDue: null,
      lastStudiedAt: null,
      dependsOnTopicId: "olympiad-number-theory-congruence",
      availableFrom: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      subtopics: [],
      sourceMaterials: [],
      difficulty: 4,
      preferredBlockTypes: ["deep_work"],
      paperCode: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
    },
  ];

  const candidates = buildTaskCandidates({
    topics: legacyTopics,
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-20T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    candidates.some((candidate) => candidate.topicId === "olympiad-number-theory-valuations"),
    false,
  );
});

test("any incomplete olympiad foundation suppresses all olympiad advanced candidates globally", () => {
  const dataset = buildSeedDataset(new Date("2026-03-20T08:00:00"));
  const olympiadTopics = dataset.topics
    .filter((topic) => topic.subjectId === "olympiad")
    .map((topic) => {
      if (
        topic.id === "olympiad-geometry-points-lines-polygons" ||
        topic.id === "olympiad-geometry-triangle-centers"
      ) {
        return {
          ...topic,
          completedHours: topic.estHours,
          mastery: 5,
          status: "strong" as const,
        };
      }

      return topic;
    });

  const candidates = buildTaskCandidates({
    topics: olympiadTopics,
    existingPlannedBlocks: [],
    referenceDate: new Date("2026-03-20T08:00:00"),
    subjectDeadlinesById: { olympiad: "2027-06-30" },
  });

  assert.equal(
    candidates.some((candidate) => candidate.topicId === "olympiad-geometry-quadrilaterals-circles"),
    false,
  );
  assert.equal(
    candidates.some((candidate) => candidate.topicId === "olympiad-algebra-polynomials"),
    false,
  );
  assert.equal(
    candidates.some((candidate) => candidate.topicId === "olympiad-combinatorics-graph-theory"),
    false,
  );
});

test("validator flags dependent blocks that start before the prerequisite is fully covered", () => {
  const issues = validateGeneratedHorizon({
    topics: [
      {
        id: "foundation",
        subjectId: "olympiad",
        unitId: "u1",
        unitTitle: "Foundations",
        title: "Number Theory Foundations",
        order: 1,
        estHours: 3,
        completedHours: 0,
        mastery: 2,
        status: "learning",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: null,
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 3,
        preferredBlockTypes: ["standard_focus"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
      {
        id: "advanced",
        subjectId: "olympiad",
        unitId: "u1",
        unitTitle: "Advanced",
        title: "Number Theory Advanced",
        order: 2,
        estHours: 3,
        completedHours: 0,
        mastery: 2,
        status: "not_started",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: "foundation",
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 4,
        preferredBlockTypes: ["deep_work"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
    ],
    studyBlocks: [
      createStudyBlock({
        id: "foundation-1",
        subjectId: "olympiad",
        topicId: "foundation",
        estimatedMinutes: 60,
        start: "2026-03-24T08:00:00.000Z",
        end: "2026-03-24T09:00:00.000Z",
      }),
      createStudyBlock({
        id: "advanced-1",
        subjectId: "olympiad",
        topicId: "advanced",
        estimatedMinutes: 60,
        start: "2026-03-24T10:00:00.000Z",
        end: "2026-03-24T11:00:00.000Z",
      }),
    ],
    weeklyPlans: [],
  });

  assert.equal(
    issues.some((issue) => issue.code === "dependency-coverage-order-violation"),
    true,
  );
});

test("validator flags olympiad advanced blocks before same-strand foundations are fully completed", () => {
  const issues = validateGeneratedHorizon({
    topics: [
      {
        id: "nt-foundation-1",
        subjectId: "olympiad",
        unitId: "nt-1",
        unitTitle: "Olympiad - Number Theory Foundations",
        title: "NT Foundations 1",
        order: 1,
        estHours: 2,
        completedHours: 0,
        mastery: 2,
        status: "learning",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: null,
        sequenceGroup: "olympiad-nt",
        sequenceStage: "foundation",
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 3,
        preferredBlockTypes: ["standard_focus"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
      {
        id: "nt-foundation-2",
        subjectId: "olympiad",
        unitId: "nt-1",
        unitTitle: "Olympiad - Number Theory Foundations",
        title: "NT Foundations 2",
        order: 2,
        estHours: 2,
        completedHours: 0,
        mastery: 2,
        status: "learning",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: "nt-foundation-1",
        sequenceGroup: "olympiad-nt",
        sequenceStage: "foundation",
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 3,
        preferredBlockTypes: ["standard_focus"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
      {
        id: "nt-advanced-1",
        subjectId: "olympiad",
        unitId: "nt-2",
        unitTitle: "Olympiad - Number Theory Advanced",
        title: "NT Advanced 1",
        order: 3,
        estHours: 2,
        completedHours: 0,
        mastery: 2,
        status: "not_started",
        reviewDue: null,
        lastStudiedAt: null,
        dependsOnTopicId: "nt-foundation-2",
        sequenceGroup: "olympiad-nt",
        sequenceStage: "advanced",
        availableFrom: null,
        minDaysAfterDependency: null,
        maxDaysAfterDependency: null,
        subtopics: [],
        sourceMaterials: [],
        difficulty: 4,
        preferredBlockTypes: ["deep_work"],
        paperCode: null,
        sessionMode: "flexible",
        exactSessionMinutes: null,
      },
    ],
    studyBlocks: [
      createStudyBlock({
        id: "nt-foundation-block",
        subjectId: "olympiad",
        topicId: "nt-foundation-1",
        estimatedMinutes: 120,
        start: "2026-03-24T08:00:00.000Z",
        end: "2026-03-24T10:00:00.000Z",
      }),
      createStudyBlock({
        id: "nt-advanced-block",
        subjectId: "olympiad",
        topicId: "nt-advanced-1",
        estimatedMinutes: 120,
        start: "2026-03-24T10:30:00.000Z",
        end: "2026-03-24T12:30:00.000Z",
      }),
    ],
    weeklyPlans: [],
  });

  assert.equal(
    issues.some(
      (issue) =>
        issue.code === "dependency-coverage-order-violation" &&
        issue.topicId === "nt-advanced-1",
    ),
    true,
  );
});

test("regeneration preserves user-touched future blocks", () => {
  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        isAutoGenerated: false,
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        notes: "Keep this slot for tutoring notes",
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        rescheduleCount: 1,
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        assignmentLocked: true,
        assignmentEditedAt: "2026-03-20T08:00:00.000Z",
      }),
    ),
    true,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        assignmentLocked: false,
        assignmentEditedAt: "2026-03-20T08:00:00.000Z",
        status: "rescheduled",
        notes: "",
        rescheduleCount: 0,
        isAutoGenerated: true,
      }),
    ),
    false,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        status: "planned",
        notes: "",
        rescheduleCount: 0,
        isAutoGenerated: true,
      }),
    ),
    false,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        notes: "Keep this slot for tutoring notes",
      }),
      { preserveFlexibleFutureBlocks: false },
    ),
    false,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        rescheduleCount: 1,
      }),
      { preserveFlexibleFutureBlocks: false },
    ),
    false,
  );

  assert.equal(
    shouldPreserveStudyBlockOnRegeneration(
      createStudyBlock({
        isAutoGenerated: false,
      }),
      { preserveFlexibleFutureBlocks: false },
    ),
    true,
  );
});

test("manual block reassignment only offers topics valid for the fixed slot", () => {
  const block = createStudyBlock({
    id: "manual-slot",
    subjectId: "physics-hl",
    topicId: "physics-current",
    estimatedMinutes: 120,
    start: "2026-09-22T08:00:00.000Z",
    end: "2026-09-22T10:00:00.000Z",
  });
  const topics: Topic[] = [
    {
      id: "physics-flex-topic",
      subjectId: "physics-hl",
      unitId: "physics-flex",
      unitTitle: "Physics flexible",
      title: "Flexible topic",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: null,
      sequenceStage: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 3,
      completedHours: 0,
      difficulty: 3,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      order: 1,
      paperCode: null,
      notes: "",
    },
    {
      id: "physics-paper-valid",
      subjectId: "physics-hl",
      unitId: "physics-papers",
      unitTitle: "Physics papers",
      title: "Paper 1A + 1B",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: null,
      sequenceStage: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "exam",
      exactSessionMinutes: 120,
      estHours: 2,
      completedHours: 0,
      difficulty: 4,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      order: 2,
      paperCode: "PHY-W01-P1AB",
      notes: "",
    },
    {
      id: "physics-paper-invalid",
      subjectId: "physics-hl",
      unitId: "physics-papers",
      unitTitle: "Physics papers",
      title: "Paper 2",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: null,
      sequenceStage: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "exam",
      exactSessionMinutes: 150,
      estHours: 2.5,
      completedHours: 0,
      difficulty: 4,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["deep_work"],
      order: 3,
      paperCode: "PHY-W01-P2",
      notes: "",
    },
  ];

  const candidates = getAssignableTaskCandidatesForBlock({
    block,
    topics,
    existingPlannedBlocks: [],
    subjectDeadlinesById: { "physics-hl": "2027-06-30" },
  });

  assert.equal(
    candidates.some((candidate) => candidate.topicId === "physics-flex-topic"),
    true,
  );
  assert.equal(
    candidates.some((candidate) => candidate.topicId === "physics-paper-valid"),
    true,
  );
  assert.equal(
    candidates.some((candidate) => candidate.topicId === "physics-paper-invalid"),
    false,
  );
});

test("manual block reassignment can target a valid topic even when it is already fully planned later", () => {
  const block = createStudyBlock({
    id: "manual-slot-rebalance",
    subjectId: "physics-hl",
    topicId: "physics-current",
    estimatedMinutes: 120,
    start: "2026-09-22T08:00:00.000Z",
    end: "2026-09-22T10:00:00.000Z",
  });
  const topics: Topic[] = [
    {
      id: "physics-current",
      subjectId: "physics-hl",
      unitId: "physics-foundations",
      unitTitle: "Physics foundations",
      title: "Current physics topic",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: null,
      sequenceStage: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 5,
      completedHours: 1,
      difficulty: 3,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      order: 1,
      paperCode: null,
      notes: "",
    },
    {
      id: "physics-target-fully-planned",
      subjectId: "physics-hl",
      unitId: "physics-advanced",
      unitTitle: "Physics advanced",
      title: "Already planned later topic",
      subtopics: [],
      availableFrom: null,
      dependsOnTopicId: null,
      sequenceGroup: null,
      sequenceStage: null,
      minDaysAfterDependency: null,
      maxDaysAfterDependency: null,
      sessionMode: "flexible",
      exactSessionMinutes: null,
      estHours: 2,
      completedHours: 0,
      difficulty: 4,
      status: "learning",
      mastery: 2,
      reviewDue: null,
      lastStudiedAt: null,
      sourceMaterials: [],
      preferredBlockTypes: ["standard_focus"],
      order: 2,
      paperCode: null,
      notes: "",
    },
  ];
  const laterPlannedBlock = createStudyBlock({
    id: "later-block",
    subjectId: "physics-hl",
    topicId: "physics-target-fully-planned",
    title: "Already planned later topic",
    estimatedMinutes: 120,
    start: "2026-09-23T08:00:00.000Z",
    end: "2026-09-23T10:00:00.000Z",
  });

  const candidates = getAssignableTaskCandidatesForBlock({
    block,
    topics,
    existingPlannedBlocks: [laterPlannedBlock],
    subjectDeadlinesById: { "physics-hl": "2027-06-30" },
  });

  assert.equal(
    candidates.some((candidate) => candidate.topicId === "physics-target-fully-planned"),
    true,
  );
});

test("generated horizon passes core validation checks for a short seeded window", () => {
  const referenceDate = new Date("2026-03-13T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const result = generateStudyPlanHorizon({
    startWeek: new Date("2026-03-09T00:00:00"),
    endWeek: new Date("2026-03-30T00:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    preferences: dataset.preferences,
  });

  const issues = validateGeneratedHorizon({
    studyBlocks: result.studyBlocks,
    topics: dataset.topics,
    weeklyPlans: result.weeklyPlans,
  });

  const errorIssues = issues.filter((issue) => issue.severity === "error");
  assert.deepEqual(
    errorIssues,
    [],
    `expected no blocking validation issues, got: ${errorIssues.map((issue) => issue.message).join(" | ")}`,
  );
});

test("single-subject focused days reserve most of the day for that subject", () => {
  const referenceDate = new Date("2026-03-16T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const focusedDate = "2026-03-23";
  const basePhysics = dataset.subjects.find((subject) => subject.id === "physics-hl");
  const baseChemistry = dataset.subjects.find((subject) => subject.id === "chemistry-hl");

  assert.ok(basePhysics);
  assert.ok(baseChemistry);

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: [
      {
        id: "goal-physics",
        title: "Physics deadline",
        subjectId: "physics-hl",
        deadline: "2026-04-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
      {
        id: "goal-chemistry",
        title: "Chemistry deadline",
        subjectId: "chemistry-hl",
        deadline: "2026-05-30",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [
      { ...basePhysics, deadline: "2026-04-30" },
      { ...baseChemistry, deadline: "2026-05-30" },
    ],
    topics: [
      {
        id: "physics-focus-topic",
        subjectId: "physics-hl",
        unitId: "focus-unit-physics",
        unitTitle: "Focus unit",
        title: "Physics focus topic",
        subtopics: ["Focused physics work"],
        estHours: 10,
        completedHours: 0,
        difficulty: 3,
        status: "not_started",
        mastery: 0,
        reviewDue: null,
        lastStudiedAt: null,
        sourceMaterials: [],
        preferredBlockTypes: ["drill"],
        order: 1,
      },
      {
        id: "chemistry-background-topic",
        subjectId: "chemistry-hl",
        unitId: "focus-unit-chem",
        unitTitle: "Background unit",
        title: "Chemistry background topic",
        subtopics: ["Background chemistry work"],
        estHours: 10,
        completedHours: 0,
        difficulty: 3,
        status: "not_started",
        mastery: 0,
        reviewDue: null,
        lastStudiedAt: null,
        sourceMaterials: [],
        preferredBlockTypes: ["drill"],
        order: 1,
      },
    ],
    fixedEvents: [],
    preferences: {
      ...dataset.preferences,
      reservedCommitmentRules: [],
      schoolSchedule: {
        ...dataset.preferences.schoolSchedule,
        enabled: false,
        terms: [],
      },
      holidaySchedule: {
        ...dataset.preferences.holidaySchedule,
        enabled: true,
      },
    },
    focusedDays: [
      {
        id: "focus-physics",
        date: focusedDate,
        subjectIds: ["physics-hl"],
      },
    ],
  });

  const focusedDayBlocks = result.studyBlocks.filter(
    (block) => block.date === focusedDate && block.subjectId,
  );
  const totalMinutes = focusedDayBlocks.reduce((total, block) => total + block.estimatedMinutes, 0);
  const physicsMinutes = focusedDayBlocks
    .filter((block) => block.subjectId === "physics-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0);

  assert.ok(totalMinutes >= 60, "expected focused day to contain real study time");
  assert.ok(physicsMinutes / totalMinutes >= 0.65);
});

test("focused days materially increase the chosen subject in the seeded schedule", () => {
  const referenceDate = new Date("2026-03-19T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const focusedDate = "2026-03-25";

  const withoutFocus = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    preferences: dataset.preferences,
    focusedDays: [],
  });
  const withFocus = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    preferences: dataset.preferences,
    focusedDays: [
      {
        id: "focus-physics-seeded",
        date: focusedDate,
        subjectIds: ["physics-hl"],
      },
    ],
  });

  const physicsMinutesWithoutFocus = withoutFocus.studyBlocks
    .filter((block) => block.date === focusedDate && block.subjectId === "physics-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0);
  const physicsMinutesWithFocus = withFocus.studyBlocks
    .filter((block) => block.date === focusedDate && block.subjectId === "physics-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0);

  assert.ok(physicsMinutesWithFocus >= physicsMinutesWithoutFocus + 120);
});

test("multi-subject focused days split work by pressure instead of equally", () => {
  const referenceDate = new Date("2026-03-16T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const basePhysics = dataset.subjects.find((subject) => subject.id === "physics-hl");
  const baseChemistry = dataset.subjects.find((subject) => subject.id === "chemistry-hl");

  assert.ok(basePhysics);
  assert.ok(baseChemistry);

  const result = generateStudyPlanForWeek({
    weekStart: new Date("2026-03-23T00:00:00"),
    goals: [
      {
        id: "goal-physics",
        title: "Physics deadline",
        subjectId: "physics-hl",
        deadline: "2026-04-15",
        targetCompletion: 1,
        priorityWeight: 1,
      },
      {
        id: "goal-chemistry",
        title: "Chemistry deadline",
        subjectId: "chemistry-hl",
        deadline: "2026-06-15",
        targetCompletion: 1,
        priorityWeight: 1,
      },
    ],
    subjects: [
      { ...basePhysics, deadline: "2026-04-15" },
      { ...baseChemistry, deadline: "2026-06-15" },
    ],
    topics: [
      {
        id: "physics-focus-topic",
        subjectId: "physics-hl",
        unitId: "focus-unit-physics",
        unitTitle: "Focus unit",
        title: "Physics focus topic",
        subtopics: ["High-priority physics work"],
        estHours: 8,
        completedHours: 0,
        difficulty: 3,
        status: "not_started",
        mastery: 0,
        reviewDue: null,
        lastStudiedAt: null,
        sourceMaterials: [],
        preferredBlockTypes: ["drill"],
        order: 1,
      },
      {
        id: "chemistry-focus-topic",
        subjectId: "chemistry-hl",
        unitId: "focus-unit-chem",
        unitTitle: "Focus unit",
        title: "Chemistry focus topic",
        subtopics: ["Lower-pressure chemistry work"],
        estHours: 8,
        completedHours: 0,
        difficulty: 3,
        status: "not_started",
        mastery: 0,
        reviewDue: null,
        lastStudiedAt: null,
        sourceMaterials: [],
        preferredBlockTypes: ["drill"],
        order: 1,
      },
    ],
    fixedEvents: [],
    preferences: {
      ...dataset.preferences,
      reservedCommitmentRules: [],
      schoolSchedule: {
        ...dataset.preferences.schoolSchedule,
        enabled: false,
        terms: [],
      },
      holidaySchedule: {
        ...dataset.preferences.holidaySchedule,
        enabled: true,
      },
    },
    focusedDays: [
      {
        id: "focus-physics-chem",
        date: "2026-03-23",
        subjectIds: ["physics-hl", "chemistry-hl"],
      },
    ],
  });

  const focusedDayBlocks = result.studyBlocks.filter(
    (block) => block.date === "2026-03-23" && block.subjectId,
  );
  const physicsMinutes = focusedDayBlocks
    .filter((block) => block.subjectId === "physics-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0);
  const chemistryMinutes = focusedDayBlocks
    .filter((block) => block.subjectId === "chemistry-hl")
    .reduce((total, block) => total + block.estimatedMinutes, 0);

  assert.ok(physicsMinutes > 0, "expected at least some physics time on the focused day");
  assert.ok(physicsMinutes >= chemistryMinutes);
});

test("focused days still keep all main-subject topic hours fully scheduled in the seeded horizon", () => {
  const referenceDate = new Date("2026-03-21T08:00:00");
  const dataset = buildSeedDataset(referenceDate);
  const result = generateStudyPlanHorizon({
    startWeek: startOfPlannerWeek(referenceDate),
    goals: dataset.goals,
    subjects: dataset.subjects,
    topics: dataset.topics,
    fixedEvents: dataset.fixedEvents,
    preferences: dataset.preferences,
    sickDays: dataset.sickDays,
    focusedDays: [
      { id: "focus-1", date: "2026-03-23", subjectIds: ["physics-hl"] },
      { id: "focus-2", date: "2026-03-24", subjectIds: ["maths-aa-hl"] },
      { id: "focus-3", date: "2026-03-25", subjectIds: ["chemistry-hl"] },
      { id: "focus-4", date: "2026-03-26", subjectIds: ["olympiad"] },
      { id: "focus-5", date: "2026-03-27", subjectIds: ["physics-hl", "maths-aa-hl"] },
    ],
    existingStudyBlocks: [],
  });

  for (const subjectId of ["maths-aa-hl", "physics-hl", "chemistry-hl", "olympiad"] as const) {
    const subject = dataset.subjects.find((candidate) => candidate.id === subjectId);
    assert.ok(subject);
    const progress = getSubjectProgress(subject, dataset.topics, result.studyBlocks, referenceDate);
    assert.equal(
      progress.unscheduledHours,
      0,
      `expected ${subjectId} to stay fully scheduled even with focused days`,
    );
  }
});

test("overlapping sick-day ranges resolve to the highest active severity", () => {
  const severity = getActiveSickDaySeverity(new Date("2026-03-18T10:00:00"), [
    {
      id: "light-range",
      startDate: "2026-03-17",
      endDate: "2026-03-20",
      severity: "light",
    },
    {
      id: "severe-range",
      startDate: "2026-03-18",
      endDate: "2026-03-18",
      severity: "severe",
    },
  ]);

  assert.equal(severity, "severe");
});

test("sick-day severity lightens capacity and keeps homework while reducing piano", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
  };

  const lightProfile = resolveDailyScheduleProfile(
    new Date("2026-03-17T10:00:00"),
    preferences,
    [],
  );
  const reducedLightProfile = resolveDailyScheduleProfile(
    new Date("2026-03-17T10:00:00"),
    preferences,
    [
      {
        id: "light",
        startDate: "2026-03-17",
        endDate: "2026-03-17",
        severity: "light",
      },
    ],
  );

  assert.equal(reducedLightProfile.maxHeavySessionsPerDay, 1);
  assert.ok(reducedLightProfile.maxStudyHoursPerDay < lightProfile.maxStudyHoursPerDay);

  const lightCommitments = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [
      {
        id: "light",
        startDate: "2026-03-17",
        endDate: "2026-03-17",
        severity: "light",
      },
    ],
  ).filter((window) => window.start.startsWith("2026-03-17"));

  const pianoCommitment = lightCommitments.find((window) => window.label === "Piano");
  const homeworkCommitment = lightCommitments.find((window) => window.label === "Homework");

  assert.ok(pianoCommitment);
  assert.equal(
    Math.round(
      (new Date(pianoCommitment!.end).getTime() - new Date(pianoCommitment!.start).getTime()) /
        60000,
    ),
    30,
  );
  assert.ok(homeworkCommitment);
  assert.equal(
    Math.round(
      (new Date(homeworkCommitment!.end).getTime() - new Date(homeworkCommitment!.start).getTime()) /
        60000,
    ),
    90,
  );
});

test("moderate and severe sick days remove piano and restrict heavier study modes", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
  };

  const moderateProfile = resolveDailyScheduleProfile(
    new Date("2026-03-18T10:00:00"),
    preferences,
    [
      {
        id: "moderate",
        startDate: "2026-03-18",
        endDate: "2026-03-18",
        severity: "moderate",
      },
    ],
  );
  const severeProfile = resolveDailyScheduleProfile(
    new Date("2026-03-19T10:00:00"),
    preferences,
    [
      {
        id: "severe",
        startDate: "2026-03-19",
        endDate: "2026-03-19",
        severity: "severe",
      },
    ],
  );

  assert.equal(moderateProfile.maxHeavySessionsPerDay, 0);
  assert.deepEqual(moderateProfile.allowedBlockTypes, ["standard_focus", "drill", "review", "recovery"]);
  assert.equal(severeProfile.maxHeavySessionsPerDay, 0);
  assert.deepEqual(severeProfile.allowedBlockTypes, ["drill", "review", "recovery"]);

  const moderateCommitments = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [
      {
        id: "moderate",
        startDate: "2026-03-18",
        endDate: "2026-03-18",
        severity: "moderate",
      },
    ],
  ).filter((window) => window.start.startsWith("2026-03-18"));

  assert.equal(
    moderateCommitments.some((window) => window.label === "Piano"),
    false,
  );
  assert.equal(
    moderateCommitments.some((window) => window.label === "Homework"),
    true,
  );
});

test("piano commitment rules support single-day additions and removals", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const pianoRule = dataset.preferences.reservedCommitmentRules.find(
    (rule) => rule.id === "piano-practice",
  );

  assert.ok(pianoRule, "expected seeded piano rule");

  const monday = new Date("2026-03-16T10:00:00");
  const tuesday = new Date("2026-03-17T10:00:00");

  assert.equal(isReservedCommitmentRuleActiveOnDate(pianoRule!, monday, false), false);
  assert.equal(isReservedCommitmentRuleActiveOnDate(pianoRule!, tuesday, false), true);

  const withMondayAddition = {
    ...pianoRule!,
    additionalDates: ["2026-03-16"],
  };
  const withTuesdayRemoval = {
    ...pianoRule!,
    excludedDates: ["2026-03-17"],
  };

  assert.equal(isReservedCommitmentRuleActiveOnDate(withMondayAddition, monday, false), true);
  assert.equal(isReservedCommitmentRuleActiveOnDate(withTuesdayRemoval, tuesday, false), false);
});

test("homework commitment rules can be explicitly added outside normal school-term dates", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const homeworkRule = dataset.preferences.reservedCommitmentRules.find(
    (rule) => rule.id === "term-homework",
  );

  assert.ok(homeworkRule, "expected seeded homework rule");

  const holidayDate = new Date("2026-07-10T10:00:00");
  assert.equal(isReservedCommitmentRuleActiveOnDate(homeworkRule!, holidayDate, false), false);

  const withHolidayAddition = {
    ...homeworkRule!,
    additionalDates: ["2026-07-10"],
  };

  assert.equal(isReservedCommitmentRuleActiveOnDate(withHolidayAddition, holidayDate, false), true);
});

test("homework duration overrides change the reserved commitment length for one date", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    schoolSchedule: {
      ...dataset.preferences.schoolSchedule,
      enabled: true,
      weekdays: [1, 2, 3, 4, 5],
      terms: [
        {
          id: "term-1",
          label: "Term 1",
          startDate: "2026-03-01",
          endDate: "2026-03-31",
        },
      ],
    },
    reservedCommitmentRules: dataset.preferences.reservedCommitmentRules.map((rule) =>
      rule.id === "term-homework"
        ? {
            ...rule,
            durationOverrides: {
              ...(rule.durationOverrides ?? {}),
              "2026-03-17": 120,
            },
          }
        : rule,
    ),
  };

  const commitment = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [],
  ).find(
    (window) => window.label === "Homework" && window.start.startsWith("2026-03-17"),
  );

  assert.ok(commitment);
  assert.equal(
    Math.round(
      (new Date(commitment!.end).getTime() - new Date(commitment!.start).getTime()) / 60000,
    ),
    120,
  );
});

test("piano time overrides move the reserved commitment to the selected one-day start time", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    reservedCommitmentRules: dataset.preferences.reservedCommitmentRules.map((rule) =>
      rule.id === "piano-practice"
        ? {
            ...rule,
            timeOverrides: {
              ...(rule.timeOverrides ?? {}),
              "2026-03-17": {
                start: "16:30",
              },
            },
          }
        : rule,
    ),
  };

  const commitment = expandReservedCommitmentWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [],
  ).find(
    (window) => window.label === "Piano" && window.start.startsWith("2026-03-17"),
  );

  assert.ok(commitment);
  assert.equal(
    commitment?.start,
    createDateAtTime(fromDateKey("2026-03-17"), "16:30").toISOString(),
  );
  assert.equal(
    commitment?.end,
    createDateAtTime(fromDateKey("2026-03-17"), "17:30").toISOString(),
  );
});

test("lunch and dinner time overrides change the recovery windows for one date", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    lockedRecoveryWindows: dataset.preferences.lockedRecoveryWindows.map((window) => {
      if (window.label === "Lunch break") {
        return {
          ...window,
          timeOverrides: {
            ...(window.timeOverrides ?? {}),
            "2026-03-17": {
              start: "12:30",
              end: "14:00",
            },
          },
        };
      }

      if (window.label === "Dinner reset") {
        return {
          ...window,
          timeOverrides: {
            ...(window.timeOverrides ?? {}),
            "2026-03-17": {
              start: "19:45",
              end: "20:30",
            },
          },
        };
      }

      return window;
    }),
  };

  const windows = expandLockedRecoveryWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [],
    [],
    false,
  );
  const lunch = windows.find(
    (window) => window.label === "Lunch break" && window.dateKey === "2026-03-17",
  );
  const dinner = windows.find(
    (window) => window.label === "Dinner reset" && window.dateKey === "2026-03-17",
  );

  assert.equal(
    lunch?.start,
    createDateAtTime(fromDateKey("2026-03-17"), "12:30").toISOString(),
  );
  assert.equal(
    lunch?.end,
    createDateAtTime(fromDateKey("2026-03-17"), "14:00").toISOString(),
  );
  assert.equal(
    dinner?.start,
    createDateAtTime(fromDateKey("2026-03-17"), "19:45").toISOString(),
  );
  assert.equal(
    dinner?.end,
    createDateAtTime(fromDateKey("2026-03-17"), "20:30").toISOString(),
  );
});

test("dinner stays exclusive and pushes overlapping sunday recovery out of its slot", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    lockedRecoveryWindows: dataset.preferences.lockedRecoveryWindows.map((window) => {
      if (window.label === "Dinner reset") {
        return {
          ...window,
          timeOverrides: {
            ...(window.timeOverrides ?? {}),
            "2026-03-22": {
              start: "19:45",
              end: "20:30",
            },
          },
        };
      }

      return window;
    }),
  };

  const windows = expandLockedRecoveryWindowsForWeek(
    new Date("2026-03-16T00:00:00"),
    preferences,
    [],
    [],
    [],
    false,
  );
  const dinner = windows.find(
    (window) => window.label === "Dinner reset" && window.dateKey === "2026-03-22",
  );
  const sundayRecovery = windows.find(
    (window) => window.label === "Sunday recovery" && window.dateKey === "2026-03-22",
  );

  assert.ok(dinner);
  assert.ok(sundayRecovery);
  assert.equal(
    dinner?.start,
    createDateAtTime(fromDateKey("2026-03-22"), "19:45").toISOString(),
  );
  assert.equal(
    dinner?.end,
    createDateAtTime(fromDateKey("2026-03-22"), "20:30").toISOString(),
  );
  assert.equal(
    sundayRecovery?.start,
    createDateAtTime(fromDateKey("2026-03-22"), "20:30").toISOString(),
  );
  assert.equal(
    sundayRecovery?.end,
    createDateAtTime(fromDateKey("2026-03-22"), "22:30").toISOString(),
  );
});

test("dinner still blocks study slots even in skip movable recovery passes", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    dailyStudyWindow: {
      start: "18:00",
      end: "21:30",
    },
    holidaySchedule: {
      ...dataset.preferences.holidaySchedule,
      dailyStudyWindow: {
        start: "18:00",
        end: "21:30",
      },
    },
    reservedCommitmentRules: [],
  };

  const slots = calculateFreeSlots({
    weekStart: new Date("2026-03-23T00:00:00"),
    fixedEvents: [],
    preferences,
    skipMovableRecovery: true,
  }).filter((slot) => slot.dateKey === "2026-03-24");

  assert.equal(slots.length, 2);
  assert.equal(
    slots[0]?.start.toISOString(),
    createDateAtTime(fromDateKey("2026-03-24"), "18:00").toISOString(),
  );
  assert.equal(
    slots[0]?.end.toISOString(),
    createDateAtTime(fromDateKey("2026-03-24"), "19:15").toISOString(),
  );
  assert.equal(
    slots[1]?.start.toISOString(),
    createDateAtTime(fromDateKey("2026-03-24"), "20:00").toISOString(),
  );
  assert.equal(
    slots[1]?.end.toISOString(),
    createDateAtTime(fromDateKey("2026-03-24"), "21:30").toISOString(),
  );
});

test("fixed events do not carve out an extra pre-event buffer from the free slots", () => {
  const dataset = buildSeedDataset(new Date("2026-03-16T08:00:00"));
  const preferences = {
    ...dataset.preferences,
    dailyStudyWindow: {
      start: "16:00",
      end: "19:00",
    },
    lockedRecoveryWindows: [],
    reservedCommitmentRules: [],
    bufferMinutesBeforeFixedEvent: 15,
  };

  const slots = calculateFreeSlots({
    weekStart: new Date("2026-03-16T00:00:00"),
    fixedEvents: [
      {
        id: "lesson",
        title: "Lesson",
        start: "2026-03-16T18:00:00+02:00",
        end: "2026-03-16T19:00:00+02:00",
        recurrence: "none",
        flexibility: "fixed",
        category: "activity",
      },
    ],
    preferences,
  });

  const mondaySlot = slots.find((slot) => slot.dateKey === "2026-03-16");
  assert.ok(mondaySlot);
  assert.equal(mondaySlot?.end.getHours(), 18);
  assert.equal(mondaySlot?.end.getMinutes(), 0);
});

test("the allocator does not force a gap when a busy boundary is immediately next", () => {
  assert.equal(getInlineBreakMinutes(90, 60, 15), 0);
  assert.equal(getInlineBreakMinutes(120, 60, 15), 15);
});

test("english is no longer auto-seeded for study and french is only light grammar/vocab maintenance", () => {
  const dataset = buildSeedDataset(new Date("2026-03-19T08:00:00"));
  const englishTopics = dataset.topics.filter((topic) => topic.subjectId === "english-a-sl");
  const frenchTopics = dataset.topics.filter((topic) => topic.subjectId === "french-b-sl");

  assert.equal(englishTopics.length, 0);
  assert.ok(frenchTopics.length > 0);
  assert.ok(
    frenchTopics.every(
      (topic) =>
        topic.title.toLowerCase().includes("grammar") ||
        topic.title.toLowerCase().includes("vocabulary"),
    ),
  );
  assert.ok(
    frenchTopics.every(
      (topic) =>
        topic.availableFrom !== null &&
        topic.availableFrom !== undefined,
    ),
  );
});
