import { format } from "date-fns";

import { subjectPrioritySeed } from "@/lib/constants/planner";
import { getAcademicDeadline } from "@/lib/dates/helpers";
import { seedTopicBlueprints } from "@/lib/seed/topic-catalog";
import type { Goal, Subject } from "@/lib/types/planner";

const FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX = "-06-30";

function sumSeedTopicHours(subjectId: Subject["id"], options?: { practiceOnly?: boolean }) {
  return seedTopicBlueprints
    .filter((topic) => topic.subjectId === subjectId)
    .filter((topic) =>
      options?.practiceOnly
        ? topic.unitId.includes("past-papers")
        : true,
    )
    .reduce((total, topic) => total + topic.estHours, 0);
}

function buildSyllabusTargetCompletion(subjectId: Subject["id"]) {
  const totalHours = sumSeedTopicHours(subjectId);
  const practiceHours = sumSeedTopicHours(subjectId, { practiceOnly: true });
  const syllabusHours = Math.max(totalHours - practiceHours, 0);

  return totalHours > 0 ? Number((syllabusHours / totalHours).toFixed(4)) : 1;
}

function getOlympiadTopicsUpTo(deadline: string) {
  return seedTopicBlueprints
    .filter((topic) => topic.subjectId === "olympiad")
    .filter((topic) => (topic.availableFrom ?? deadline) <= deadline)
    .map((topic) => topic.id);
}

export function buildSeedSubjects(referenceDate = new Date()): Subject[] {
  const deadline = format(getAcademicDeadline(referenceDate), "yyyy-MM-dd");
  const paperPracticeDeadline = `${referenceDate.getFullYear() + 1}${FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX}`;

  return [
    {
      id: "physics-hl",
      name: "Physics HL",
      shortName: "Physics HL",
      category: "physics",
      description: "Guide-backed Physics HL coverage across themes A-E, mapped to the Pearson 2023 text for first assessment 2025.",
      defaultPriority: subjectPrioritySeed["physics-hl"],
      weeklyMinimumHours: 7,
      examMode: "syllabus",
      colorToken: "subject-physics",
      gradientClassName: "from-subject-physics/25 via-subject-physics/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "maths-aa-hl",
      name: "Maths AA HL",
      shortName: "Maths AA HL",
      category: "maths",
      description: "Full Analysis and Approaches HL coverage across Topics 1-5 using the Hodder 2019 SL and HL sequence.",
      defaultPriority: subjectPrioritySeed["maths-aa-hl"],
      weeklyMinimumHours: 7,
      examMode: "syllabus",
      colorToken: "subject-maths",
      gradientClassName: "from-subject-maths/25 via-subject-maths/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "chemistry-hl",
      name: "Chemistry HL",
      shortName: "Chemistry HL",
      category: "chemistry",
      description: "Guide-backed Chemistry HL structure/reactivity coverage mapped to the Pearson 2023 text for first assessment 2025.",
      defaultPriority: subjectPrioritySeed["chemistry-hl"],
      weeklyMinimumHours: 6,
      examMode: "syllabus",
      colorToken: "subject-chemistry",
      gradientClassName: "from-subject-chemistry/25 via-subject-chemistry/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "olympiad",
      name: "Olympiad Prep",
      shortName: "Olympiad",
      category: "olympiad",
      description:
        "Track B+ Olympiad roadmap with continuous geometry, algebra/FE, NT/combi, proof conversion, and timed mock work through the next South African selection cycle.",
      defaultPriority: subjectPrioritySeed.olympiad,
      weeklyMinimumHours: 10,
      examMode: "olympiad",
      colorToken: "subject-olympiad",
      gradientClassName: "from-subject-olympiad/25 via-subject-olympiad/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "cpp-book",
      name: "Programming: Principles and Practice Using C++",
      shortName: "C++ Book",
      category: "programming",
      description:
        "Maintenance-mode C++ reading from Stroustrup's Programming: Principles and Practice Using C++ (3rd edition), reserved for slack and holiday capacity after the academic anchors.",
      defaultPriority: subjectPrioritySeed["cpp-book"],
      weeklyMinimumHours: 0,
      examMode: "syllabus",
      colorToken: "subject-programming",
      gradientClassName: "from-subject-programming/25 via-subject-programming/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "english-a-sl",
      name: "English A SL",
      shortName: "English A",
      category: "english",
      description: "Tracked for visibility only. No automatic English study blocks are generated by the planner.",
      defaultPriority: subjectPrioritySeed["english-a-sl"],
      weeklyMinimumHours: 0,
      examMode: "maintenance",
      colorToken: "subject-english",
      gradientClassName: "from-subject-english/25 via-subject-english/10 to-transparent",
      deadline,
    },
    {
      id: "french-b-sl",
      name: "French B SL",
      shortName: "French B",
      category: "french",
      description: "Light twice-weekly maintenance: small grammar and vocabulary tune-ups instead of full theme study.",
      defaultPriority: subjectPrioritySeed["french-b-sl"],
      weeklyMinimumHours: 1,
      examMode: "maintenance",
      colorToken: "subject-french",
      gradientClassName: "from-subject-french/25 via-subject-french/10 to-transparent",
      deadline,
    },
    {
      id: "geography-transition",
      name: "Geography HL/SL Transition",
      shortName: "Geography",
      category: "geography",
      description: "Tracked for visibility only. No automatic Geography study blocks are generated by the planner.",
      defaultPriority: subjectPrioritySeed["geography-transition"],
      weeklyMinimumHours: 0,
      examMode: "maintenance",
      colorToken: "subject-geography",
      gradientClassName: "from-subject-geography/25 via-subject-geography/10 to-transparent",
      deadline,
    },
  ];
}

export function buildSeedGoals(referenceDate = new Date()): Goal[] {
  const firstSchoolMilestoneDeadline = `${referenceDate.getFullYear()}-08-14`;
  const olympiadPhaseOneDeadline = `${referenceDate.getFullYear()}-07-31`;
  const olympiadPhaseTwoDeadline = `${referenceDate.getFullYear()}-09-30`;
  const olympiadCampDeadline = `${referenceDate.getFullYear()}-11-30`;
  const paperPracticeDeadline = `${referenceDate.getFullYear() + 1}${FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX}`;
  const physicsSyllabusTargetCompletion = buildSyllabusTargetCompletion("physics-hl");
  const mathsSyllabusTargetCompletion = buildSyllabusTargetCompletion("maths-aa-hl");
  const chemistrySyllabusTargetCompletion = buildSyllabusTargetCompletion("chemistry-hl");
  const olympiadPhaseOneTopicIds = getOlympiadTopicsUpTo(olympiadPhaseOneDeadline);
  const olympiadPhaseTwoTopicIds = getOlympiadTopicsUpTo(olympiadPhaseTwoDeadline);
  const olympiadCampTopicIds = getOlympiadTopicsUpTo(olympiadCampDeadline);
  const olympiadFinalTopicIds = getOlympiadTopicsUpTo(paperPracticeDeadline);

  return [
    {
      id: "goal-physics-hl",
      title: `Finish all Physics HL guide topics A.1-E.5 by ${firstSchoolMilestoneDeadline}`,
      subjectId: "physics-hl",
      deadline: firstSchoolMilestoneDeadline,
      targetCompletion: physicsSyllabusTargetCompletion,
      priorityWeight: 1,
    },
    {
      id: "goal-physics-hl-past-papers",
      title: `Complete the Physics HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "physics-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.85,
    },
    {
      id: "goal-maths-aa-hl",
      title: `Finish the full Maths AA HL syllabus, including HL extension, by ${firstSchoolMilestoneDeadline}`,
      subjectId: "maths-aa-hl",
      deadline: firstSchoolMilestoneDeadline,
      targetCompletion: mathsSyllabusTargetCompletion,
      priorityWeight: 1,
    },
    {
      id: "goal-maths-aa-hl-past-papers",
      title: `Complete the Maths AA HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "maths-aa-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.85,
    },
    {
      id: "goal-chemistry-hl",
      title: `Finish all Chemistry HL structure and reactivity topics by ${firstSchoolMilestoneDeadline}`,
      subjectId: "chemistry-hl",
      deadline: firstSchoolMilestoneDeadline,
      targetCompletion: chemistrySyllabusTargetCompletion,
      priorityWeight: 0.9,
    },
    {
      id: "goal-chemistry-hl-past-papers",
      title: `Complete the Chemistry HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "chemistry-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.8,
    },
    {
      id: "goal-olympiad-phase-1",
      title: `Finish Olympiad foundations, first-pass core strand work, and the early mock ladder by ${olympiadPhaseOneDeadline}`,
      subjectId: "olympiad",
      deadline: olympiadPhaseOneDeadline,
      targetCompletion: 1,
      priorityWeight: 1,
      topicIds: olympiadPhaseOneTopicIds,
    },
    {
      id: "goal-olympiad-phase-2",
      title: `Complete the Olympiad main coverage layer by ${olympiadPhaseTwoDeadline}`,
      subjectId: "olympiad",
      deadline: olympiadPhaseTwoDeadline,
      targetCompletion: 1,
      priorityWeight: 0.95,
      topicIds: olympiadPhaseTwoTopicIds,
    },
    {
      id: "goal-olympiad-phase-3",
      title: `Finish the Olympiad first pass before December camp by ${olympiadCampDeadline}`,
      subjectId: "olympiad",
      deadline: olympiadCampDeadline,
      targetCompletion: 1,
      priorityWeight: 0.95,
      topicIds: olympiadCampTopicIds,
    },
    {
      id: "goal-olympiad-phase-4",
      title: `Finish the full Olympiad Prep roadmap by ${paperPracticeDeadline}`,
      subjectId: "olympiad",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.9,
      topicIds: olympiadFinalTopicIds,
    },
    {
      id: "goal-cpp-book",
      title: `Keep steady maintenance progress through Programming: Principles and Practice Using C++ by ${paperPracticeDeadline}`,
      subjectId: "cpp-book",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.15,
    },
  ];
}
