import { format } from "date-fns";

import { getAcademicDeadline } from "@/lib/dates/helpers";
import { seedTopicBlueprints } from "@/lib/seed/topic-catalog";
import type { Goal, Subject } from "@/lib/types/planner";

const FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX = "-06-30";

function sumSeedTopicHours(subjectId: Subject["id"], options?: { practiceOnly?: boolean }) {
  return seedTopicBlueprints
    .filter((topic) => topic.subjectId === subjectId)
    .filter((topic) =>
      options?.practiceOnly
        ? topic.unitId.includes("past-papers")
        : true,
    )
    .reduce((total, topic) => total + topic.estHours, 0);
}

function buildSyllabusTargetCompletion(subjectId: Subject["id"]) {
  const totalHours = sumSeedTopicHours(subjectId);
  const practiceHours = sumSeedTopicHours(subjectId, { practiceOnly: true });
  const syllabusHours = Math.max(totalHours - practiceHours, 0);

  return totalHours > 0 ? Number((syllabusHours / totalHours).toFixed(4)) : 1;
}

export function buildSeedSubjects(referenceDate = new Date()): Subject[] {
  const deadline = format(getAcademicDeadline(referenceDate), "yyyy-MM-dd");
  const olympiadGoldDeadline = `${referenceDate.getFullYear() + 1}-06-30`;
  const paperPracticeDeadline = `${referenceDate.getFullYear() + 1}${FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX}`;

  return [
    {
      id: "physics-hl",
      name: "Physics HL",
      shortName: "Physics HL",
      category: "physics",
      description: "Guide-backed Physics HL coverage across themes A-E, mapped to the Pearson 2023 text for first assessment 2025.",
      defaultPriority: 1,
      weeklyMinimumHours: 7,
      examMode: "syllabus",
      colorToken: "subject-physics",
      gradientClassName: "from-subject-physics/25 via-subject-physics/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "maths-aa-hl",
      name: "Maths AA HL",
      shortName: "Maths AA HL",
      category: "maths",
      description: "Full Analysis and Approaches HL coverage across Topics 1-5 using the Hodder 2019 SL and HL sequence.",
      defaultPriority: 1,
      weeklyMinimumHours: 7,
      examMode: "syllabus",
      colorToken: "subject-maths",
      gradientClassName: "from-subject-maths/25 via-subject-maths/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "chemistry-hl",
      name: "Chemistry HL",
      shortName: "Chemistry HL",
      category: "chemistry",
      description: "Guide-backed Chemistry HL structure/reactivity coverage mapped to the Pearson 2023 text for first assessment 2025.",
      defaultPriority: 0.9,
      weeklyMinimumHours: 6,
      examMode: "syllabus",
      colorToken: "subject-chemistry",
      gradientClassName: "from-subject-chemistry/25 via-subject-chemistry/10 to-transparent",
      deadline: paperPracticeDeadline,
    },
    {
      id: "olympiad",
      name: "Olympiad Prep",
      shortName: "Olympiad",
      category: "olympiad",
      description:
        "Evidence-based April-camp-to-IMO-gold roadmap spanning algebra, number theory, combinatorics, geometry, inequalities, functional equations, and contest execution.",
      defaultPriority: 0.85,
      weeklyMinimumHours: 6,
      examMode: "olympiad",
      colorToken: "subject-olympiad",
      gradientClassName: "from-subject-olympiad/25 via-subject-olympiad/10 to-transparent",
      deadline: olympiadGoldDeadline,
    },
    {
      id: "cpp-book",
      name: "Programming: Principles and Practice Using C++",
      shortName: "C++ Book",
      category: "programming",
      description:
        "Chapter-by-chapter completion of Stroustrup's Programming: Principles and Practice Using C++ (3rd edition), with time for drills and coded examples.",
      defaultPriority: 0.45,
      weeklyMinimumHours: 2.5,
      examMode: "syllabus",
      colorToken: "subject-programming",
      gradientClassName: "from-subject-programming/25 via-subject-programming/10 to-transparent",
      deadline,
    },
    {
      id: "english-a-sl",
      name: "English A SL",
      shortName: "English A",
      category: "english",
      description: "Tracked for visibility only. No automatic English study blocks are generated by the planner.",
      defaultPriority: 0,
      weeklyMinimumHours: 0,
      examMode: "maintenance",
      colorToken: "subject-english",
      gradientClassName: "from-subject-english/25 via-subject-english/10 to-transparent",
      deadline,
    },
    {
      id: "french-b-sl",
      name: "French B SL",
      shortName: "French B",
      category: "french",
      description: "Occasional light maintenance only: small grammar and vocabulary tune-ups instead of full theme study.",
      defaultPriority: 0.15,
      weeklyMinimumHours: 0.5,
      examMode: "maintenance",
      colorToken: "subject-french",
      gradientClassName: "from-subject-french/25 via-subject-french/10 to-transparent",
      deadline,
    },
    {
      id: "geography-transition",
      name: "Geography HL/SL Transition",
      shortName: "Geography",
      category: "geography",
      description: "Light transition reading keyed to the 2019 geography core, optional themes, and HL extension.",
      defaultPriority: 0.4,
      weeklyMinimumHours: 1,
      examMode: "maintenance",
      colorToken: "subject-geography",
      gradientClassName: "from-subject-geography/25 via-subject-geography/10 to-transparent",
      deadline,
    },
  ];
}

export function buildSeedGoals(referenceDate = new Date()): Goal[] {
  const deadline = format(getAcademicDeadline(referenceDate), "yyyy-MM-dd");
  const olympiadReadyDeadline = `${referenceDate.getFullYear()}-06-30`;
  const olympiadGoldDeadline = `${referenceDate.getFullYear() + 1}-06-30`;
  const paperPracticeDeadline = `${referenceDate.getFullYear() + 1}${FINAL_PAPER_PRACTICE_DEADLINE_SUFFIX}`;
  const physicsSyllabusTargetCompletion = buildSyllabusTargetCompletion("physics-hl");
  const mathsSyllabusTargetCompletion = buildSyllabusTargetCompletion("maths-aa-hl");
  const chemistrySyllabusTargetCompletion = buildSyllabusTargetCompletion("chemistry-hl");

  return [
    {
      id: "goal-physics-hl",
      title: "Finish all Physics HL guide topics A.1-E.5 by July 31",
      subjectId: "physics-hl",
      deadline,
      targetCompletion: physicsSyllabusTargetCompletion,
      priorityWeight: 1,
    },
    {
      id: "goal-physics-hl-past-papers",
      title: `Complete the Physics HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "physics-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.85,
    },
    {
      id: "goal-maths-aa-hl",
      title: "Finish the full Maths AA HL syllabus, including HL extension, by July 31",
      subjectId: "maths-aa-hl",
      deadline,
      targetCompletion: mathsSyllabusTargetCompletion,
      priorityWeight: 1,
    },
    {
      id: "goal-maths-aa-hl-past-papers",
      title: `Complete the Maths AA HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "maths-aa-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.85,
    },
    {
      id: "goal-chemistry-hl",
      title: "Finish all Chemistry HL structure and reactivity topics by July 31",
      subjectId: "chemistry-hl",
      deadline,
      targetCompletion: chemistrySyllabusTargetCompletion,
      priorityWeight: 0.9,
    },
    {
      id: "goal-chemistry-hl-past-papers",
      title: `Complete the Chemistry HL post-syllabus past paper cycle by ${paperPracticeDeadline}`,
      subjectId: "chemistry-hl",
      deadline: paperPracticeDeadline,
      targetCompletion: 1,
      priorityWeight: 0.8,
    },
    {
      id: "goal-olympiad-imo-ready",
      title: `Reach the April-camp roadmap's pre-IMO coverage target by ${olympiadReadyDeadline}`,
      subjectId: "olympiad",
      deadline: olympiadReadyDeadline,
      targetCompletion: 0.65,
      priorityWeight: 0.95,
    },
    {
      id: "goal-olympiad-gold",
      title: `Reach the April-camp roadmap's IMO gold depth target by ${olympiadGoldDeadline}`,
      subjectId: "olympiad",
      deadline: olympiadGoldDeadline,
      targetCompletion: 1,
      priorityWeight: 0.9,
    },
    {
      id: "goal-cpp-book",
      title: "Finish Programming: Principles and Practice Using C++ (Ch. 0-21) by July 31",
      subjectId: "cpp-book",
      deadline,
      targetCompletion: 1,
      priorityWeight: 0.45,
    },
  ];
}
