import type { BlockType, SubjectId, TopicResource } from "@/lib/types/planner";

export interface SeedTopicBlueprint {
  id: string;
  subjectId: SubjectId;
  unitId: string;
  unitTitle: string;
  title: string;
  subtopics: string[];
  estHours: number;
  difficulty: 1 | 2 | 3 | 4 | 5;
  preferredBlockTypes: BlockType[];
  sourceMaterials: TopicResource[];
  notes?: string;
}

function resource(type: TopicResource["type"], label: string, details: string): TopicResource {
  return { type, label, details };
}

const guide = (label: string, details: string) => resource("notes", label, details);
const notes = (label: string, details: string) => resource("notes", label, details);
const textbook = (label: string, details: string) => resource("textbook", label, details);
const worksheet = (label: string, details: string) => resource("worksheet", label, details);
const pastPaper = (label: string, details: string) => resource("past_paper", label, details);
const video = (label: string, details: string) => resource("video", label, details);

export const legacySeedTopicIds = [
  "phys-measurements",
  "phys-mechanics",
  "phys-waves",
  "phys-thermal",
  "phys-circuits",
  "phys-fields",
  "phys-emi",
  "phys-atomic",
  "math-functions",
  "math-sequences",
  "math-complex",
  "math-vectors",
  "math-diff-applications",
  "math-integral-parts",
  "math-probability",
  "math-differential-equations",
  "chem-stoich",
  "chem-bonding",
  "chem-energetics",
  "chem-kinetics",
  "chem-equilibrium",
  "chem-acids",
  "chem-redox",
  "chem-organic",
  "oly-geometry",
  "oly-number-theory",
  "oly-combinatorics",
  "oly-inequalities",
  "oly-functional",
  "oly-mock-review",
  "eng-maintenance",
  "fr-maintenance",
  "geo-maintenance",
] as const;

export function hasLegacySeedTopics(topics: Array<{ id: string }>) {
  return topics.some((topic) =>
    legacySeedTopicIds.includes(topic.id as (typeof legacySeedTopicIds)[number]),
  );
}

const physicsTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "physics-a1-kinematics",
    subjectId: "physics-hl",
    unitId: "physics-theme-a",
    unitTitle: "Theme A - Space, time and motion",
    title: "A.1 Kinematics",
    subtopics: ["Displacement and velocity", "Acceleration models", "Motion graphs"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic A.1 checklist and guiding question."),
      textbook("Pearson Physics HL 2023", "A.1 Kinematics."),
    ],
  },
  {
    id: "physics-a2-forces-momentum",
    subjectId: "physics-hl",
    unitId: "physics-theme-a",
    unitTitle: "Theme A - Space, time and motion",
    title: "A.2 Forces and momentum",
    subtopics: ["Newton's laws", "Momentum and impulse", "Circular motion"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic A.2 plus HL expectations."),
      textbook("Pearson Physics HL 2023", "A.2 Forces and momentum."),
      pastPaper("IB-style mechanics set", "Target free-body, impulse, and circular motion questions."),
    ],
  },
  {
    id: "physics-a3-work-energy-power",
    subjectId: "physics-hl",
    unitId: "physics-theme-a",
    unitTitle: "Theme A - Space, time and motion",
    title: "A.3 Work, energy and power",
    subtopics: ["Work-energy theorem", "Power and efficiency", "Energy transfer models"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic A.3 understandings."),
      textbook("Pearson Physics HL 2023", "A.3 Work, energy and power."),
    ],
  },
  {
    id: "physics-a4-rigid-body-mechanics",
    subjectId: "physics-hl",
    unitId: "physics-theme-a",
    unitTitle: "Theme A - Space, time and motion",
    title: "A.4 Rigid body mechanics",
    subtopics: ["Torque", "Angular momentum", "Rotational equilibrium"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "HL-only topic A.4."),
      textbook("Pearson Physics HL 2023", "A.4 Rigid body mechanics."),
    ],
  },
  {
    id: "physics-a5-relativity",
    subjectId: "physics-hl",
    unitId: "physics-theme-a",
    unitTitle: "Theme A - Space, time and motion",
    title: "A.5 Galilean and special relativity",
    subtopics: ["Frames of reference", "Time dilation", "Length contraction"],
    estHours: 5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "HL-only topic A.5."),
      textbook("Pearson Physics HL 2023", "A.5 Galilean and special relativity."),
      video("Relativity concept pass", "Short visualization before doing derivations."),
    ],
  },
  {
    id: "physics-b1-thermal-transfers",
    subjectId: "physics-hl",
    unitId: "physics-theme-b",
    unitTitle: "Theme B - The particulate nature of matter",
    title: "B.1 Thermal energy transfers",
    subtopics: ["Specific heat capacity", "Latent heat", "Conduction, convection, radiation"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic B.1 core coverage."),
      textbook("Pearson Physics HL 2023", "B.1 Thermal energy transfers."),
    ],
  },
  {
    id: "physics-b2-greenhouse-effect",
    subjectId: "physics-hl",
    unitId: "physics-theme-b",
    unitTitle: "Theme B - The particulate nature of matter",
    title: "B.2 Greenhouse effect",
    subtopics: ["Radiative balance", "Absorption and re-emission", "Climate model reasoning"],
    estHours: 2.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic B.2 applications."),
      textbook("Pearson Physics HL 2023", "B.2 Greenhouse effect."),
    ],
  },
  {
    id: "physics-b3-gas-laws",
    subjectId: "physics-hl",
    unitId: "physics-theme-b",
    unitTitle: "Theme B - The particulate nature of matter",
    title: "B.3 Gas laws",
    subtopics: ["Ideal gas equation", "Kinetic model", "Pressure-volume-temperature relationships"],
    estHours: 3,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic B.3 checklist."),
      textbook("Pearson Physics HL 2023", "B.3 Gas laws."),
    ],
  },
  {
    id: "physics-b4-thermodynamics",
    subjectId: "physics-hl",
    unitId: "physics-theme-b",
    unitTitle: "Theme B - The particulate nature of matter",
    title: "B.4 Thermodynamics",
    subtopics: ["Internal energy", "First law", "Entropy and engines"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "HL-only topic B.4."),
      textbook("Pearson Physics HL 2023", "B.4 Thermodynamics."),
    ],
  },
  {
    id: "physics-b5-current-circuits",
    subjectId: "physics-hl",
    unitId: "physics-theme-b",
    unitTitle: "Theme B - The particulate nature of matter",
    title: "B.5 Current and circuits",
    subtopics: ["Charge and current", "Resistance and internal resistance", "Kirchhoff reasoning"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic B.5 core and HL-linked problem solving."),
      textbook("Pearson Physics HL 2023", "B.5 Current and circuits."),
      pastPaper("Circuit analysis pack", "Mixed Paper 1 and Paper 2 circuit questions."),
    ],
  },
  {
    id: "physics-c1-shm",
    subjectId: "physics-hl",
    unitId: "physics-theme-c",
    unitTitle: "Theme C - Wave behaviour",
    title: "C.1 Simple harmonic motion",
    subtopics: ["Oscillation variables", "Energy in SHM", "Pendulums and springs"],
    estHours: 3.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic C.1 plus HL treatment."),
      textbook("Pearson Physics HL 2023", "C.1 Simple harmonic motion."),
    ],
  },
  {
    id: "physics-c2-wave-model",
    subjectId: "physics-hl",
    unitId: "physics-theme-c",
    unitTitle: "Theme C - Wave behaviour",
    title: "C.2 Wave model",
    subtopics: ["Wavefronts", "Wave speed relationships", "Superposition basics"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic C.2 coverage."),
      textbook("Pearson Physics HL 2023", "C.2 Wave model."),
    ],
  },
  {
    id: "physics-c3-wave-phenomena",
    subjectId: "physics-hl",
    unitId: "physics-theme-c",
    unitTitle: "Theme C - Wave behaviour",
    title: "C.3 Wave phenomena",
    subtopics: ["Interference", "Diffraction", "Polarization"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic C.3 plus HL elements."),
      textbook("Pearson Physics HL 2023", "C.3 Wave phenomena."),
    ],
  },
  {
    id: "physics-c4-standing-waves",
    subjectId: "physics-hl",
    unitId: "physics-theme-c",
    unitTitle: "Theme C - Wave behaviour",
    title: "C.4 Standing waves and resonance",
    subtopics: ["Nodes and antinodes", "Harmonics", "Resonance conditions"],
    estHours: 3,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic C.4 core content."),
      textbook("Pearson Physics HL 2023", "C.4 Standing waves and resonance."),
    ],
  },
  {
    id: "physics-c5-doppler-effect",
    subjectId: "physics-hl",
    unitId: "physics-theme-c",
    unitTitle: "Theme C - Wave behaviour",
    title: "C.5 Doppler effect",
    subtopics: ["Source-observer motion", "Frequency shifts", "Applications"],
    estHours: 3,
    difficulty: 3,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic C.5 plus HL extension."),
      textbook("Pearson Physics HL 2023", "C.5 Doppler effect."),
    ],
  },
  {
    id: "physics-d1-gravitational-fields",
    subjectId: "physics-hl",
    unitId: "physics-theme-d",
    unitTitle: "Theme D - Fields",
    title: "D.1 Gravitational fields",
    subtopics: ["Field strength", "Potential", "Orbital motion"],
    estHours: 4,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic D.1 plus HL components."),
      textbook("Pearson Physics HL 2023", "D.1 Gravitational fields."),
    ],
  },
  {
    id: "physics-d2-electric-magnetic-fields",
    subjectId: "physics-hl",
    unitId: "physics-theme-d",
    unitTitle: "Theme D - Fields",
    title: "D.2 Electric and magnetic fields",
    subtopics: ["Electric field strength", "Magnetic flux density", "Field mapping"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic D.2 plus HL content."),
      textbook("Pearson Physics HL 2023", "D.2 Electric and magnetic fields."),
    ],
  },
  {
    id: "physics-d3-motion-em-fields",
    subjectId: "physics-hl",
    unitId: "physics-theme-d",
    unitTitle: "Theme D - Fields",
    title: "D.3 Motion in electromagnetic fields",
    subtopics: ["Charged particles", "Electric acceleration", "Magnetic circular motion"],
    estHours: 4,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic D.3 core content."),
      textbook("Pearson Physics HL 2023", "D.3 Motion in electromagnetic fields."),
    ],
  },
  {
    id: "physics-d4-induction",
    subjectId: "physics-hl",
    unitId: "physics-theme-d",
    unitTitle: "Theme D - Fields",
    title: "D.4 Induction",
    subtopics: ["Magnetic flux", "Faraday and Lenz laws", "Generators and transformers"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "HL-only topic D.4."),
      textbook("Pearson Physics HL 2023", "D.4 Induction."),
    ],
  },
  {
    id: "physics-e1-structure-atom",
    subjectId: "physics-hl",
    unitId: "physics-theme-e",
    unitTitle: "Theme E - Nuclear and quantum physics",
    title: "E.1 Structure of the atom",
    subtopics: ["Atomic models", "Spectra", "Nuclear notation"],
    estHours: 3.5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic E.1 plus HL elements."),
      textbook("Pearson Physics HL 2023", "E.1 Structure of the atom."),
    ],
  },
  {
    id: "physics-e2-quantum-physics",
    subjectId: "physics-hl",
    unitId: "physics-theme-e",
    unitTitle: "Theme E - Nuclear and quantum physics",
    title: "E.2 Quantum physics",
    subtopics: ["Photons", "Wave-particle duality", "Photoelectric effect"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Physics Guide 2025", "HL-only topic E.2."),
      textbook("Pearson Physics HL 2023", "E.2 Quantum physics."),
    ],
  },
  {
    id: "physics-e3-radioactive-decay",
    subjectId: "physics-hl",
    unitId: "physics-theme-e",
    unitTitle: "Theme E - Nuclear and quantum physics",
    title: "E.3 Radioactive decay",
    subtopics: ["Decay modes", "Half-life", "Activity and decay equations"],
    estHours: 3.5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic E.3 plus HL details."),
      textbook("Pearson Physics HL 2023", "E.3 Radioactive decay."),
    ],
  },
  {
    id: "physics-e4-fission",
    subjectId: "physics-hl",
    unitId: "physics-theme-e",
    unitTitle: "Theme E - Nuclear and quantum physics",
    title: "E.4 Fission",
    subtopics: ["Binding energy", "Chain reactions", "Reactor concepts"],
    estHours: 2.5,
    difficulty: 3,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic E.4 core coverage."),
      textbook("Pearson Physics HL 2023", "E.4 Fission."),
    ],
  },
  {
    id: "physics-e5-fusion-stars",
    subjectId: "physics-hl",
    unitId: "physics-theme-e",
    unitTitle: "Theme E - Nuclear and quantum physics",
    title: "E.5 Fusion and stars",
    subtopics: ["Fusion reactions", "Stellar energy", "Life cycle of stars"],
    estHours: 2.5,
    difficulty: 3,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Physics Guide 2025", "Topic E.5 core coverage."),
      textbook("Pearson Physics HL 2023", "E.5 Fusion and stars."),
    ],
  },
];

const mathsTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "maths-topic1-exponents-logs",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Exponents and logarithms",
    subtopics: ["Laws of exponents", "Scientific notation", "Logarithmic models"],
    estHours: 5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 1 foundations in number and algebra."),
      textbook("Hodder AA SL 2019", "Ch. 1 Core exponents and logarithms; Ch. 12 AA logarithms."),
    ],
  },
  {
    id: "maths-topic1-sequences-series",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Sequences and series",
    subtopics: ["Arithmetic sequences", "Geometric series", "Binomial links"],
    estHours: 6,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 1 sequence and series coverage."),
      textbook("Hodder AA SL 2019", "Ch. 2 Core sequences; Ch. 13 AA sequences and series."),
    ],
  },
  {
    id: "maths-topic1-counting-binomial",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Counting principles and binomial theorem",
    subtopics: ["Permutations and combinations", "Binomial coefficients", "Counting strategies"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "HL Topic 1 extension."),
      textbook("Hodder AA HL 2019", "Ch. 1 Counting principles."),
    ],
  },
  {
    id: "maths-topic1-algebra-partial-fractions",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Algebra, systems, and partial fractions",
    subtopics: ["Systems of equations", "Partial fractions", "Binomial extension"],
    estHours: 6,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 1 HL algebraic manipulation."),
      textbook("Hodder AA HL 2019", "Ch. 2 Algebra."),
    ],
  },
  {
    id: "maths-topic1-proof",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Mathematical proof",
    subtopics: ["Structure of proof", "Induction", "Contradiction and counterexample"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Proof expectations appear across Topics 1 to 5."),
      textbook("Hodder AA SL 2019", "Ch. 11 Proof."),
      textbook("Hodder AA HL 2019", "Ch. 5 Mathematical proof."),
    ],
  },
  {
    id: "maths-topic1-complex-numbers",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-1",
    unitTitle: "Topic 1 - Number and algebra",
    title: "Complex numbers",
    subtopics: ["Cartesian and polar form", "De Moivre's theorem", "Roots of complex numbers"],
    estHours: 7,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "HL Topic 1 complex-number extension."),
      textbook("Hodder AA HL 2019", "Ch. 4 Complex numbers."),
    ],
  },
  {
    id: "maths-topic2-functions-core",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-2",
    unitTitle: "Topic 2 - Functions",
    title: "Core functions and inverse reasoning",
    subtopics: ["Function concept", "Sketching graphs", "Composite and inverse functions"],
    estHours: 5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 2 function notation and behaviour."),
      textbook("Hodder AA SL 2019", "Ch. 3 Core functions; Ch. 14 AA functions."),
    ],
  },
  {
    id: "maths-topic2-graphs-models",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-2",
    unitTitle: "Topic 2 - Functions",
    title: "Graphs, transformations, and equation solving",
    subtopics: ["Transformations", "Rational and exponential models", "Analytical and graphical solutions"],
    estHours: 7,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 2 graphs and equations."),
      textbook("Hodder AA SL 2019", "Ch. 16 Graphs; Ch. 17 Equations."),
    ],
  },
  {
    id: "maths-topic2-polynomials",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-2",
    unitTitle: "Topic 2 - Functions",
    title: "Polynomials and rational functions",
    subtopics: ["Polynomial graphs", "Factor and remainder theorems", "Root relationships"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 2 HL polynomial behaviour."),
      textbook("Hodder AA HL 2019", "Ch. 6 Polynomials; Ch. 7 Functions."),
    ],
  },
  {
    id: "maths-topic3-coordinate-geometry",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-3",
    unitTitle: "Topic 3 - Geometry and trigonometry",
    title: "Coordinate geometry",
    subtopics: ["Lines in 2D", "Distance and midpoint", "3D coordinate geometry basics"],
    estHours: 5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 3 coordinate geometry."),
      textbook("Hodder AA SL 2019", "Ch. 4 Coordinate geometry."),
    ],
  },
  {
    id: "maths-topic3-trigonometry",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-3",
    unitTitle: "Topic 3 - Geometry and trigonometry",
    title: "Geometry and trigonometry",
    subtopics: ["Trigonometric functions", "Identities and equations", "Applications to geometry"],
    estHours: 6,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 3 trigonometry and geometry."),
      textbook("Hodder AA SL 2019", "Ch. 5 Core geometry and trigonometry; Ch. 18 AA trigonometry."),
      textbook("Hodder AA HL 2019", "Ch. 3 Trigonometry."),
    ],
  },
  {
    id: "maths-topic3-vectors",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-3",
    unitTitle: "Topic 3 - Geometry and trigonometry",
    title: "Vectors and 3D geometry",
    subtopics: ["Vector equations", "Lines and planes", "Angles and intersections"],
    estHours: 8,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 3 HL vector extension."),
      textbook("Hodder AA HL 2019", "Ch. 8 Vectors."),
    ],
  },
  {
    id: "maths-topic4-statistics",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-4",
    unitTitle: "Topic 4 - Statistics and probability",
    title: "Statistics and data representation",
    subtopics: ["Sampling", "Summary statistics", "Correlation and regression"],
    estHours: 5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 4 descriptive statistics."),
      textbook("Hodder AA SL 2019", "Ch. 6 Statistics; Ch. 19 AA statistics."),
    ],
  },
  {
    id: "maths-topic4-probability-distributions",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-4",
    unitTitle: "Topic 4 - Statistics and probability",
    title: "Probability techniques and distributions",
    subtopics: ["Conditional probability", "Discrete random variables", "Binomial and normal distributions"],
    estHours: 6,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 4 probability foundation."),
      textbook("Hodder AA SL 2019", "Ch. 7 Probability; Ch. 8 Probability distributions."),
    ],
  },
  {
    id: "maths-topic4-advanced-probability",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-4",
    unitTitle: "Topic 4 - Statistics and probability",
    title: "Advanced probability models",
    subtopics: ["Bayes' theorem", "Variance of random variables", "Continuous random variables"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 4 HL probability extension."),
      textbook("Hodder AA HL 2019", "Ch. 9 Probability."),
    ],
  },
  {
    id: "maths-topic5-differentiation-core",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Core differentiation",
    subtopics: ["Limits", "Derivative rules", "Tangents and normals"],
    estHours: 6,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 introductory calculus."),
      textbook("Hodder AA SL 2019", "Ch. 9 Core differentiation; Ch. 20 AA differentiation."),
    ],
  },
  {
    id: "maths-topic5-integration-core",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Core integration",
    subtopics: ["Anti-differentiation", "Definite integrals", "Area under curves"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 integrals and accumulation."),
      textbook("Hodder AA SL 2019", "Ch. 10 Core integration; Ch. 21 AA integration."),
    ],
  },
  {
    id: "maths-topic5-advanced-differentiation",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Advanced differentiation and applications",
    subtopics: ["L'Hopital's rule", "Implicit differentiation", "Optimization and related rates"],
    estHours: 9,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 HL calculus extension."),
      textbook("Hodder AA HL 2019", "Ch. 10A-10F Further calculus."),
    ],
  },
  {
    id: "maths-topic5-advanced-integration",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Advanced integration techniques",
    subtopics: ["Substitution", "Integration by parts", "Further geometric interpretation"],
    estHours: 8,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 HL integration methods."),
      textbook("Hodder AA HL 2019", "Ch. 10G-10I Further calculus."),
    ],
  },
  {
    id: "maths-topic5-differential-equations",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Differential equations",
    subtopics: ["Euler's method", "Separating variables", "Integrating factors"],
    estHours: 8,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 HL differential-equation modelling."),
      textbook("Hodder AA HL 2019", "Ch. 11A-11C Series and differential equations."),
    ],
  },
  {
    id: "maths-topic5-maclaurin-series",
    subjectId: "maths-aa-hl",
    unitId: "maths-topic-5",
    unitTitle: "Topic 5 - Calculus",
    title: "Maclaurin series",
    subtopics: ["Series expansion", "Approximation", "Series-based differential-equation methods"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("AA Guide 2021", "Topic 5 HL series expansion."),
      textbook("Hodder AA HL 2019", "Ch. 11D-11E Series and differential equations."),
    ],
  },
];

const chemistryTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "chem-structure-1-1-particulate",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-1",
    unitTitle: "Structure 1 - Models of the particulate nature of matter",
    title: "Structure 1.1 - Introduction to the particulate nature of matter",
    subtopics: ["States of matter", "Kinetic molecular theory", "Changes of state"],
    estHours: 3,
    difficulty: 2,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 1.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 1.1."),
    ],
  },
  {
    id: "chem-structure-1-2-nuclear-atom",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-1",
    unitTitle: "Structure 1 - Models of the particulate nature of matter",
    title: "Structure 1.2 - The nuclear atom",
    subtopics: ["Subatomic particles", "Isotopes", "Mass spectrometry"],
    estHours: 3.5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 1.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 1.2."),
    ],
  },
  {
    id: "chem-structure-1-3-electron-configurations",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-1",
    unitTitle: "Structure 1 - Models of the particulate nature of matter",
    title: "Structure 1.3 - Electron configurations",
    subtopics: ["Emission spectra", "Orbitals and shells", "Ionization-energy links"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 1.3."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 1.3."),
    ],
  },
  {
    id: "chem-structure-1-4-mole",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-1",
    unitTitle: "Structure 1 - Models of the particulate nature of matter",
    title: "Structure 1.4 - Counting particles by mass: The mole",
    subtopics: ["Amount of substance", "Empirical and molecular formulae", "Concentration"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 1.4."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 1.4."),
    ],
  },
  {
    id: "chem-structure-1-5-ideal-gases",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-1",
    unitTitle: "Structure 1 - Models of the particulate nature of matter",
    title: "Structure 1.5 - Ideal gases",
    subtopics: ["Ideal gas model", "Molar volume", "Ideal gas equation"],
    estHours: 3.5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 1.5."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 1.5."),
    ],
  },
  {
    id: "chem-reactivity-1-1-enthalpy",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-1",
    unitTitle: "Reactivity 1 - What drives chemical reactions?",
    title: "Reactivity 1.1 - Measuring enthalpy changes",
    subtopics: ["Calorimetry", "Standard enthalpy changes", "Combustion and neutralization"],
    estHours: 3.5,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 1.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 1.1."),
    ],
  },
  {
    id: "chem-reactivity-1-2-energy-cycles",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-1",
    unitTitle: "Reactivity 1 - What drives chemical reactions?",
    title: "Reactivity 1.2 - Energy cycles in reactions",
    subtopics: ["Hess's law", "Bond enthalpies", "Lattice and hydration cycles"],
    estHours: 4,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 1.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 1.2."),
    ],
  },
  {
    id: "chem-reactivity-1-3-fuels",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-1",
    unitTitle: "Reactivity 1 - What drives chemical reactions?",
    title: "Reactivity 1.3 - Energy from fuels",
    subtopics: ["Combustion", "Energy density", "Fuel cells and environmental tradeoffs"],
    estHours: 3,
    difficulty: 3,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 1.3."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 1.3."),
    ],
  },
  {
    id: "chem-reactivity-1-4-entropy",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-1",
    unitTitle: "Reactivity 1 - What drives chemical reactions?",
    title: "Reactivity 1.4 - Entropy and spontaneity",
    subtopics: ["Entropy change", "Gibbs energy", "Spontaneous processes"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "AHL Reactivity 1.4."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 1.4."),
    ],
  },
  {
    id: "chem-structure-2-1-ionic",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-2",
    unitTitle: "Structure 2 - Models of bonding and structure",
    title: "Structure 2.1 - The ionic model",
    subtopics: ["Ion formation", "Ionic bonding", "Lattice structures"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 2.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 2.1."),
    ],
  },
  {
    id: "chem-structure-2-2-covalent",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-2",
    unitTitle: "Structure 2 - Models of bonding and structure",
    title: "Structure 2.2 - The covalent model",
    subtopics: ["VSEPR", "Polarity and intermolecular forces", "Hybridization and resonance"],
    estHours: 6,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 2.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 2.2."),
    ],
  },
  {
    id: "chem-structure-2-3-metallic",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-2",
    unitTitle: "Structure 2 - Models of bonding and structure",
    title: "Structure 2.3 - The metallic model",
    subtopics: ["Metallic bonding", "Alloys", "Conductivity and structure-property links"],
    estHours: 3,
    difficulty: 3,
    preferredBlockTypes: ["review", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 2.3."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 2.3."),
    ],
  },
  {
    id: "chem-structure-2-4-materials",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-2",
    unitTitle: "Structure 2 - Models of bonding and structure",
    title: "Structure 2.4 - From models to materials",
    subtopics: ["Material properties", "Networks and solids", "Linking models to applications"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 2.4."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 2.4."),
    ],
  },
  {
    id: "chem-reactivity-2-1-amount-change",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-2",
    unitTitle: "Reactivity 2 - How much, how fast and how far?",
    title: "Reactivity 2.1 - How much? The amount of chemical change",
    subtopics: ["Stoichiometric calculations", "Limiting reagents", "Yield and atom economy"],
    estHours: 4,
    difficulty: 3,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 2.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 2.1."),
    ],
  },
  {
    id: "chem-reactivity-2-2-rate",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-2",
    unitTitle: "Reactivity 2 - How much, how fast and how far?",
    title: "Reactivity 2.2 - How fast? The rate of chemical change",
    subtopics: ["Collision theory", "Rate laws", "Catalysis and activation energy"],
    estHours: 4,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 2.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 2.2."),
    ],
  },
  {
    id: "chem-reactivity-2-3-extent",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-2",
    unitTitle: "Reactivity 2 - How much, how fast and how far?",
    title: "Reactivity 2.3 - How far? The extent of chemical change",
    subtopics: ["Equilibrium constants", "Le Chatelier's principle", "Buffer and equilibrium systems"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 2.3."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 2.3."),
    ],
  },
  {
    id: "chem-structure-3-1-periodic-table",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-3",
    unitTitle: "Structure 3 - Classification of matter",
    title: "Structure 3.1 - The periodic table: Classification of elements",
    subtopics: ["Periodic trends", "Ionization-energy patterns", "Classification of elements"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "review"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 3.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 3.1."),
    ],
  },
  {
    id: "chem-structure-3-2-functional-groups",
    subjectId: "chemistry-hl",
    unitId: "chem-structure-3",
    unitTitle: "Structure 3 - Classification of matter",
    title: "Structure 3.2 - Functional groups: Classification of organic compounds",
    subtopics: ["Nomenclature", "Homologous series", "Structural identification"],
    estHours: 5.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Structure 3.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Structure 3.2."),
    ],
  },
  {
    id: "chem-reactivity-3-1-proton-transfer",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-3",
    unitTitle: "Reactivity 3 - What are the mechanisms of chemical change?",
    title: "Reactivity 3.1 - Proton transfer reactions",
    subtopics: ["Bronsted-Lowry acids and bases", "pH and titrations", "Buffer systems"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 3.1."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 3.1."),
    ],
  },
  {
    id: "chem-reactivity-3-2-electron-transfer",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-3",
    unitTitle: "Reactivity 3 - What are the mechanisms of chemical change?",
    title: "Reactivity 3.2 - Electron transfer reactions",
    subtopics: ["Oxidation states", "Electrochemistry", "Electrolysis"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 3.2."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 3.2."),
    ],
  },
  {
    id: "chem-reactivity-3-3-electron-sharing",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-3",
    unitTitle: "Reactivity 3 - What are the mechanisms of chemical change?",
    title: "Reactivity 3.3 - Electron sharing reactions",
    subtopics: ["Addition reactions", "Substitution and elimination", "Organic synthesis pathways"],
    estHours: 4,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 3.3."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 3.3."),
    ],
  },
  {
    id: "chem-reactivity-3-4-electron-pair-sharing",
    subjectId: "chemistry-hl",
    unitId: "chem-reactivity-3",
    unitTitle: "Reactivity 3 - What are the mechanisms of chemical change?",
    title: "Reactivity 3.4 - Electron-pair sharing reactions",
    subtopics: ["Nucleophiles and electrophiles", "Reaction mechanisms", "Organic mechanism comparison"],
    estHours: 6.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      guide("Chemistry Guide 2025", "Reactivity 3.4."),
      textbook("Pearson Chemistry HL 2023", "Use the section aligned to Reactivity 3.4."),
    ],
  },
];

const olympiadTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "olympiad-number-theory-divisibility",
    subjectId: "olympiad",
    unitId: "olympiad-number-theory-1",
    unitTitle: "Olympiad - Number Theory I",
    title: "Arithmetic of integers and divisibility",
    subtopics: ["Primes", "gcd and lcm", "Euclidean algorithm", "Divisibility arguments"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Arithmetic of integers, divisibility, primes, gcd, lcm, and Euclidean algorithm."),
      worksheet("Number theory core set", "Foundational divisibility and gcd/lcm problems."),
    ],
  },
  {
    id: "olympiad-number-theory-congruence",
    subjectId: "olympiad",
    unitId: "olympiad-number-theory-1",
    unitTitle: "Olympiad - Number Theory I",
    title: "Congruences and modular theorems",
    subtopics: ["Fermat little theorem", "Chinese remainder theorem", "Wilson's theorem", "Euler's totient theorem"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Congruence, Fermat, CRT, Wilson, and Euler totient."),
      worksheet("Congruence pack", "Modular arithmetic proofs and residue practice."),
    ],
  },
  {
    id: "olympiad-number-theory-valuations",
    subjectId: "olympiad",
    unitId: "olympiad-number-theory-2",
    unitTitle: "Olympiad - Number Theory II",
    title: "Number theoretic functions and valuations",
    subtopics: ["Floor and ceiling functions", "p-adic valuation", "Divisibility bounds"],
    estHours: 4.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Ceiling and floor functions plus p-adic valuation."),
      worksheet("Valuation drills", "Floor identities and valuation problems."),
    ],
  },
  {
    id: "olympiad-number-theory-diophantine",
    subjectId: "olympiad",
    unitId: "olympiad-number-theory-2",
    unitTitle: "Olympiad - Number Theory II",
    title: "Diophantine equations",
    subtopics: ["Linear and quadratic Diophantine equations", "Pell's equation", "Descent arguments"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Diophantine equations including Pell's equation."),
      worksheet("Diophantine set", "Laddered equations and descent problems."),
    ],
  },
  {
    id: "olympiad-geometry-points-lines-polygons",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-1",
    unitTitle: "Olympiad - Geometry I",
    title: "Points, lines, polygons, and trigonometry",
    subtopics: ["Angle chase", "Polygon structure", "Trigonometric identities in geometry"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Points, lines and polygons; trigonometry."),
      worksheet("Geometry core set", "Angle chase and trig-based geometry problems."),
    ],
  },
  {
    id: "olympiad-geometry-triangle-centers",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-1",
    unitTitle: "Olympiad - Geometry I",
    title: "Triangle centers, Ceva, and Menelaus",
    subtopics: ["Circumcentre, incentre, orthocentre, centroid", "Ceva's theorem", "Menelaus' theorem"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Triangle centers with Ceva and Menelaus."),
      worksheet("Triangle-center proofs", "Synthetic geometry proofs around Ceva and Menelaus."),
    ],
  },
  {
    id: "olympiad-geometry-quadrilaterals-circles",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-2",
    unitTitle: "Olympiad - Geometry II",
    title: "Quadrilaterals and circle geometry",
    subtopics: ["Cyclic quadrilaterals", "Power of a point", "Tangency and radical axis"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Quadrilaterals and circle geometry."),
      worksheet("Circle geometry shortlist", "Proof-heavy cyclic and tangent problems."),
    ],
  },
  {
    id: "olympiad-geometry-advanced-theorems",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-2",
    unitTitle: "Olympiad - Geometry II",
    title: "Advanced Euclidean geometry theorems",
    subtopics: ["Nine-point circle", "Stewart's theorem", "Ptolemy's theorem", "Simpson's line", "Euler's line"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Nine-point circle, Stewart, Ptolemy, Simpson, and Euler line."),
      worksheet("Advanced Euclidean set", "Named-theorem geometry proofs."),
    ],
  },
  {
    id: "olympiad-geometry-coordinate-complex",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-3",
    unitTitle: "Olympiad - Geometry III",
    title: "Coordinate and complex geometry",
    subtopics: ["Coordinate bashing", "Vectors on the plane", "Complex-plane geometry"],
    estHours: 5.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Coordinate geometry and complex geometry."),
      worksheet("Coordinate and complex pack", "Analytic and complex-plane geometry drills."),
    ],
  },
  {
    id: "olympiad-geometry-barycentric-inversion-projective",
    subjectId: "olympiad",
    unitId: "olympiad-geometry-3",
    unitTitle: "Olympiad - Geometry III",
    title: "Barycentric, inversion, and projective geometry",
    subtopics: ["Barycentric coordinates", "Inversion", "Projective transformations"],
    estHours: 7,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Barycentric, inversion, and projective geometry."),
      worksheet("Advanced geometry extensions", "Specialized geometry method problems."),
    ],
  },
  {
    id: "olympiad-algebra-sequences-series",
    subjectId: "olympiad",
    unitId: "olympiad-algebra-1",
    unitTitle: "Olympiad - Algebra I",
    title: "Sequences and series",
    subtopics: ["A.P.", "G.P.", "Harmonic sequences", "Fibonacci sequence"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Sequences and series including Fibonacci."),
      worksheet("Sequence methods", "Pattern-finding and recurrence problems."),
    ],
  },
  {
    id: "olympiad-algebra-functional-equations",
    subjectId: "olympiad",
    unitId: "olympiad-algebra-1",
    unitTitle: "Olympiad - Algebra I",
    title: "Functional equations",
    subtopics: ["Substitution strategies", "Injective and surjective cases", "Iterative arguments"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Functional equations."),
      worksheet("Functional equation set", "Laddered olympiad FE problems."),
    ],
  },
  {
    id: "olympiad-algebra-polynomials",
    subjectId: "olympiad",
    unitId: "olympiad-algebra-2",
    unitTitle: "Olympiad - Algebra II",
    title: "Polynomials and algebraic structure",
    subtopics: ["Systems of equations", "Vieta's formulas", "Factorization methods"],
    estHours: 5.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Polynomials, systems, Vieta, and factorization."),
      worksheet("Polynomial toolkit", "Roots, symmetric sums, and factorization problems."),
    ],
  },
  {
    id: "olympiad-algebra-inequalities-foundations",
    subjectId: "olympiad",
    unitId: "olympiad-algebra-2",
    unitTitle: "Olympiad - Algebra II",
    title: "Inequalities foundations",
    subtopics: ["AM-GM", "Cauchy-Schwarz", "Chebyshev", "Basic trigonometric inequalities"],
    estHours: 5.5,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "AM-GM, Cauchy-Schwarz, Chebyshev, and trig inequalities."),
      worksheet("Inequality basics", "Foundational inequality proofs and transformations."),
    ],
  },
  {
    id: "olympiad-algebra-inequalities-advanced",
    subjectId: "olympiad",
    unitId: "olympiad-algebra-3",
    unitTitle: "Olympiad - Algebra III",
    title: "Advanced inequalities",
    subtopics: ["Holder", "Minkowski", "Jensen", "Schur", "Muirhead"],
    estHours: 7,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Holder, Minkowski, Jensen, Schur, and Muirhead."),
      worksheet("Advanced inequalities shortlist", "Hard olympiad inequality problems."),
    ],
  },
  {
    id: "olympiad-combinatorics-counting-induction",
    subjectId: "olympiad",
    unitId: "olympiad-combinatorics-1",
    unitTitle: "Olympiad - Combinatorics I",
    title: "Counting methods and induction",
    subtopics: ["Permutations and combinations", "Double counting", "Principle of mathematical induction"],
    estHours: 5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Principle of counting and PMI."),
      worksheet("Counting core set", "Permutation, combination, and induction problems."),
    ],
  },
  {
    id: "olympiad-combinatorics-pie-pigeonhole-invariants",
    subjectId: "olympiad",
    unitId: "olympiad-combinatorics-1",
    unitTitle: "Olympiad - Combinatorics I",
    title: "Inclusion-exclusion, pigeonhole, and invariants",
    subtopics: ["Derangements", "Inclusion-exclusion principle", "Pigeonhole principle", "Invariant principle"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Inclusion-exclusion, derangement, pigeonhole, and invariants."),
      worksheet("Combinatorics proof set", "Hard counting and invariant problems."),
    ],
  },
  {
    id: "olympiad-combinatorics-graph-theory",
    subjectId: "olympiad",
    unitId: "olympiad-combinatorics-2",
    unitTitle: "Olympiad - Combinatorics II",
    title: "Graph theory",
    subtopics: ["Graph basics", "Extremal arguments", "Coloring and connectivity"],
    estHours: 4.5,
    difficulty: 4,
    preferredBlockTypes: ["standard_focus", "drill"],
    sourceMaterials: [
      notes("Olympiad syllabus", "Graph theory."),
      worksheet("Graph theory set", "Extremal, coloring, and path problems."),
    ],
  },
  {
    id: "olympiad-contest-synthesis",
    subjectId: "olympiad",
    unitId: "olympiad-contest",
    unitTitle: "Olympiad - Contest Practice",
    title: "Mock papers, error logs, and synthesis",
    subtopics: ["Timed sets", "Error log review", "Cross-topic synthesis"],
    estHours: 6,
    difficulty: 5,
    preferredBlockTypes: ["deep_work", "standard_focus"],
    sourceMaterials: [
      pastPaper("Mock Olympiad set", "Timed mixed-topic olympiad papers."),
      notes("Olympiad error log", "Consolidate misses and retries from mock work."),
    ],
  },
];

const englishTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "english-area-readers-writers-texts",
    subjectId: "english-a-sl",
    unitId: "english-area-1",
    unitTitle: "Area 1 - Readers, writers and texts",
    title: "Readers, writers and texts",
    subtopics: ["Authorial choices", "Close reading", "Commentary practice"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [
      guide("Language A Guide 2021", "Area of exploration 1."),
      notes("Class annotations", "Maintain annotation and commentary fluency."),
    ],
  },
  {
    id: "english-area-time-space",
    subjectId: "english-a-sl",
    unitId: "english-area-2",
    unitTitle: "Area 2 - Time and space",
    title: "Time and space",
    subtopics: ["Context", "Cultural perspective", "Text and society"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [
      guide("Language A Guide 2021", "Area of exploration 2."),
      notes("Text-context notebook", "Short context refresh and paragraph writing."),
    ],
  },
  {
    id: "english-area-intertextuality",
    subjectId: "english-a-sl",
    unitId: "english-area-3",
    unitTitle: "Area 3 - Intertextuality",
    title: "Intertextuality: connecting texts",
    subtopics: ["Comparison", "Themes across texts", "Oral comparison planning"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [
      guide("Language A Guide 2021", "Area of exploration 3."),
      notes("Comparison bank", "Keep a live list of linkable extracts and themes."),
    ],
  },
];

const frenchTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "french-theme-identities",
    subjectId: "french-b-sl",
    unitId: "french-theme-1",
    unitTitle: "Prescribed theme - Identities",
    title: "Identities",
    subtopics: ["Personal identity", "Lifestyle", "Values and beliefs"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Language B Guide 2020", "Prescribed theme: identities.")],
  },
  {
    id: "french-theme-experiences",
    subjectId: "french-b-sl",
    unitId: "french-theme-2",
    unitTitle: "Prescribed theme - Experiences",
    title: "Experiences",
    subtopics: ["Daily routine", "Leisure", "Life events"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Language B Guide 2020", "Prescribed theme: experiences.")],
  },
  {
    id: "french-theme-human-ingenuity",
    subjectId: "french-b-sl",
    unitId: "french-theme-3",
    unitTitle: "Prescribed theme - Human ingenuity",
    title: "Human ingenuity",
    subtopics: ["Technology", "Communication", "Innovation vocabulary"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Language B Guide 2020", "Prescribed theme: human ingenuity.")],
  },
  {
    id: "french-theme-social-organization",
    subjectId: "french-b-sl",
    unitId: "french-theme-4",
    unitTitle: "Prescribed theme - Social organization",
    title: "Social organization",
    subtopics: ["Community", "Education", "Work and society"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Language B Guide 2020", "Prescribed theme: social organization.")],
  },
  {
    id: "french-theme-sharing-planet",
    subjectId: "french-b-sl",
    unitId: "french-theme-5",
    unitTitle: "Prescribed theme - Sharing the planet",
    title: "Sharing the planet",
    subtopics: ["Environment", "Global issues", "Sustainable futures"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Language B Guide 2020", "Prescribed theme: sharing the planet.")],
  },
];

const geographyTopicBlueprints: SeedTopicBlueprint[] = [
  {
    id: "geography-transition-core-global-change",
    subjectId: "geography-transition",
    unitId: "geography-core",
    unitTitle: "Transition - SL/HL core",
    title: "Global change core familiarization",
    subtopics: ["Population change", "Resource consumption", "Global risks and resilience"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Geography Guide 2019", "Core theme: global change.")],
  },
  {
    id: "geography-transition-optional-themes",
    subjectId: "geography-transition",
    unitId: "geography-options",
    unitTitle: "Transition - Optional themes",
    title: "Optional theme orientation",
    subtopics: ["Theme overview", "Case-study notebook", "Terminology refresh"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Geography Guide 2019", "Optional themes for SL/HL geography.")],
  },
  {
    id: "geography-transition-hl-extension",
    subjectId: "geography-transition",
    unitId: "geography-hl-extension",
    unitTitle: "Transition - HL extension",
    title: "Global interactions extension",
    subtopics: ["Power and networks", "Cultural integration", "Global development links"],
    estHours: 1.5,
    difficulty: 2,
    preferredBlockTypes: ["review", "recovery"],
    sourceMaterials: [guide("Geography Guide 2019", "HL extension: global interactions.")],
  },
];

export const seedTopicBlueprints: SeedTopicBlueprint[] = [
  ...physicsTopicBlueprints,
  ...mathsTopicBlueprints,
  ...chemistryTopicBlueprints,
  ...olympiadTopicBlueprints,
  ...englishTopicBlueprints,
  ...frenchTopicBlueprints,
  ...geographyTopicBlueprints,
];
