"use client";

import { useMemo, useState } from "react";
import { format } from "date-fns";
import { CalendarClock, X } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { createDateAtTime, fromDateKey, minutesBetween, startOfPlannerWeek, toDateKey } from "@/lib/dates/helpers";
import { getAssignableTaskCandidatesForBlock } from "@/lib/scheduler/task-candidates";
import type { StudyBlock, Subject, Topic } from "@/lib/types/planner";

export type StudyBlockEditorDraft =
  | {
      mode: "create";
      start: string;
      end: string;
    }
  | {
      mode: "edit";
      block: StudyBlock;
    }
  | null;

interface StudyBlockEditorDialogProps {
  open: boolean;
  draft: StudyBlockEditorDraft;
  subjects: Subject[];
  topics: Topic[];
  studyBlocks: StudyBlock[];
  onClose: () => void;
  onSave: (options: {
    blockId?: string;
    start: string;
    end: string;
    topicId: string;
    notes?: string;
  }) => Promise<void>;
}

function buildEmptyScoreBreakdown(): StudyBlock["scoreBreakdown"] {
  return {
    priorityWeight: 0,
    deadlineUrgency: 0,
    remainingWorkloadPressure: 0,
    lowMasteryBonus: 0,
    reviewDueBonus: 0,
    neglectedSubjectBonus: 0,
    olympiadSlotBonus: 0,
    focusDayBonus: 0,
    badSlotFitPenalty: 0,
    fragmentationPenalty: 0,
    total: 0,
  };
}

function toTimeInputValue(value: string) {
  return format(new Date(value), "HH:mm");
}

function buildDraftStudyBlock(options: {
  draft: Exclude<StudyBlockEditorDraft, null>;
  start: Date;
  end: Date;
  notes: string;
}): StudyBlock {
  const { draft, start, end, notes } = options;
  const durationMinutes = minutesBetween(start, end);
  const existingBlock = draft.mode === "edit" ? draft.block : null;

  return {
    id: existingBlock?.id ?? "manual-study-draft",
    weekStart: toDateKey(startOfPlannerWeek(start)),
    date: toDateKey(start),
    start: start.toISOString(),
    end: end.toISOString(),
    subjectId: existingBlock?.subjectId ?? null,
    topicId: existingBlock?.topicId ?? null,
    title: existingBlock?.title ?? "Manual study block",
    sessionSummary: existingBlock?.sessionSummary ?? null,
    paperCode: existingBlock?.paperCode ?? null,
    unitTitle: existingBlock?.unitTitle ?? null,
    blockType: existingBlock?.blockType ?? "standard_focus",
    intensity: existingBlock?.intensity ?? "moderate",
    generatedReason: existingBlock?.generatedReason ?? "",
    scoreBreakdown: existingBlock?.scoreBreakdown ?? buildEmptyScoreBreakdown(),
    status: existingBlock?.status ?? "planned",
    isAutoGenerated: true,
    creationSource: "manual",
    sourceMaterials: existingBlock?.sourceMaterials ?? [],
    slotEnergy: existingBlock?.slotEnergy ?? "steady",
    estimatedMinutes: durationMinutes,
    actualMinutes: existingBlock?.actualMinutes ?? null,
    notes,
    rescheduleCount: existingBlock?.rescheduleCount ?? 0,
    assignmentLocked: false,
    assignmentEditedAt: existingBlock?.assignmentEditedAt ?? null,
  };
}

export function StudyBlockEditorDialog({
  open,
  draft,
  subjects,
  topics,
  studyBlocks,
  onClose,
  onSave,
}: StudyBlockEditorDialogProps) {
  if (!open || !draft) {
    return null;
  }

  return (
    <StudyBlockEditorDialogPanel
      draft={draft}
      subjects={subjects}
      topics={topics}
      studyBlocks={studyBlocks}
      onClose={onClose}
      onSave={onSave}
    />
  );
}

function StudyBlockEditorDialogPanel({
  draft,
  subjects,
  topics,
  studyBlocks,
  onClose,
  onSave,
}: Omit<StudyBlockEditorDialogProps, "open"> & {
  draft: Exclude<StudyBlockEditorDraft, null>;
}) {
  const initialStart = draft.mode === "create" ? new Date(draft.start) : new Date(draft.block.start);
  const initialEnd = draft.mode === "create" ? new Date(draft.end) : new Date(draft.block.end);
  const [dateKey, setDateKey] = useState(toDateKey(initialStart));
  const [startTime, setStartTime] = useState(toTimeInputValue(initialStart.toISOString()));
  const [endTime, setEndTime] = useState(toTimeInputValue(initialEnd.toISOString()));
  const [notes, setNotes] = useState(draft.mode === "edit" ? draft.block.notes : "");
  const [formError, setFormError] = useState<string | null>(null);
  const [editorOpenedAt] = useState(() => Date.now());
  const initialTopicId = draft.mode === "edit" ? draft.block.topicId ?? "" : "";
  const initialSubjectId = draft.mode === "edit" ? draft.block.subjectId ?? "" : "";
  const initialUnitId =
    draft.mode === "edit"
      ? topics.find((topic) => topic.id === draft.block.topicId)?.unitId ?? ""
      : "";
  const [draftSelection, setDraftSelection] = useState<{
    subjectId: string;
    unitId: string;
    topicId: string;
  }>({
    subjectId: initialSubjectId,
    unitId: initialUnitId,
    topicId: initialTopicId,
  });

  const range = useMemo(() => {
    if (!dateKey || !startTime || !endTime) {
      return null;
    }

    const day = fromDateKey(dateKey);
    const start = createDateAtTime(day, startTime);
    const end = createDateAtTime(day, endTime);

    if (end <= start) {
      return null;
    }

    return { start, end };
  }, [dateKey, startTime, endTime]);

  const assignableTopicEntries = useMemo(() => {
    if (!range) {
      return [];
    }

    const draftBlock = buildDraftStudyBlock({
      draft,
      start: range.start,
      end: range.end,
      notes,
    });

    if (draftBlock.estimatedMinutes < 30) {
      return [];
    }

    const subjectDeadlinesById = Object.fromEntries(
      subjects.map((subject) => [subject.id, subject.deadline]),
    );

    return getAssignableTaskCandidatesForBlock({
      block: draftBlock,
      topics,
      existingPlannedBlocks: studyBlocks.filter((candidate) => candidate.id !== draftBlock.id),
      subjectDeadlinesById,
    })
      .map((candidate) => {
        const candidateTopic = topics.find((topic) => topic.id === candidate.topicId);

        if (!candidateTopic) {
          return null;
        }

        return {
          candidate,
          topic: candidateTopic,
        };
      })
      .filter((entry): entry is NonNullable<typeof entry> => !!entry)
      .sort((left, right) => {
        if (left.topic.subjectId !== right.topic.subjectId) {
          return left.topic.subjectId.localeCompare(right.topic.subjectId);
        }

        if (left.topic.unitTitle !== right.topic.unitTitle) {
          return left.topic.unitTitle.localeCompare(right.topic.unitTitle);
        }

        return left.topic.order - right.topic.order;
      });
  }, [draft, notes, range, studyBlocks, subjects, topics]);

  const availableSubjects = useMemo(() => {
    const seen = new Set<string>();
    return assignableTopicEntries
      .map((entry) => entry.topic.subjectId)
      .filter((subjectId) => {
        if (seen.has(subjectId)) {
          return false;
        }

        seen.add(subjectId);
        return true;
      })
      .map((subjectId) => subjects.find((subject) => subject.id === subjectId))
      .filter((subject): subject is Subject => !!subject);
  }, [assignableTopicEntries, subjects]);

  const selectedSubjectId = availableSubjects.some((subject) => subject.id === draftSelection.subjectId)
    ? draftSelection.subjectId
    : availableSubjects[0]?.id ?? "";

  const availableUnits = useMemo(() => {
    const seen = new Set<string>();
    return assignableTopicEntries
      .filter((entry) => entry.topic.subjectId === selectedSubjectId)
      .filter((entry) => {
        if (seen.has(entry.topic.unitId)) {
          return false;
        }

        seen.add(entry.topic.unitId);
        return true;
      })
      .map((entry) => ({
        id: entry.topic.unitId,
        label: entry.topic.unitTitle,
      }));
  }, [assignableTopicEntries, selectedSubjectId]);

  const selectedUnitId = availableUnits.some((unit) => unit.id === draftSelection.unitId)
    ? draftSelection.unitId
    : availableUnits[0]?.id ?? "";

  const availableTopics = useMemo(
    () =>
      assignableTopicEntries
        .filter((entry) => entry.topic.subjectId === selectedSubjectId)
        .filter((entry) => entry.topic.unitId === selectedUnitId),
    [assignableTopicEntries, selectedSubjectId, selectedUnitId],
  );

  const selectedTopicId = availableTopics.some((entry) => entry.topic.id === draftSelection.topicId)
    ? draftSelection.topicId
    : availableTopics[0]?.topic.id ?? "";

  const selectedCandidate = availableTopics.find((entry) => entry.topic.id === selectedTopicId) ?? null;
  const isFutureRange = !!range && range.end.getTime() > editorOpenedAt;
  const canSave =
    !!range &&
    range.start.toDateString() === range.end.toDateString() &&
    minutesBetween(range.start, range.end) >= 30 &&
    !!selectedTopicId &&
    isFutureRange;

  const handleSave = async () => {
    if (!range || !selectedTopicId) {
      return;
    }

    setFormError(null);

    try {
      await onSave({
        blockId: draft.mode === "edit" ? draft.block.id : undefined,
        start: range.start.toISOString(),
        end: range.end.toISOString(),
        topicId: selectedTopicId,
        notes: notes.trim() || undefined,
      });
    } catch (error) {
      setFormError(error instanceof Error ? error.message : "Failed to save the study block.");
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/55 p-4 backdrop-blur-sm">
      <div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto overscroll-contain">
        <Card data-testid="study-block-editor-dialog">
          <CardHeader className="flex-row items-start justify-between">
            <div>
              <CardTitle>{draft.mode === "edit" ? "Edit study block" : "Add study block"}</CardTitle>
              <p className="mt-1 text-sm text-muted-foreground">
                This is a real study block, not a fixed event. It counts toward topic coverage immediately, and the future horizon rebuilds around it.
              </p>
            </div>
            <Button variant="ghost" size="sm" className="h-10 w-10 rounded-full p-0" onClick={onClose}>
              <X className="h-4 w-4" />
            </Button>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Date</label>
                <Input
                  data-testid="study-block-editor-date"
                  type="date"
                  value={dateKey}
                  onChange={(event) => {
                    setFormError(null);
                    setDateKey(event.target.value);
                  }}
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Start</label>
                <Input
                  data-testid="study-block-editor-start"
                  type="time"
                  value={startTime}
                  onChange={(event) => {
                    setFormError(null);
                    setStartTime(event.target.value);
                  }}
                />
              </div>
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">End</label>
                <Input
                  data-testid="study-block-editor-end"
                  type="time"
                  value={endTime}
                  onChange={(event) => {
                    setFormError(null);
                    setEndTime(event.target.value);
                  }}
                />
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-3">
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Subject</label>
                <Select
                  data-testid="study-block-editor-subject"
                  value={selectedSubjectId}
                  onChange={(event) => {
                    setFormError(null);
                    setDraftSelection({
                      subjectId: event.target.value,
                      unitId: "",
                      topicId: "",
                    });
                  }}
                >
                  {availableSubjects.map((subject) => (
                    <option key={subject.id} value={subject.id}>
                      {subject.shortName}
                    </option>
                  ))}
                </Select>
              </div>
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Section</label>
                <Select
                  data-testid="study-block-editor-unit"
                  value={selectedUnitId}
                  onChange={(event) => {
                    setFormError(null);
                    setDraftSelection((current) => ({
                      ...current,
                      unitId: event.target.value,
                      topicId: "",
                    }));
                  }}
                >
                  {availableUnits.map((unit) => (
                    <option key={unit.id} value={unit.id}>
                      {unit.label}
                    </option>
                  ))}
                </Select>
              </div>
              <div className="space-y-2">
                <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Topic</label>
                <Select
                  data-testid="study-block-editor-topic"
                  value={selectedTopicId}
                  onChange={(event) => {
                    setFormError(null);
                    setDraftSelection((current) => ({
                      ...current,
                      topicId: event.target.value,
                    }));
                  }}
                >
                  {availableTopics.map((entry) => (
                    <option key={entry.topic.id} value={entry.topic.id}>
                      {entry.topic.title}
                    </option>
                  ))}
                </Select>
              </div>
            </div>

            {selectedCandidate ? (
              <div className="rounded-sm border border-white/8 bg-white/4 px-4 py-3">
                <p className="text-sm font-medium text-foreground">{selectedCandidate.topic.unitTitle}</p>
                {selectedCandidate.candidate.sessionSummary ? (
                  <p className="mt-1 text-sm text-muted-foreground">{selectedCandidate.candidate.sessionSummary}</p>
                ) : null}
              </div>
            ) : (
              <div className="rounded-sm border border-white/8 bg-white/4 px-4 py-3 text-sm text-muted-foreground">
                No valid topics fit this exact time and duration yet. Dependency gates, Olympiad frontiers, and exact-duration paper sessions are all enforced here too.
              </div>
            )}

            <div className="space-y-2">
              <label className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Optional notes</label>
              <Textarea
                data-testid="study-block-editor-notes"
                value={notes}
                onChange={(event) => {
                  setFormError(null);
                  setNotes(event.target.value);
                }}
                placeholder="Anything you want attached to this block."
              />
            </div>

            <div className="rounded-sm border border-primary/20 bg-primary/8 px-4 py-3">
              <div className="flex items-start gap-3">
                <CalendarClock className="mt-0.5 h-4 w-4 text-primary" />
                <p className="text-sm text-foreground">
                  Saving keeps this block at the chosen time for the immediate rebuild, but later full regenerations can still move or retarget it like any normal planned study block.
                </p>
              </div>
            </div>

            {!isFutureRange ? (
              <p className="text-sm text-danger">
                Study-block scheduling edits are limited to future time slots.
              </p>
            ) : null}

            {range && minutesBetween(range.start, range.end) < 30 ? (
              <p className="text-sm text-danger">
                Study blocks must be at least 30 minutes long.
              </p>
            ) : null}

            {formError ? <p className="text-sm text-danger">{formError}</p> : null}

            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={onClose}>
                Cancel
              </Button>
              <Button
                data-testid="study-block-editor-save"
                disabled={!canSave}
                onClick={() => void handleSave()}
              >
                {draft.mode === "edit" ? "Save changes" : "Add study block"}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
