import { addDays, addMinutes, isAfter } from "date-fns";

import { subjectIds } from "@/lib/constants/planner";
import {
  buildUnconfiguredWeeklyPlan,
  buildWeeklyPlan,
  computeSubjectDeadlineTracks,
} from "@/lib/scheduler/feasibility";
import { calculateFreeSlots } from "@/lib/scheduler/free-slots";
import { scoreTaskCandidate, buildGeneratedReason } from "@/lib/scheduler/scoring";
import type { BlockSelectionPolicy } from "@/lib/scheduler/slot-classifier";
import { selectBlockOption } from "@/lib/scheduler/slot-classifier";
import { buildTaskCandidates } from "@/lib/scheduler/task-candidates";
import {
  formatHoursFromMinutes,
  getAcademicDeadline,
  getPlannerReferenceDate,
  startOfPlannerWeek,
  toDateKey,
} from "@/lib/dates/helpers";
import { clamp, createId, recordFromKeys, sum } from "@/lib/utils";
import type {
  CalendarSlot,
  Goal,
  Preferences,
  SchedulerResult,
  StudyBlock,
  Subject,
  TaskCandidate,
  Topic,
  WeeklyPlan,
} from "@/lib/types/planner";

function buildRecoveryBlock(slot: CalendarSlot, weekStart: string): StudyBlock {
  return {
    id: createId("block"),
    weekStart,
    date: slot.dateKey,
    start: slot.start.toISOString(),
    end: slot.end.toISOString(),
    subjectId: null,
    topicId: null,
    title: "Recovery / buffer",
    unitTitle: null,
    blockType: "recovery",
    intensity: "light",
    generatedReason:
      "The planner preserved this slot as explicit low-friction recovery so the week stays realistic after fixed commitments.",
    scoreBreakdown: {
      priorityWeight: 0,
      deadlineUrgency: 0,
      remainingWorkloadPressure: 0,
      lowMasteryBonus: 0,
      reviewDueBonus: 0,
      neglectedSubjectBonus: 0,
      olympiadSlotBonus: 0,
      badSlotFitPenalty: 0,
      fragmentationPenalty: 0,
      total: 0,
    },
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: [],
    slotEnergy: slot.energy,
    estimatedMinutes: slot.durationMinutes,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
  };
}

function cloneTasks(tasks: TaskCandidate[]) {
  return tasks.map((task) => ({ ...task }));
}

interface DayCapacityEntry {
  capacity: number;
  dayIndex: number;
  scheduleRegime: CalendarSlot["scheduleRegime"];
}

function buildDayCapacityByDate(
  freeSlots: CalendarSlot[],
  dailyCapBoostMinutes: number,
) {
  return freeSlots.reduce<Record<string, DayCapacityEntry>>((accumulator, slot) => {
    const dailyCap = slot.dayStudyCapMinutes + dailyCapBoostMinutes;
    const current = accumulator[slot.dateKey] ?? {
      capacity: 0,
      dayIndex: slot.dayIndex,
      scheduleRegime: slot.scheduleRegime,
    };
    current.capacity = Math.min(dailyCap, current.capacity + slot.durationMinutes);
    current.dayIndex = slot.dayIndex;
    current.scheduleRegime = slot.scheduleRegime;
    accumulator[slot.dateKey] = current;
    return accumulator;
  }, {});
}

function getReservedTargetMinutesForDay(options: {
  dayEntry: DayCapacityEntry;
  preferences: Preferences;
  fillAvailableStudyDays: boolean;
}) {
  const { dayEntry, preferences, fillAvailableStudyDays } = options;

  if (fillAvailableStudyDays) {
    if (dayEntry.scheduleRegime === "holiday" || dayEntry.dayIndex === 6) {
      return dayEntry.capacity;
    }

    if (dayEntry.dayIndex === 0 && preferences.sundayStudy.enabled) {
      return Math.min(
        dayEntry.capacity,
        Math.max(
          45,
          Math.floor((dayEntry.capacity * preferences.sundayStudy.workloadIntensity) / 15) * 15,
        ),
      );
    }

    return 0;
  }

  if (dayEntry.dayIndex === 6) {
    return Math.min(
      dayEntry.capacity,
      Math.max(240, Math.floor((dayEntry.capacity * 0.55) / 15) * 15),
    );
  }

  if (dayEntry.dayIndex === 0 && preferences.sundayStudy.enabled) {
    return Math.min(dayEntry.capacity, 60);
  }

  return 0;
}

function buildDailyTargetMinutes(options: {
  dayCapacityByDate: Record<string, DayCapacityEntry>;
  effectiveCapacityMinutes: number;
  preferences: Preferences;
  fillAvailableStudyDays: boolean;
}) {
  const dayKeys = Object.keys(options.dayCapacityByDate).sort();
  const totalDayCapacity = sum(Object.values(options.dayCapacityByDate).map((entry) => entry.capacity));

  if (!dayKeys.length || totalDayCapacity <= 0 || options.effectiveCapacityMinutes <= 0) {
    return {} as Record<string, number>;
  }

  const targets = dayKeys.reduce<Record<string, number>>((accumulator, dayKey) => {
    accumulator[dayKey] = getReservedTargetMinutesForDay({
      dayEntry: options.dayCapacityByDate[dayKey],
      preferences: options.preferences,
      fillAvailableStudyDays: options.fillAvailableStudyDays,
    });
    return accumulator;
  }, {});

  const reservedTargetMinutes = sum(Object.values(targets));
  const cappedEffectiveCapacityMinutes = clamp(
    Math.max(options.effectiveCapacityMinutes, reservedTargetMinutes),
    0,
    totalDayCapacity,
  );
  let assignedTargetMinutes = reservedTargetMinutes;
  let remainingTargetMinutes = Math.max(0, cappedEffectiveCapacityMinutes - assignedTargetMinutes);

  if (remainingTargetMinutes > 0) {
    dayKeys.forEach((dayKey) => {
      const remainingCapacity = Math.max(
        options.dayCapacityByDate[dayKey].capacity - targets[dayKey],
        0,
      );

      if (remainingCapacity < 15) {
        return;
      }

      const rawShare = (remainingTargetMinutes * remainingCapacity) / Math.max(
        15,
        totalDayCapacity - reservedTargetMinutes,
      );
      const roundedShare = Math.min(
        remainingCapacity,
        Math.max(0, Math.floor(rawShare / 15) * 15),
      );
      targets[dayKey] += roundedShare;
      assignedTargetMinutes += roundedShare;
    });

    remainingTargetMinutes = Math.max(
      0,
      cappedEffectiveCapacityMinutes - assignedTargetMinutes,
    );
  }

  while (remainingTargetMinutes >= 15) {
    const nextDay = dayKeys
      .filter(
        (dayKey) => targets[dayKey] + 15 <= options.dayCapacityByDate[dayKey].capacity,
      )
      .sort((left, right) => {
        const leftRemaining = options.dayCapacityByDate[left].capacity - targets[left];
        const rightRemaining = options.dayCapacityByDate[right].capacity - targets[right];
        return rightRemaining - leftRemaining;
      })[0];

    if (!nextDay) {
      break;
    }

    targets[nextDay] += 15;
    remainingTargetMinutes -= 15;
    assignedTargetMinutes += 15;
  }

  return targets;
}

function sumAssignedMinutesBySubject(blocks: StudyBlock[]) {
  return blocks.reduce<Record<string, number>>((accumulator, block) => {
    if (!block.subjectId) {
      return accumulator;
    }

    accumulator[block.subjectId] = (accumulator[block.subjectId] ?? 0) + block.estimatedMinutes;
    return accumulator;
  }, {});
}

function buildRequiredHoursFromTracks(subjects: Subject[], tracks: Record<string, { recommendedWeeklyHours: number }>) {
  return Object.fromEntries(
    subjects.map((subject) => [subject.id, tracks[subject.id]?.recommendedWeeklyHours ?? 0]),
  );
}

function buildDeadlinePaceHoursFromTracks(subjects: Subject[], tracks: Record<string, { baselineWeeklyHours: number }>) {
  return Object.fromEntries(
    subjects.map((subject) => [subject.id, tracks[subject.id]?.baselineWeeklyHours ?? 0]),
  );
}

function getRemainingRequiredHoursBySubject(
  requiredHoursBySubject: Record<string, number>,
  assignedMinutesBySubject: Record<string, number>,
) {
  return Object.fromEntries(
    Object.entries(requiredHoursBySubject).map(([subjectId, requiredHours]) => [
      subjectId,
      Math.max(requiredHours - (assignedMinutesBySubject[subjectId] ?? 0) / 60, 0),
    ]),
  );
}

interface AllocationPassPolicy {
  allowLowEnergyHeavy?: boolean;
  allowLateNightDeepWork?: boolean;
  preferLongerBlocks?: boolean;
  protectRecovery?: boolean;
  skipMovableRecovery?: boolean;
  heavySessionBoost?: number;
  dailyCapBoostMinutes?: number;
  minBreakMinutes?: number;
  countAsForcedCoverage?: boolean;
  blockSelectionPolicy?: BlockSelectionPolicy;
}

function createStudyBlockFromTask(options: {
  task: TaskCandidate;
  weekStart: string;
  slot: CalendarSlot;
  start: Date;
  durationMinutes: number;
  generatedReason: string;
  scoreBreakdown: StudyBlock["scoreBreakdown"];
  blockType: StudyBlock["blockType"];
  intensity: StudyBlock["intensity"];
}) {
  return {
    id: createId("block"),
    weekStart: options.weekStart,
    date: options.slot.dateKey,
    start: options.start.toISOString(),
    end: addMinutes(options.start, options.durationMinutes).toISOString(),
    subjectId: options.task.subjectId,
    topicId: options.task.topicId,
    title: options.task.title,
    unitTitle: options.task.unitTitle,
    blockType: options.blockType,
    intensity: options.intensity,
    generatedReason: options.generatedReason,
    scoreBreakdown: options.scoreBreakdown,
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: options.task.sourceMaterials,
    slotEnergy: options.slot.energy,
    estimatedMinutes: options.durationMinutes,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
  } satisfies StudyBlock;
}

function allocateTasksToSlots(options: {
  weekStart: Date;
  referenceDate: Date;
  freeSlots: CalendarSlot[];
  tasks: TaskCandidate[];
  subjects: Subject[];
  goals: Goal[];
  topics: Topic[];
  preferences: Preferences;
  lockedBlocks: StudyBlock[];
  priorPlannedBlocks?: StudyBlock[];
  requiredHoursBySubject?: Record<string, number>;
  dailyCapBoostMinutes?: number;
  heavySessionBoost?: number;
  minBreakMinutes?: number;
  protectRecovery?: boolean;
  blockSelectionPolicy?: BlockSelectionPolicy;
  fillAvailableStudyDays?: boolean;
}) {
  const weekStartKey = toDateKey(options.weekStart);
  const subjectMap = new Map(options.subjects.map((subject) => [subject.id, subject]));
  const requiredHoursBySubject =
    options.requiredHoursBySubject ??
    Object.fromEntries(
      options.subjects.map((subject) => [subject.id, 0]),
    );
  const requiredMinutesBySubject = Object.fromEntries(
    Object.entries(requiredHoursBySubject).map(([key, value]) => [key, Math.round(value * 60)]),
  );
  const assignedMinutesBySubject = recordFromKeys(subjectIds, () => 0);
  const dailyMinutes: Record<string, number> = {};
  const heavyBlocksPerDay: Record<string, number> = {};

  function hasReachedWeeklyTarget(task: TaskCandidate) {
    if (options.fillAvailableStudyDays) {
      return false;
    }

    if (!task.subjectId) {
      return false;
    }

    const requiredMinutes = requiredMinutesBySubject[task.subjectId] ?? 0;
    const assignedMinutes = assignedMinutesBySubject[task.subjectId] ?? 0;

    if (task.kind === "review") {
      return assignedMinutes >= requiredMinutes + 45;
    }

    return requiredMinutes > 0 && assignedMinutes >= requiredMinutes;
  }

  function allWeeklyTargetsSatisfied() {
    if (options.fillAvailableStudyDays) {
      return workingTasks.every((task) => task.remainingMinutes < 20);
    }

    return Object.entries(requiredMinutesBySubject)
      .filter(([, requiredMinutes]) => requiredMinutes > 0)
      .every(
        ([subjectId, requiredMinutes]) =>
          (assignedMinutesBySubject[subjectId as keyof typeof assignedMinutesBySubject] ?? 0) >=
          requiredMinutes,
      );
  }

  function canInsertRecoveryBlock(slot: CalendarSlot, usedToday: number, dailyBudget: number) {
    if (slot.durationMinutes < 20) {
      return false;
    }

    if (scheduledBlocks.some((block) => block.date === slot.dateKey && block.blockType === "recovery")) {
      return false;
    }

    return usedToday <= dailyBudget - 30;
  }

  options.lockedBlocks.forEach((block) => {
    const dateKey = block.date;
    dailyMinutes[dateKey] = (dailyMinutes[dateKey] ?? 0) + block.estimatedMinutes;
    if (block.intensity === "heavy") {
      heavyBlocksPerDay[dateKey] = (heavyBlocksPerDay[dateKey] ?? 0) + 1;
    }

    if (block.subjectId) {
      assignedMinutesBySubject[block.subjectId] += block.estimatedMinutes;
    }
  });

  const totalFreeSlotMinutes = Math.round(sum(options.freeSlots.map((slot) => slot.durationMinutes)));
  const bufferedCapacityMinutes = Math.round(
    totalFreeSlotMinutes * (1 - options.preferences.weeklyBufferRatio),
  );
  const requiredMinutes = sum(Object.values(requiredMinutesBySubject));
  const needsIntensityRamp = requiredMinutes > bufferedCapacityMinutes;
  const dailyCapBoostMinutes = options.dailyCapBoostMinutes ?? 0;
  const dayCapacityByDate = buildDayCapacityByDate(options.freeSlots, dailyCapBoostMinutes);
  const aggressiveStudyDayMinutes = Object.values(dayCapacityByDate).reduce((total, dayEntry) => {
    return total + getReservedTargetMinutesForDay({
      dayEntry,
      preferences: options.preferences,
      fillAvailableStudyDays: true,
    });
  }, 0);
  const effectiveCapacityMinutes = clamp(
    options.fillAvailableStudyDays
      ? Math.max(
          needsIntensityRamp
            ? Math.min(totalFreeSlotMinutes, requiredMinutes)
            : bufferedCapacityMinutes,
          aggressiveStudyDayMinutes,
        )
      : needsIntensityRamp
        ? Math.min(totalFreeSlotMinutes, requiredMinutes)
        : bufferedCapacityMinutes,
    0,
    totalFreeSlotMinutes,
  );
  const maxHeavySessionsPerDay =
    options.preferences.maxHeavySessionsPerDay +
    (needsIntensityRamp ? 1 : 0) +
    (options.heavySessionBoost ?? 0);
  const minBreakMinutes = options.minBreakMinutes ?? options.preferences.minBreakMinutes;
  const dailyTargetMinutes = buildDailyTargetMinutes({
    dayCapacityByDate,
    effectiveCapacityMinutes,
    preferences: options.preferences,
    fillAvailableStudyDays: options.fillAvailableStudyDays ?? false,
  });
  let consumedStudyMinutes = 0;
  const workingTasks = cloneTasks(options.tasks);
  const scheduledBlocks: StudyBlock[] = [];
  let usedSundayMinutes = 0;

  function shouldHoldCapacityForLaterDays(dateKey: string) {
    const targetForToday = dailyTargetMinutes[dateKey] ?? 0;
    const usedToday = dailyMinutes[dateKey] ?? 0;

    if (targetForToday <= 0 || usedToday < targetForToday) {
      return false;
    }

    return Object.entries(dailyTargetMinutes).some(
      ([candidateDateKey, candidateTarget]) =>
        candidateDateKey > dateKey &&
        (dailyMinutes[candidateDateKey] ?? 0) + 15 <= candidateTarget,
    );
  }

  options.freeSlots.forEach((slot) => {
    if (consumedStudyMinutes >= effectiveCapacityMinutes) {
      return;
    }

    if (shouldHoldCapacityForLaterDays(slot.dateKey)) {
      return;
    }

    let cursor = slot.start;
    let remainingSlotMinutes = slot.durationMinutes;

    while (remainingSlotMinutes >= 20 && consumedStudyMinutes < effectiveCapacityMinutes) {
      const dailyBudget = slot.dayStudyCapMinutes + (options.dailyCapBoostMinutes ?? 0);
      const usedToday = dailyMinutes[slot.dateKey] ?? 0;
      const availableToday = dailyBudget - usedToday;

      if (availableToday < 20) {
        break;
      }

      if (shouldHoldCapacityForLaterDays(slot.dateKey)) {
        break;
      }

      const slotSlice: CalendarSlot = {
        ...slot,
        start: cursor,
        end: addMinutes(cursor, Math.min(remainingSlotMinutes, availableToday)),
        durationMinutes: Math.min(remainingSlotMinutes, availableToday),
      };

      const scoredOptions = workingTasks
        .filter((task) => task.remainingMinutes >= 20)
        .filter((task) => !hasReachedWeeklyTarget(task))
        .map((task) => {
          const blockOption = selectBlockOption(
            task,
            slotSlice,
            options.preferences,
            options.blockSelectionPolicy,
          );
          if (!blockOption) {
            return null;
          }

          if (
            blockOption.intensity === "heavy" &&
            (heavyBlocksPerDay[slot.dateKey] ?? 0) >= maxHeavySessionsPerDay
          ) {
            return null;
          }

          const scoreBreakdown = scoreTaskCandidate(task, slotSlice, blockOption, {
            subjectMap,
            preferences: options.preferences,
            requiredMinutesBySubject,
            assignedMinutesBySubject,
            referenceDate: options.referenceDate,
          });

          return {
            task,
            blockOption,
            scoreBreakdown,
          };
        })
        .filter(Boolean)
        .sort(
          (left, right) =>
            (right?.scoreBreakdown.total ?? 0) - (left?.scoreBreakdown.total ?? 0),
        ) as Array<{
        task: TaskCandidate;
        blockOption: NonNullable<ReturnType<typeof selectBlockOption>>;
        scoreBreakdown: StudyBlock["scoreBreakdown"];
      }>;

      const winner = scoredOptions[0];
      const allTargetsMet = allWeeklyTargetsSatisfied();
      const shouldProtectRecovery =
        options.protectRecovery ?? (!needsIntensityRamp || allTargetsMet);

      if (!winner) {
        if (
          shouldProtectRecovery &&
          canInsertRecoveryBlock(slotSlice, usedToday, dailyBudget) &&
          (slotSlice.energy === "low" || allTargetsMet)
        ) {
          const recoveryDuration = clamp(Math.min(30, remainingSlotMinutes), 20, 30);
          const recoverySlot = {
            ...slotSlice,
            end: addMinutes(cursor, recoveryDuration),
            durationMinutes: recoveryDuration,
          };
          const recoveryBlock = buildRecoveryBlock(recoverySlot, weekStartKey);
          scheduledBlocks.push(recoveryBlock);
          dailyMinutes[slot.dateKey] = (dailyMinutes[slot.dateKey] ?? 0) + recoveryDuration;
          cursor = addMinutes(cursor, recoveryDuration + minBreakMinutes);
          remainingSlotMinutes = Math.max(
            0,
            remainingSlotMinutes - recoveryDuration - minBreakMinutes,
          );
          continue;
        }

        break;
      }

      if (
        winner.scoreBreakdown.total < 8 &&
        shouldProtectRecovery &&
        (slotSlice.energy === "low" || allTargetsMet)
      ) {
        if (canInsertRecoveryBlock(slotSlice, usedToday, dailyBudget)) {
          const recoveryDuration = clamp(Math.min(30, remainingSlotMinutes), 20, 30);
          const recoverySlot = {
            ...slotSlice,
            end: addMinutes(cursor, recoveryDuration),
            durationMinutes: recoveryDuration,
          };
          const recoveryBlock = buildRecoveryBlock(recoverySlot, weekStartKey);
          scheduledBlocks.push(recoveryBlock);
          dailyMinutes[slot.dateKey] = (dailyMinutes[slot.dateKey] ?? 0) + recoveryDuration;
          cursor = addMinutes(cursor, recoveryDuration + minBreakMinutes);
          remainingSlotMinutes = Math.max(
            0,
            remainingSlotMinutes - recoveryDuration - minBreakMinutes,
          );
          continue;
        }

        break;
      }

      const block = createStudyBlockFromTask({
        task: winner.task,
        weekStart: weekStartKey,
        slot: slotSlice,
        start: cursor,
        durationMinutes: winner.blockOption.durationMinutes,
        generatedReason: buildGeneratedReason(winner.task, slotSlice, winner.scoreBreakdown),
        scoreBreakdown: winner.scoreBreakdown,
        blockType: winner.blockOption.blockType,
        intensity: winner.blockOption.intensity,
      });

      scheduledBlocks.push(block);
      winner.task.remainingMinutes -= winner.blockOption.durationMinutes;
      dailyMinutes[slot.dateKey] =
        (dailyMinutes[slot.dateKey] ?? 0) + winner.blockOption.durationMinutes;
      if (winner.blockOption.intensity === "heavy") {
        heavyBlocksPerDay[slot.dateKey] = (heavyBlocksPerDay[slot.dateKey] ?? 0) + 1;
      }
      if (winner.task.subjectId) {
        assignedMinutesBySubject[winner.task.subjectId] += winner.blockOption.durationMinutes;
      }
      if (slot.dayIndex === 0) {
        usedSundayMinutes += winner.blockOption.durationMinutes;
      }
      consumedStudyMinutes += winner.blockOption.durationMinutes;
      cursor = addMinutes(
        cursor,
        winner.blockOption.durationMinutes + minBreakMinutes,
      );
      remainingSlotMinutes = Math.max(
        0,
        remainingSlotMinutes -
          winner.blockOption.durationMinutes -
          minBreakMinutes,
      );
    }
  });

  return {
    scheduledBlocks,
    unscheduledTasks: workingTasks.filter((task) => task.remainingMinutes >= 20),
    usedSundayMinutes,
    scheduledStudyMinutes: consumedStudyMinutes,
  };
}

function buildAutomaticDailyCapBoost(options: {
  freeSlots: CalendarSlot[];
  requiredMinutes: number;
  preferences: Preferences;
}) {
  const totalFreeSlotMinutes = sum(options.freeSlots.map((slot) => slot.durationMinutes));
  const bufferedCapacityMinutes =
    totalFreeSlotMinutes * (1 - options.preferences.weeklyBufferRatio);
  const activeDayCount = new Set(options.freeSlots.map((slot) => slot.dateKey)).size;

  return activeDayCount > 0
    ? clamp(
        Math.ceil(Math.max(0, options.requiredMinutes - bufferedCapacityMinutes) / activeDayCount / 15) * 15,
        0,
        120,
      )
    : 0;
}

function buildAllocationPasses(baseDailyCapBoostMinutes: number, options?: { partialCurrentWeek?: boolean }): AllocationPassPolicy[] {
  const passes: AllocationPassPolicy[] = [
    {
      protectRecovery: true,
      skipMovableRecovery: false,
      dailyCapBoostMinutes: baseDailyCapBoostMinutes,
      minBreakMinutes: undefined,
      countAsForcedCoverage: false,
    },
    {
      protectRecovery: false,
      skipMovableRecovery: true,
      dailyCapBoostMinutes: baseDailyCapBoostMinutes + 240,
      heavySessionBoost: 1,
      minBreakMinutes: 10,
      blockSelectionPolicy: {
        preferLongerBlocks: true,
      },
      countAsForcedCoverage: true,
    },
    {
      protectRecovery: false,
      skipMovableRecovery: true,
      dailyCapBoostMinutes: baseDailyCapBoostMinutes + 600,
      heavySessionBoost: 2,
      minBreakMinutes: 5,
      blockSelectionPolicy: {
        preferLongerBlocks: true,
        allowLowEnergyHeavy: true,
        allowLateNightDeepWork: true,
      },
      countAsForcedCoverage: true,
    },
  ];

  if (options?.partialCurrentWeek) {
    return passes.slice(0, 1);
  }

  return passes;
}

export function generateStudyPlanForWeek(options: {
  weekStart?: Date;
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: import("@/lib/types/planner").FixedEvent[];
  preferences: Preferences;
  lockedBlocks?: StudyBlock[];
  existingPlannedBlocks?: StudyBlock[];
  dailyCapBoostMinutes?: number;
  horizonStartDate?: Date;
}): SchedulerResult {
  const weekStart = startOfPlannerWeek(options.weekStart ?? new Date());
  const referenceDate = getPlannerReferenceDate(weekStart);
  const horizonStartDate = options.horizonStartDate ?? getPlannerReferenceDate(startOfPlannerWeek(new Date()));
  const isPartialCurrentWeek = toDateKey(referenceDate) !== toDateKey(weekStart);
  const lockedBlocks = options.lockedBlocks ?? [];
  const weekStartKey = toDateKey(weekStart);
  const existingPlannedBlocks = options.existingPlannedBlocks ?? lockedBlocks;
  const deadlineTracks = computeSubjectDeadlineTracks({
    subjects: options.subjects,
    goals: options.goals,
    topics: options.topics,
    referenceDate,
    horizonStartDate,
    weekStartDate: weekStart,
    weekEndDate: addDays(weekStart, 6),
    priorPlannedBlocks: existingPlannedBlocks,
  });
  const requiredHoursBySubject = buildRequiredHoursFromTracks(options.subjects, deadlineTracks);
  const deadlinePaceHoursBySubject = buildDeadlinePaceHoursFromTracks(options.subjects, deadlineTracks);
  const subjectDeadlinesById = Object.fromEntries(
    options.subjects.map((subject) => [
      subject.id,
      deadlineTracks[subject.id]?.deadline ?? subject.deadline,
    ]),
  );
  const hasAvailabilityConstraints =
    options.fixedEvents.length > 0 ||
    options.preferences.schoolSchedule.enabled ||
    options.preferences.holidaySchedule.enabled;

  if (!hasAvailabilityConstraints) {
    const studyBlocks = [...lockedBlocks].sort(
      (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
    );

    return {
      studyBlocks,
      weeklyPlan: buildUnconfiguredWeeklyPlan({
        weekStart: weekStartKey,
        subjects: options.subjects,
        studyBlocks,
        topics: options.topics,
        goals: options.goals,
        referenceDate,
      }),
      freeSlots: [],
      unscheduledTasks: buildTaskCandidates({
        topics: options.topics,
        existingPlannedBlocks,
        referenceDate,
        subjectDeadlinesById,
      }),
    };
  }

  const initialFreeSlots = calculateFreeSlots({
    weekStart,
    fixedEvents: options.fixedEvents,
    preferences: options.preferences,
    blockedStudyBlocks: lockedBlocks,
    planningStart: referenceDate,
  });
  const capacityFreeSlots = calculateFreeSlots({
    weekStart,
    fixedEvents: options.fixedEvents,
    preferences: options.preferences,
    blockedStudyBlocks: lockedBlocks,
    planningStart: referenceDate,
    skipMovableRecovery: true,
  });
  const shouldFillAvailableStudyDays =
    Object.values(deadlineTracks).some((track) => track.uncoveredGoalHours > 0.1) &&
    initialFreeSlots.some(
      (slot) =>
        slot.scheduleRegime === "holiday" ||
        slot.dayIndex === 6 ||
        (slot.dayIndex === 0 && options.preferences.sundayStudy.enabled),
    );
  const requiredMinutes = sum(Object.values(requiredHoursBySubject).map((value) => value * 60));
  const automaticDailyCapBoostMinutes = buildAutomaticDailyCapBoost({
    freeSlots: initialFreeSlots,
    requiredMinutes,
    preferences: options.preferences,
  });
  const passPolicies = buildAllocationPasses(
    Math.max(options.dailyCapBoostMinutes ?? 0, automaticDailyCapBoostMinutes),
    { partialCurrentWeek: isPartialCurrentWeek },
  );
  const scheduledBlocks: StudyBlock[] = [];
  let usedSundayMinutes = 0;
  let forcedCoverageMinutes = 0;

  for (const passPolicy of passPolicies) {
    if (passPolicy.countAsForcedCoverage && scheduledBlocks.some((block) => !block.subjectId)) {
      const reclaimedRecoveryIds = new Set(
        scheduledBlocks.filter((block) => !block.subjectId).map((block) => block.id),
      );
      const preservedBlocks = scheduledBlocks.filter((block) => !reclaimedRecoveryIds.has(block.id));
      scheduledBlocks.length = 0;
      scheduledBlocks.push(...preservedBlocks);
    }

    const assignedMinutesBySubject = sumAssignedMinutesBySubject([...lockedBlocks, ...scheduledBlocks]);
    const remainingRequiredHoursBySubject = getRemainingRequiredHoursBySubject(
      requiredHoursBySubject,
      assignedMinutesBySubject,
    );
    const remainingRequiredMinutes = sum(
      Object.values(remainingRequiredHoursBySubject).map((hours) => Math.round(hours * 60)),
    );

    if (remainingRequiredMinutes <= 0) {
      break;
    }

    const freeSlots = calculateFreeSlots({
      weekStart,
      fixedEvents: options.fixedEvents,
      preferences: options.preferences,
      blockedStudyBlocks: [...lockedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
      planningStart: referenceDate,
      skipMovableRecovery: passPolicy.skipMovableRecovery,
    });

    if (!freeSlots.length) {
      continue;
    }

    const tasks = buildTaskCandidates({
      topics: options.topics,
      existingPlannedBlocks: [...existingPlannedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
      referenceDate,
      subjectDeadlinesById,
    });

    const result = allocateTasksToSlots({
      weekStart,
      referenceDate,
      freeSlots,
      tasks,
      subjects: options.subjects,
      goals: options.goals,
      topics: options.topics,
      preferences: options.preferences,
      lockedBlocks: [...lockedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
      priorPlannedBlocks: existingPlannedBlocks,
      requiredHoursBySubject: remainingRequiredHoursBySubject,
      dailyCapBoostMinutes: passPolicy.dailyCapBoostMinutes,
      heavySessionBoost: passPolicy.heavySessionBoost,
      minBreakMinutes: passPolicy.minBreakMinutes,
      protectRecovery: passPolicy.protectRecovery,
      blockSelectionPolicy: passPolicy.blockSelectionPolicy,
      fillAvailableStudyDays: shouldFillAvailableStudyDays,
    });

    if (!result.scheduledBlocks.length) {
      continue;
    }

    scheduledBlocks.push(...result.scheduledBlocks);
    usedSundayMinutes += result.usedSundayMinutes;
    if (passPolicy.countAsForcedCoverage) {
      forcedCoverageMinutes += result.scheduledStudyMinutes;
    }
  }

  const finalFreeSlots = calculateFreeSlots({
    weekStart,
    fixedEvents: options.fixedEvents,
    preferences: options.preferences,
    blockedStudyBlocks: [...lockedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
    planningStart: referenceDate,
  });
  const finalTasks = buildTaskCandidates({
    topics: options.topics,
    existingPlannedBlocks: [...existingPlannedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
    referenceDate,
    subjectDeadlinesById,
  });
  const finalAssignedMinutesBySubject = sumAssignedMinutesBySubject([...lockedBlocks, ...scheduledBlocks]);
  const remainingRequiredHoursBySubject = getRemainingRequiredHoursBySubject(
    requiredHoursBySubject,
    finalAssignedMinutesBySubject,
  );
  const studyBlocks = [...lockedBlocks, ...scheduledBlocks].sort(
    (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
  );
  const weeklyPlan = buildWeeklyPlan({
    weekStart: weekStartKey,
    subjects: options.subjects,
    studyBlocks,
    topics: options.topics,
    goals: options.goals,
    freeSlots: finalFreeSlots,
    capacityFreeSlots,
    referenceDate,
    horizonStartDate,
    requiredHoursBySubject,
    deadlinePaceHoursBySubject,
    forcedCoverageMinutes,
    usedSundayMinutes,
    unscheduledTasks: finalTasks.filter((task) => {
      if (!task.subjectId) {
        return false;
      }

      return (remainingRequiredHoursBySubject[task.subjectId] ?? 0) > 0;
    }),
    priorPlannedBlocks: existingPlannedBlocks,
    cumulativePlannedBlocks: [...existingPlannedBlocks, ...scheduledBlocks.filter((block) => block.subjectId)],
  });

  return {
    studyBlocks,
    weeklyPlan,
    freeSlots: finalFreeSlots,
    unscheduledTasks: finalTasks,
  };
}

export function getPlanningHorizonEndWeek(goals: Goal[], subjects: Subject[], referenceDate: Date) {
  const academicDeadline = getAcademicDeadline(referenceDate);
  const latestConfiguredDeadline = [...goals.map((goal) => goal.deadline), ...subjects.map((subject) => subject.deadline)]
    .map((value) => new Date(value))
    .filter((date) => !Number.isNaN(date.getTime()))
    .reduce(
      (latest, candidate) => (isAfter(candidate, latest) ? candidate : latest),
      academicDeadline,
    );

  return startOfPlannerWeek(
    latestConfiguredDeadline < academicDeadline ? latestConfiguredDeadline : academicDeadline,
  );
}

export function generateStudyPlanHorizon(options: {
  startWeek?: Date;
  endWeek?: Date;
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: import("@/lib/types/planner").FixedEvent[];
  preferences: Preferences;
  existingStudyBlocks?: StudyBlock[];
}) {
  const startWeek = startOfPlannerWeek(options.startWeek ?? new Date());
  const horizonStartDate = getPlannerReferenceDate(startWeek);
  const endWeek = options.endWeek
    ? startOfPlannerWeek(options.endWeek)
    : getPlanningHorizonEndWeek(options.goals, options.subjects, startWeek);
  const existingStudyBlocks = options.existingStudyBlocks ?? [];
  const preservedDoneBlocks = existingStudyBlocks.filter((block) => block.status === "done");
  const horizonStudyBlocks: StudyBlock[] = [];
  const weeklyPlans: WeeklyPlan[] = [];
  const accumulatedBlocks: StudyBlock[] = [];

  for (
    let currentWeek = startWeek;
    currentWeek.getTime() <= endWeek.getTime();
    currentWeek = addDays(currentWeek, 7)
  ) {
    const weekKey = toDateKey(currentWeek);
    const lockedBlocks = preservedDoneBlocks.filter((block) => block.weekStart === weekKey);
    const result = generateStudyPlanForWeek({
      weekStart: currentWeek,
      goals: options.goals,
      subjects: options.subjects,
      topics: options.topics,
      fixedEvents: options.fixedEvents,
      preferences: options.preferences,
      lockedBlocks,
      existingPlannedBlocks: [...accumulatedBlocks, ...lockedBlocks],
      horizonStartDate,
    });

    horizonStudyBlocks.push(...result.studyBlocks);
    weeklyPlans.push(result.weeklyPlan);
    accumulatedBlocks.push(...result.studyBlocks);
  }

  return {
    studyBlocks: horizonStudyBlocks.sort(
      (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
    ),
    weeklyPlans,
  };
}

export function getStudyPlanSummary(result: SchedulerResult) {
  return {
    assignedHours: formatHoursFromMinutes(
      result.studyBlocks.reduce((total, block) => total + block.estimatedMinutes, 0),
    ),
    unscheduledHours: formatHoursFromMinutes(
      result.unscheduledTasks.reduce((total, task) => total + task.remainingMinutes, 0),
    ),
  };
}
