import { addDays, addMinutes, isAfter } from "date-fns";

import { subjectIds } from "@/lib/constants/planner";
import {
  buildUnconfiguredWeeklyPlan,
  buildWeeklyPlan,
  computeSubjectDeadlineTracks,
} from "@/lib/scheduler/feasibility";
import { calculateFreeSlots } from "@/lib/scheduler/free-slots";
import { scoreTaskCandidate, buildGeneratedReason } from "@/lib/scheduler/scoring";
import { selectBlockOption } from "@/lib/scheduler/slot-classifier";
import { buildTaskCandidates } from "@/lib/scheduler/task-candidates";
import {
  formatHoursFromMinutes,
  getAcademicDeadline,
  getPlannerReferenceDate,
  startOfPlannerWeek,
  toDateKey,
} from "@/lib/dates/helpers";
import { clamp, createId, recordFromKeys, sum } from "@/lib/utils";
import type {
  CalendarSlot,
  Goal,
  Preferences,
  SchedulerResult,
  StudyBlock,
  Subject,
  TaskCandidate,
  Topic,
  WeeklyPlan,
} from "@/lib/types/planner";

function buildRecoveryBlock(slot: CalendarSlot, weekStart: string): StudyBlock {
  return {
    id: createId("block"),
    weekStart,
    date: slot.dateKey,
    start: slot.start.toISOString(),
    end: slot.end.toISOString(),
    subjectId: null,
    topicId: null,
    title: "Recovery / buffer",
    unitTitle: null,
    blockType: "recovery",
    intensity: "light",
    generatedReason:
      "The planner preserved this slot as explicit low-friction recovery so the week stays realistic after fixed commitments.",
    scoreBreakdown: {
      priorityWeight: 0,
      deadlineUrgency: 0,
      remainingWorkloadPressure: 0,
      lowMasteryBonus: 0,
      reviewDueBonus: 0,
      neglectedSubjectBonus: 0,
      olympiadSlotBonus: 0,
      badSlotFitPenalty: 0,
      fragmentationPenalty: 0,
      total: 0,
    },
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: [],
    slotEnergy: slot.energy,
    estimatedMinutes: slot.durationMinutes,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
  };
}

function cloneTasks(tasks: TaskCandidate[]) {
  return tasks.map((task) => ({ ...task }));
}

function createStudyBlockFromTask(options: {
  task: TaskCandidate;
  weekStart: string;
  slot: CalendarSlot;
  start: Date;
  durationMinutes: number;
  generatedReason: string;
  scoreBreakdown: StudyBlock["scoreBreakdown"];
  blockType: StudyBlock["blockType"];
  intensity: StudyBlock["intensity"];
}) {
  return {
    id: createId("block"),
    weekStart: options.weekStart,
    date: options.slot.dateKey,
    start: options.start.toISOString(),
    end: addMinutes(options.start, options.durationMinutes).toISOString(),
    subjectId: options.task.subjectId,
    topicId: options.task.topicId,
    title: options.task.title,
    unitTitle: options.task.unitTitle,
    blockType: options.blockType,
    intensity: options.intensity,
    generatedReason: options.generatedReason,
    scoreBreakdown: options.scoreBreakdown,
    status: "planned",
    isAutoGenerated: true,
    sourceMaterials: options.task.sourceMaterials,
    slotEnergy: options.slot.energy,
    estimatedMinutes: options.durationMinutes,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
  } satisfies StudyBlock;
}

function allocateTasksToSlots(options: {
  weekStart: Date;
  referenceDate: Date;
  freeSlots: CalendarSlot[];
  tasks: TaskCandidate[];
  subjects: Subject[];
  goals: Goal[];
  topics: Topic[];
  preferences: Preferences;
  lockedBlocks: StudyBlock[];
  priorPlannedBlocks?: StudyBlock[];
  requiredHoursBySubject?: Record<string, number>;
  dailyCapBoostMinutes?: number;
}) {
  const weekStartKey = toDateKey(options.weekStart);
  const subjectMap = new Map(options.subjects.map((subject) => [subject.id, subject]));
  const requiredHoursBySubject =
    options.requiredHoursBySubject ??
    Object.fromEntries(
      options.subjects.map((subject) => [subject.id, 0]),
    );
  const requiredMinutesBySubject = Object.fromEntries(
    Object.entries(requiredHoursBySubject).map(([key, value]) => [key, Math.round(value * 60)]),
  );
  const assignedMinutesBySubject = recordFromKeys(subjectIds, () => 0);
  const dailyMinutes: Record<string, number> = {};
  const heavyBlocksPerDay: Record<string, number> = {};

  function hasReachedWeeklyTarget(task: TaskCandidate) {
    if (!task.subjectId) {
      return false;
    }

    const requiredMinutes = requiredMinutesBySubject[task.subjectId] ?? 0;
    const assignedMinutes = assignedMinutesBySubject[task.subjectId] ?? 0;

    if (task.kind === "review") {
      return assignedMinutes >= requiredMinutes + 45;
    }

    return requiredMinutes > 0 && assignedMinutes >= requiredMinutes;
  }

  function allWeeklyTargetsSatisfied() {
    return Object.entries(requiredMinutesBySubject)
      .filter(([, requiredMinutes]) => requiredMinutes > 0)
      .every(
        ([subjectId, requiredMinutes]) =>
          (assignedMinutesBySubject[subjectId as keyof typeof assignedMinutesBySubject] ?? 0) >=
          requiredMinutes,
      );
  }

  function canInsertRecoveryBlock(slot: CalendarSlot, usedToday: number, dailyBudget: number) {
    if (slot.durationMinutes < 20) {
      return false;
    }

    if (scheduledBlocks.some((block) => block.date === slot.dateKey && block.blockType === "recovery")) {
      return false;
    }

    return usedToday <= dailyBudget - 30;
  }

  options.lockedBlocks.forEach((block) => {
    const dateKey = block.date;
    dailyMinutes[dateKey] = (dailyMinutes[dateKey] ?? 0) + block.estimatedMinutes;
    if (block.intensity === "heavy") {
      heavyBlocksPerDay[dateKey] = (heavyBlocksPerDay[dateKey] ?? 0) + 1;
    }

    if (block.subjectId) {
      assignedMinutesBySubject[block.subjectId] += block.estimatedMinutes;
    }
  });

  const totalFreeSlotMinutes = Math.round(sum(options.freeSlots.map((slot) => slot.durationMinutes)));
  const bufferedCapacityMinutes = Math.round(
    totalFreeSlotMinutes * (1 - options.preferences.weeklyBufferRatio),
  );
  const requiredMinutes = sum(Object.values(requiredMinutesBySubject));
  const needsIntensityRamp = requiredMinutes > bufferedCapacityMinutes;
  const effectiveCapacityMinutes = needsIntensityRamp
    ? Math.min(totalFreeSlotMinutes, requiredMinutes)
    : bufferedCapacityMinutes;
  const maxHeavySessionsPerDay =
    options.preferences.maxHeavySessionsPerDay + (needsIntensityRamp ? 1 : 0);
  let consumedMinutes = 0;
  const workingTasks = cloneTasks(options.tasks);
  const scheduledBlocks: StudyBlock[] = [];

  options.freeSlots.forEach((slot) => {
    if (consumedMinutes >= effectiveCapacityMinutes) {
      return;
    }

    let cursor = slot.start;
    let remainingSlotMinutes = slot.durationMinutes;

    while (remainingSlotMinutes >= 20 && consumedMinutes < effectiveCapacityMinutes) {
      const dailyBudget = slot.dayStudyCapMinutes + (options.dailyCapBoostMinutes ?? 0);
      const usedToday = dailyMinutes[slot.dateKey] ?? 0;
      const availableToday = dailyBudget - usedToday;

      if (availableToday < 20) {
        break;
      }

      const slotSlice: CalendarSlot = {
        ...slot,
        start: cursor,
        end: addMinutes(cursor, Math.min(remainingSlotMinutes, availableToday)),
        durationMinutes: Math.min(remainingSlotMinutes, availableToday),
      };

      const scoredOptions = workingTasks
        .filter((task) => task.remainingMinutes >= 20)
        .filter((task) => !hasReachedWeeklyTarget(task))
        .map((task) => {
          const blockOption = selectBlockOption(task, slotSlice, options.preferences);
          if (!blockOption) {
            return null;
          }

          if (
            blockOption.intensity === "heavy" &&
            (heavyBlocksPerDay[slot.dateKey] ?? 0) >= maxHeavySessionsPerDay
          ) {
            return null;
          }

          const scoreBreakdown = scoreTaskCandidate(task, slotSlice, blockOption, {
            subjectMap,
            preferences: options.preferences,
            requiredMinutesBySubject,
            assignedMinutesBySubject,
            referenceDate: options.referenceDate,
          });

          return {
            task,
            blockOption,
            scoreBreakdown,
          };
        })
        .filter(Boolean)
        .sort(
          (left, right) =>
            (right?.scoreBreakdown.total ?? 0) - (left?.scoreBreakdown.total ?? 0),
        ) as Array<{
        task: TaskCandidate;
        blockOption: NonNullable<ReturnType<typeof selectBlockOption>>;
        scoreBreakdown: StudyBlock["scoreBreakdown"];
      }>;

      const winner = scoredOptions[0];
      const allTargetsMet = allWeeklyTargetsSatisfied();
      const shouldProtectRecovery = !needsIntensityRamp || allTargetsMet;

      if (!winner) {
        if (
          shouldProtectRecovery &&
          canInsertRecoveryBlock(slotSlice, usedToday, dailyBudget) &&
          (slotSlice.energy === "low" || allTargetsMet)
        ) {
          const recoveryDuration = clamp(Math.min(30, remainingSlotMinutes), 20, 30);
          const recoverySlot = {
            ...slotSlice,
            end: addMinutes(cursor, recoveryDuration),
            durationMinutes: recoveryDuration,
          };
          const recoveryBlock = buildRecoveryBlock(recoverySlot, weekStartKey);
          scheduledBlocks.push(recoveryBlock);
          dailyMinutes[slot.dateKey] = (dailyMinutes[slot.dateKey] ?? 0) + recoveryDuration;
          cursor = addMinutes(cursor, recoveryDuration + options.preferences.minBreakMinutes);
          remainingSlotMinutes = Math.max(
            0,
            remainingSlotMinutes - recoveryDuration - options.preferences.minBreakMinutes,
          );
          consumedMinutes += recoveryDuration;
          continue;
        }

        break;
      }

      if (
        winner.scoreBreakdown.total < 8 &&
        shouldProtectRecovery &&
        (slotSlice.energy === "low" || allTargetsMet)
      ) {
        if (canInsertRecoveryBlock(slotSlice, usedToday, dailyBudget)) {
          const recoveryDuration = clamp(Math.min(30, remainingSlotMinutes), 20, 30);
          const recoverySlot = {
            ...slotSlice,
            end: addMinutes(cursor, recoveryDuration),
            durationMinutes: recoveryDuration,
          };
          const recoveryBlock = buildRecoveryBlock(recoverySlot, weekStartKey);
          scheduledBlocks.push(recoveryBlock);
          dailyMinutes[slot.dateKey] = (dailyMinutes[slot.dateKey] ?? 0) + recoveryDuration;
          cursor = addMinutes(cursor, recoveryDuration + options.preferences.minBreakMinutes);
          remainingSlotMinutes = Math.max(
            0,
            remainingSlotMinutes - recoveryDuration - options.preferences.minBreakMinutes,
          );
          consumedMinutes += recoveryDuration;
          continue;
        }

        break;
      }

      const block = createStudyBlockFromTask({
        task: winner.task,
        weekStart: weekStartKey,
        slot: slotSlice,
        start: cursor,
        durationMinutes: winner.blockOption.durationMinutes,
        generatedReason: buildGeneratedReason(winner.task, slotSlice, winner.scoreBreakdown),
        scoreBreakdown: winner.scoreBreakdown,
        blockType: winner.blockOption.blockType,
        intensity: winner.blockOption.intensity,
      });

      scheduledBlocks.push(block);
      winner.task.remainingMinutes -= winner.blockOption.durationMinutes;
      dailyMinutes[slot.dateKey] =
        (dailyMinutes[slot.dateKey] ?? 0) + winner.blockOption.durationMinutes;
      if (winner.blockOption.intensity === "heavy") {
        heavyBlocksPerDay[slot.dateKey] = (heavyBlocksPerDay[slot.dateKey] ?? 0) + 1;
      }
      if (winner.task.subjectId) {
        assignedMinutesBySubject[winner.task.subjectId] += winner.blockOption.durationMinutes;
      }
      consumedMinutes += winner.blockOption.durationMinutes;
      cursor = addMinutes(
        cursor,
        winner.blockOption.durationMinutes + options.preferences.minBreakMinutes,
      );
      remainingSlotMinutes = Math.max(
        0,
        remainingSlotMinutes -
          winner.blockOption.durationMinutes -
          options.preferences.minBreakMinutes,
      );
    }
  });

  return {
    scheduledBlocks,
    unscheduledTasks: workingTasks.filter((task) => task.remainingMinutes >= 20),
  };
}

export function generateStudyPlanForWeek(options: {
  weekStart?: Date;
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: import("@/lib/types/planner").FixedEvent[];
  preferences: Preferences;
  lockedBlocks?: StudyBlock[];
  existingPlannedBlocks?: StudyBlock[];
  dailyCapBoostMinutes?: number;
}): SchedulerResult {
  const weekStart = startOfPlannerWeek(options.weekStart ?? new Date());
  const referenceDate = getPlannerReferenceDate(weekStart);
  const lockedBlocks = options.lockedBlocks ?? [];
  const weekStartKey = toDateKey(weekStart);
  const existingPlannedBlocks = options.existingPlannedBlocks ?? lockedBlocks;
  const deadlineTracks = computeSubjectDeadlineTracks({
    subjects: options.subjects,
    goals: options.goals,
    topics: options.topics,
    referenceDate,
    priorPlannedBlocks: existingPlannedBlocks,
  });
  const requiredHoursBySubject = Object.fromEntries(
    options.subjects.map((subject) => [
      subject.id,
      deadlineTracks[subject.id]?.recommendedWeeklyHours ?? 0,
    ]),
  );
  const subjectDeadlinesById = Object.fromEntries(
    options.subjects.map((subject) => [
      subject.id,
      deadlineTracks[subject.id]?.deadline ?? subject.deadline,
    ]),
  );
  const hasAvailabilityConstraints =
    options.fixedEvents.length > 0 ||
    options.preferences.schoolSchedule.enabled ||
    options.preferences.holidaySchedule.enabled;

  if (!hasAvailabilityConstraints) {
    const studyBlocks = [...lockedBlocks].sort(
      (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
    );

    return {
      studyBlocks,
      weeklyPlan: buildUnconfiguredWeeklyPlan({
        weekStart: weekStartKey,
        subjects: options.subjects,
        studyBlocks,
        topics: options.topics,
        goals: options.goals,
        referenceDate,
      }),
      freeSlots: [],
      unscheduledTasks: buildTaskCandidates({
        topics: options.topics,
        existingPlannedBlocks,
        referenceDate,
        subjectDeadlinesById,
      }),
    };
  }

  const freeSlots = calculateFreeSlots({
    weekStart,
    fixedEvents: options.fixedEvents,
    preferences: options.preferences,
    blockedStudyBlocks: lockedBlocks,
    planningStart: referenceDate,
  });
  const requiredMinutes = sum(Object.values(requiredHoursBySubject).map((value) => value * 60));
  const totalFreeSlotMinutes = sum(freeSlots.map((slot) => slot.durationMinutes));
  const bufferedCapacityMinutes = totalFreeSlotMinutes * (1 - options.preferences.weeklyBufferRatio);
  const activeDayCount = new Set(freeSlots.map((slot) => slot.dateKey)).size;
  const automaticDailyCapBoostMinutes =
    activeDayCount > 0
      ? clamp(
          Math.ceil(Math.max(0, requiredMinutes - bufferedCapacityMinutes) / activeDayCount / 15) * 15,
          0,
          120,
        )
      : 0;
  const tasks = buildTaskCandidates({
    topics: options.topics,
    existingPlannedBlocks,
    referenceDate,
    subjectDeadlinesById,
  });
  const { scheduledBlocks, unscheduledTasks } = allocateTasksToSlots({
    weekStart,
    referenceDate,
    freeSlots,
    tasks,
    subjects: options.subjects,
    goals: options.goals,
    topics: options.topics,
    preferences: options.preferences,
    lockedBlocks,
    priorPlannedBlocks: existingPlannedBlocks,
    requiredHoursBySubject,
    dailyCapBoostMinutes: Math.max(
      options.dailyCapBoostMinutes ?? 0,
      automaticDailyCapBoostMinutes,
    ),
  });
  const studyBlocks = [...lockedBlocks, ...scheduledBlocks].sort(
    (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
  );
  const weeklyPlan = buildWeeklyPlan({
    weekStart: weekStartKey,
    subjects: options.subjects,
    studyBlocks,
    topics: options.topics,
    goals: options.goals,
    freeSlots,
    referenceDate,
    unscheduledTasks,
    priorPlannedBlocks: existingPlannedBlocks,
  });

  return {
    studyBlocks,
    weeklyPlan,
    freeSlots,
    unscheduledTasks,
  };
}

export function getPlanningHorizonEndWeek(goals: Goal[], subjects: Subject[], referenceDate: Date) {
  const academicDeadline = getAcademicDeadline(referenceDate);
  const latestConfiguredDeadline = [...goals.map((goal) => goal.deadline), ...subjects.map((subject) => subject.deadline)]
    .map((value) => new Date(value))
    .filter((date) => !Number.isNaN(date.getTime()))
    .reduce(
      (latest, candidate) => (isAfter(candidate, latest) ? candidate : latest),
      academicDeadline,
    );

  return startOfPlannerWeek(
    latestConfiguredDeadline < academicDeadline ? latestConfiguredDeadline : academicDeadline,
  );
}

export function generateStudyPlanHorizon(options: {
  startWeek?: Date;
  endWeek?: Date;
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: import("@/lib/types/planner").FixedEvent[];
  preferences: Preferences;
  existingStudyBlocks?: StudyBlock[];
}) {
  const startWeek = startOfPlannerWeek(options.startWeek ?? new Date());
  const endWeek = options.endWeek
    ? startOfPlannerWeek(options.endWeek)
    : getPlanningHorizonEndWeek(options.goals, options.subjects, startWeek);
  const existingStudyBlocks = options.existingStudyBlocks ?? [];
  const preservedDoneBlocks = existingStudyBlocks.filter((block) => block.status === "done");
  const horizonStudyBlocks: StudyBlock[] = [];
  const weeklyPlans: WeeklyPlan[] = [];
  const accumulatedBlocks: StudyBlock[] = [];

  for (
    let currentWeek = startWeek;
    currentWeek.getTime() <= endWeek.getTime();
    currentWeek = addDays(currentWeek, 7)
  ) {
    const weekKey = toDateKey(currentWeek);
    const lockedBlocks = preservedDoneBlocks.filter((block) => block.weekStart === weekKey);
    const result = generateStudyPlanForWeek({
      weekStart: currentWeek,
      goals: options.goals,
      subjects: options.subjects,
      topics: options.topics,
      fixedEvents: options.fixedEvents,
      preferences: options.preferences,
      lockedBlocks,
      existingPlannedBlocks: [...accumulatedBlocks, ...lockedBlocks],
    });

    horizonStudyBlocks.push(...result.studyBlocks);
    weeklyPlans.push(result.weeklyPlan);
    accumulatedBlocks.push(...result.studyBlocks);
  }

  return {
    studyBlocks: horizonStudyBlocks.sort(
      (left, right) => new Date(left.start).getTime() - new Date(right.start).getTime(),
    ),
    weeklyPlans,
  };
}

export function getStudyPlanSummary(result: SchedulerResult) {
  return {
    assignedHours: formatHoursFromMinutes(
      result.studyBlocks.reduce((total, block) => total + block.estimatedMinutes, 0),
    ),
    unscheduledHours: formatHoursFromMinutes(
      result.unscheduledTasks.reduce((total, task) => total + task.remainingMinutes, 0),
    ),
  };
}
