import { createId } from "@/lib/utils";
import type {
  EnergyLevel,
  Preferences,
  StudyBlock,
  SubjectId,
} from "@/lib/types/planner";

export const STUDY_BREAK_TRIGGER_MINUTES = 90;

export interface StudyContinuityContext {
  continuousStudyMinutes: number;
  sameSubjectRunMinutes: number;
  previousSubjectId: SubjectId | null;
  followsPlannedBreak: boolean;
}

export function getEffectiveStudyBreakMinutes(preferences: Preferences): number {
  if (!preferences.breaksEnabled) {
    return 0;
  }

  const configuredMinutes = Number.isFinite(preferences.minBreakMinutes)
    ? Math.round(preferences.minBreakMinutes)
    : 0;
  return Math.max(15, configuredMinutes);
}

export function getEffectiveStudyCapacityMinutes(
  slotMinutes: number,
  breakMinutes: number,
): number {
  const availableMinutes = Math.max(0, Math.floor(slotMinutes));
  const effectiveBreakMinutes = Math.max(0, breakMinutes);

  if (availableMinutes === 0 || effectiveBreakMinutes === 0) {
    return availableMinutes;
  }

  let remainingMinutes = availableMinutes;
  let studyMinutes = 0;

  while (remainingMinutes > 0) {
    const nextStudyMinutes = Math.min(STUDY_BREAK_TRIGGER_MINUTES, remainingMinutes);
    studyMinutes += nextStudyMinutes;
    remainingMinutes -= nextStudyMinutes;

    if (
      nextStudyMinutes < STUDY_BREAK_TRIGGER_MINUTES ||
      remainingMinutes <= effectiveBreakMinutes
    ) {
      break;
    }

    remainingMinutes -= effectiveBreakMinutes;
  }

  return studyMinutes;
}

export function isPlannedStudyBreakBlock(
  block: Pick<
    StudyBlock,
    "subjectId" | "topicId" | "title" | "blockType" | "isAutoGenerated"
  >,
): boolean {
  return (
    block.subjectId === null &&
    block.topicId === null &&
    block.title === "Break" &&
    block.blockType === "recovery" &&
    block.isAutoGenerated
  );
}

function getBlockDurationMinutes(block: StudyBlock): number {
  return Math.max(0, block.estimatedMinutes);
}

export function getStudyContinuityContext(options: {
  blocks: StudyBlock[];
  dateKey: string;
  cursor: Date;
  resetMinutes: number;
}): StudyContinuityContext {
  const cursorTime = options.cursor.getTime();
  const relevantBlocks = options.blocks
    .filter((block) => {
      const startTime = new Date(block.start).getTime();
      const endTime = new Date(block.end).getTime();
      return block.date === options.dateKey && startTime < cursorTime && endTime <= cursorTime;
    })
    .sort(
      (left, right) =>
        new Date(left.end).getTime() - new Date(right.end).getTime() ||
        new Date(left.start).getTime() - new Date(right.start).getTime(),
    );

  const previousSubjectId =
    [...relevantBlocks]
      .reverse()
      .find((block) => block.subjectId !== null)?.subjectId ?? null;
  const latestBlock = relevantBlocks.at(-1);
  const followsPlannedBreak = latestBlock
    ? isPlannedStudyBreakBlock(latestBlock)
    : false;

  let continuousStudyMinutes = 0;
  let sameSubjectRunMinutes = 0;
  let finalRunSubjectId: SubjectId | null = null;
  let finalRunIsContiguous = true;
  let boundaryTime = cursorTime;
  const resetMinutes = Math.max(0, options.resetMinutes);

  for (let index = relevantBlocks.length - 1; index >= 0; index -= 1) {
    const block = relevantBlocks[index];
    const blockStartTime = new Date(block.start).getTime();
    const blockEndTime = new Date(block.end).getTime();
    const gapMinutes = Math.max(0, (boundaryTime - blockEndTime) / 60000);

    if (gapMinutes >= resetMinutes || isPlannedStudyBreakBlock(block)) {
      break;
    }

    if (block.subjectId !== null) {
      const durationMinutes = getBlockDurationMinutes(block);
      continuousStudyMinutes += durationMinutes;
      if (finalRunSubjectId === null) {
        finalRunSubjectId = block.subjectId;
        sameSubjectRunMinutes = durationMinutes;
      } else if (finalRunIsContiguous && finalRunSubjectId === block.subjectId) {
        sameSubjectRunMinutes += durationMinutes;
      } else {
        finalRunIsContiguous = false;
      }
    }

    boundaryTime = blockStartTime;
  }

  return {
    continuousStudyMinutes,
    sameSubjectRunMinutes,
    previousSubjectId,
    followsPlannedBreak,
  };
}

export function buildPlannedStudyBreakBlock(options: {
  weekStart: string;
  dateKey: string;
  start: Date;
  durationMinutes: number;
  slotEnergy: EnergyLevel;
}): StudyBlock {
  const durationMinutes = Math.max(0, Math.round(options.durationMinutes));
  const end = new Date(options.start.getTime() + durationMinutes * 60000);

  return {
    id: createId("block"),
    weekStart: options.weekStart,
    date: options.dateKey,
    start: options.start.toISOString(),
    end: end.toISOString(),
    subjectId: null,
    topicId: null,
    title: "Break",
    sessionSummary: "Take a short break before the next study session.",
    paperCode: null,
    unitTitle: null,
    blockType: "recovery",
    intensity: "light",
    generatedReason: "The planner inserted a planned break after continuous study.",
    scoreBreakdown: {
      priorityWeight: 0,
      deadlineUrgency: 0,
      remainingWorkloadPressure: 0,
      lowMasteryBonus: 0,
      reviewDueBonus: 0,
      neglectedSubjectBonus: 0,
      olympiadSlotBonus: 0,
      focusDayBonus: 0,
      badSlotFitPenalty: 0,
      fragmentationPenalty: 0,
      coreSyllabusBonus: 0,
      orderPenalty: 0,
      total: 0,
    },
    status: "planned",
    isAutoGenerated: true,
    creationSource: "planner",
    sourceMaterials: [],
    slotEnergy: options.slotEnergy,
    estimatedMinutes: durationMinutes,
    actualMinutes: null,
    notes: "",
    rescheduleCount: 0,
    assignmentLocked: false,
    assignmentEditedAt: null,
  };
}
