import type {
  blockIntensityValues,
  blockTypeValues,
  energyLevelValues,
  fixedEventCategoryValues,
  fixedEventFlexibilityValues,
  fixedEventRecurrenceValues,
  resourceTypeValues,
  riskFlagValues,
  studyBlockStatusValues,
  subjectIds,
  topicStatusValues,
} from "@/lib/constants/planner";

export type SubjectId = (typeof subjectIds)[number];
export type TopicStatus = (typeof topicStatusValues)[number];
export type StudyBlockStatus = (typeof studyBlockStatusValues)[number];
export type FixedEventCategory = (typeof fixedEventCategoryValues)[number];
export type FixedEventFlexibility = (typeof fixedEventFlexibilityValues)[number];
export type FixedEventRecurrence = (typeof fixedEventRecurrenceValues)[number];
export type BlockType = (typeof blockTypeValues)[number];
export type BlockIntensity = (typeof blockIntensityValues)[number];
export type EnergyLevel = (typeof energyLevelValues)[number];
export type RiskFlag = (typeof riskFlagValues)[number];
export type ResourceType = (typeof resourceTypeValues)[number];
export type SubjectCategory =
  | "physics"
  | "maths"
  | "chemistry"
  | "olympiad"
  | "programming"
  | "english"
  | "french"
  | "geography";

export interface TopicResource {
  type: ResourceType;
  label: string;
  details: string;
}

export interface Goal {
  id: string;
  title: string;
  subjectId: SubjectId;
  deadline: string;
  targetCompletion: number;
  priorityWeight: number;
}

export interface Subject {
  id: SubjectId;
  name: string;
  shortName: string;
  category: SubjectCategory;
  description: string;
  defaultPriority: number;
  weeklyMinimumHours: number;
  examMode: "syllabus" | "maintenance" | "olympiad";
  colorToken: string;
  gradientClassName: string;
  deadline: string;
}

export interface Topic {
  id: string;
  subjectId: SubjectId;
  unitId: string;
  unitTitle: string;
  title: string;
  subtopics: string[];
  estHours: number;
  completedHours: number;
  difficulty: 1 | 2 | 3 | 4 | 5;
  status: TopicStatus;
  mastery: number;
  reviewDue: string | null;
  lastStudiedAt: string | null;
  sourceMaterials: TopicResource[];
  preferredBlockTypes: BlockType[];
  order: number;
  notes?: string;
}

export interface FixedEvent {
  id: string;
  title: string;
  start: string;
  end: string;
  isAllDay?: boolean;
  recurrence: FixedEventRecurrence;
  daysOfWeek?: number[];
  repeatUntil?: string;
  flexibility: FixedEventFlexibility;
  category: FixedEventCategory;
  notes?: string;
}

export interface ScoreBreakdown {
  priorityWeight: number;
  deadlineUrgency: number;
  remainingWorkloadPressure: number;
  lowMasteryBonus: number;
  reviewDueBonus: number;
  neglectedSubjectBonus: number;
  olympiadSlotBonus: number;
  badSlotFitPenalty: number;
  fragmentationPenalty: number;
  total: number;
}

export interface StudyBlock {
  id: string;
  weekStart: string;
  date: string;
  start: string;
  end: string;
  subjectId: SubjectId | null;
  topicId: string | null;
  title: string;
  unitTitle: string | null;
  blockType: BlockType;
  intensity: BlockIntensity;
  generatedReason: string;
  scoreBreakdown: ScoreBreakdown;
  status: StudyBlockStatus;
  isAutoGenerated: boolean;
  sourceMaterials: TopicResource[];
  slotEnergy: EnergyLevel;
  estimatedMinutes: number;
  actualMinutes: number | null;
  notes: string;
  rescheduleCount: number;
}

export interface CompletionLog {
  id: string;
  studyBlockId: string;
  outcome: Exclude<StudyBlockStatus, "planned" | "rescheduled">;
  actualMinutes: number;
  perceivedDifficulty: 1 | 2 | 3 | 4 | 5;
  notes: string;
  recordedAt: string;
}

export interface WeeklyPlan {
  weekStart: string;
  requiredHoursBySubject: Record<string, number>;
  deadlinePaceHoursBySubject: Record<string, number>;
  assignedHoursBySubject: Record<string, number>;
  completedHoursBySubject: Record<string, number>;
  remainingHoursBySubject: Record<string, number>;
  coverageGapHoursBySubject: Record<string, number>;
  scheduledToGoalHoursBySubject: Record<string, number>;
  underplannedSubjectIds: string[];
  slackMinutes: number;
  carryOverBlockIds: string[];
  feasibilityScore: number;
  riskFlag: RiskFlag;
  feasibilityWarnings: string[];
  forcedCoverageMinutes: number;
  usedSundayMinutes: number;
  overloadMinutes: number;
  coverageComplete: boolean;
  weeksRemainingToDeadline: number;
  horizonEndDate: string;
  generatedAt: string;
}

export interface TimeWindow {
  label: string;
  start: string;
  end: string;
  days: number[];
  movable?: boolean;
}

export interface SchoolTerm {
  id: string;
  label: string;
  startDate: string;
  endDate: string;
}

export interface SchoolSchedule {
  enabled: boolean;
  weekdays: number[];
  start: string;
  end: string;
  terms: SchoolTerm[];
}

export interface HolidaySchedule {
  enabled: boolean;
  dailyStudyWindow: {
    start: string;
    end: string;
  };
  preferredDeepWorkWindows: TimeWindow[];
  maxStudyHoursPerDay: number | null;
}

export interface SundayStudySettings {
  enabled: boolean;
  workloadIntensity: number;
}

export interface Preferences {
  id: string;
  dailyStudyWindow: {
    start: string;
    end: string;
  };
  preferredDeepWorkWindows: TimeWindow[];
  lockedRecoveryWindows: TimeWindow[];
  maxHeavySessionsPerDay: number;
  maxStudyHoursPerDay: number;
  minBreakMinutes: number;
  weeklyBufferRatio: number;
  bufferMinutesBeforeFixedEvent: number;
  reserveSundayEvening: boolean;
  autoReduceBeforeExamWeeks: boolean;
  avoidLateNightHeavy: boolean;
  lateNightCutoff: string;
  subjectWeightOverrides: Record<string, number>;
  schoolSchedule: SchoolSchedule;
  holidaySchedule: HolidaySchedule;
  sundayStudy: SundayStudySettings;
}

export interface PlannerExportPayload {
  version: number;
  exportedAt: string;
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: FixedEvent[];
  studyBlocks: StudyBlock[];
  completionLogs: CompletionLog[];
  weeklyPlans: WeeklyPlan[];
  preferences: Preferences;
}

export interface TimeInterval {
  start: Date;
  end: Date;
}

export interface CalendarSlot {
  id: string;
  start: Date;
  end: Date;
  dateKey: string;
  durationMinutes: number;
  energy: EnergyLevel;
  dayIndex: number;
  scheduleRegime: "school-term" | "holiday" | "default";
  dayStudyCapMinutes: number;
}

export interface TaskCandidate {
  id: string;
  subjectId: SubjectId | null;
  topicId: string | null;
  title: string;
  unitTitle: string | null;
  sourceMaterials: TopicResource[];
  remainingMinutes: number;
  difficulty: 1 | 2 | 3 | 4 | 5;
  mastery: number;
  order: number;
  blockedByEarlierTopics: number;
  reviewDue: string | null;
  deadline: string;
  lastStudiedAt: string | null;
  preferredBlockTypes: BlockType[];
  intensity: BlockIntensity;
  kind: "topic" | "review" | "carry_over" | "recovery";
}

export interface SchedulerResult {
  studyBlocks: StudyBlock[];
  weeklyPlan: WeeklyPlan;
  freeSlots: CalendarSlot[];
  unscheduledTasks: TaskCandidate[];
}

export interface SeedDataset {
  goals: Goal[];
  subjects: Subject[];
  topics: Topic[];
  fixedEvents: FixedEvent[];
  preferences: Preferences;
}

export interface HorizonRoadmapWeek {
  weekStart: string;
  weekLabel: string;
  horizonEndDate: string;
  weeksRemainingToDeadline: number;
  requiredHours: number;
  assignedHours: number;
  completedHours: number;
  remainingCoreHours: number;
  riskFlag: RiskFlag;
  coverageComplete: boolean;
  forcedCoverageMinutes: number;
  usedSundayMinutes: number;
  overloadMinutes: number;
  underplannedSubjectIds: string[];
}

export interface HorizonRoadmapSummary {
  startWeek: string;
  endWeek: string;
  weeksRemaining: number;
  totalRequiredHours: number;
  totalAssignedHours: number;
  totalCompletedHours: number;
  remainingCoreHours: number;
  riskWeeks: number;
  weeks: HorizonRoadmapWeek[];
}
