import { z } from "zod";

import {
  blockIntensityValues,
  blockTypeValues,
  energyLevelValues,
  fixedEventCategoryValues,
  fixedEventFlexibilityValues,
  fixedEventRecurrenceValues,
  resourceTypeValues,
  riskFlagValues,
  studyBlockStatusValues,
  topicStatusValues,
} from "@/lib/constants/planner";

export const topicResourceSchema = z.object({
  type: z.enum(resourceTypeValues),
  label: z.string(),
  details: z.string(),
});

export const goalSchema = z.object({
  id: z.string(),
  title: z.string(),
  subjectId: z.string(),
  deadline: z.string(),
  targetCompletion: z.number(),
  priorityWeight: z.number(),
});

export const subjectSchema = z.object({
  id: z.string(),
  name: z.string(),
  shortName: z.string(),
  category: z.string(),
  description: z.string(),
  defaultPriority: z.number(),
  weeklyMinimumHours: z.number(),
  examMode: z.enum(["syllabus", "maintenance", "olympiad"]),
  colorToken: z.string(),
  gradientClassName: z.string(),
  deadline: z.string(),
});

export const topicSchema = z.object({
  id: z.string(),
  subjectId: z.string(),
  unitId: z.string(),
  unitTitle: z.string(),
  title: z.string(),
  subtopics: z.array(z.string()),
  availableFrom: z.string().nullable().optional(),
  dependsOnTopicId: z.string().nullable().optional().default(null),
  minDaysAfterDependency: z.number().nullable().optional().default(null),
  maxDaysAfterDependency: z.number().nullable().optional().default(null),
  sessionMode: z.enum(["flexible", "exam"]).optional().default("flexible"),
  exactSessionMinutes: z.number().nullable().optional().default(null),
  estHours: z.number(),
  completedHours: z.number(),
  difficulty: z.number().min(1).max(5),
  status: z.enum(topicStatusValues),
  mastery: z.number().min(0).max(5),
  reviewDue: z.string().nullable(),
  lastStudiedAt: z.string().nullable(),
  sourceMaterials: z.array(topicResourceSchema),
  preferredBlockTypes: z.array(z.enum(blockTypeValues)),
  order: z.number(),
  paperCode: z.string().nullable().optional().default(null),
  notes: z.string().optional(),
});

export const fixedEventSchema = z.object({
  id: z.string(),
  title: z.string(),
  start: z.string(),
  end: z.string(),
  isAllDay: z.boolean().optional(),
  recurrence: z.enum(fixedEventRecurrenceValues),
  daysOfWeek: z.array(z.number().min(0).max(6)).optional(),
  repeatUntil: z.string().optional(),
  excludedDates: z.array(z.string()).optional(),
  flexibility: z.enum(fixedEventFlexibilityValues),
  category: z.enum(fixedEventCategoryValues),
  notes: z.string().optional(),
});

export const scoreBreakdownSchema = z.object({
  priorityWeight: z.number(),
  deadlineUrgency: z.number(),
  remainingWorkloadPressure: z.number(),
  lowMasteryBonus: z.number(),
  reviewDueBonus: z.number(),
  neglectedSubjectBonus: z.number(),
  olympiadSlotBonus: z.number(),
  badSlotFitPenalty: z.number(),
  fragmentationPenalty: z.number(),
  total: z.number(),
});

export const studyBlockSchema = z.object({
  id: z.string(),
  weekStart: z.string(),
  date: z.string(),
  start: z.string(),
  end: z.string(),
  subjectId: z.string().nullable(),
  topicId: z.string().nullable(),
  title: z.string(),
  sessionSummary: z.string().nullable().optional().default(null),
  paperCode: z.string().nullable().optional().default(null),
  unitTitle: z.string().nullable(),
  blockType: z.enum(blockTypeValues),
  intensity: z.enum(blockIntensityValues),
  generatedReason: z.string(),
  scoreBreakdown: scoreBreakdownSchema,
  status: z.enum(studyBlockStatusValues),
  isAutoGenerated: z.boolean(),
  sourceMaterials: z.array(topicResourceSchema),
  slotEnergy: z.enum(energyLevelValues),
  estimatedMinutes: z.number(),
  actualMinutes: z.number().nullable(),
  notes: z.string(),
  rescheduleCount: z.number(),
});

export const completionLogSchema = z.object({
  id: z.string(),
  studyBlockId: z.string(),
  outcome: z.enum(["done", "partial", "missed"]),
  actualMinutes: z.number(),
  perceivedDifficulty: z.number().min(1).max(5),
  notes: z.string(),
  recordedAt: z.string(),
});

export const weeklyPlanSchema = z.object({
  weekStart: z.string(),
  requiredHoursBySubject: z.record(z.string(), z.number()),
  deadlinePaceHoursBySubject: z.record(z.string(), z.number()).optional().default({}),
  assignedHoursBySubject: z.record(z.string(), z.number()),
  completedHoursBySubject: z.record(z.string(), z.number()),
  remainingHoursBySubject: z.record(z.string(), z.number()).optional().default({}),
  coverageGapHoursBySubject: z.record(z.string(), z.number()).optional().default({}),
  scheduledToGoalHoursBySubject: z.record(z.string(), z.number()).optional().default({}),
  underplannedSubjectIds: z.array(z.string()).optional().default([]),
  slackMinutes: z.number(),
  carryOverBlockIds: z.array(z.string()),
  feasibilityScore: z.number(),
  riskFlag: z.enum(riskFlagValues),
  feasibilityWarnings: z.array(z.string()),
  forcedCoverageMinutes: z.number().optional().default(0),
  usedSundayMinutes: z.number().optional().default(0),
  overloadMinutes: z.number().optional().default(0),
  coverageComplete: z.boolean().optional().default(false),
  weeksRemainingToDeadline: z.number().optional().default(1),
  horizonEndDate: z.string().optional().default(""),
  generatedAt: z.string(),
});

export const timeWindowSchema = z.object({
  label: z.string(),
  start: z.string(),
  end: z.string(),
  days: z.array(z.number()),
  movable: z.boolean().optional(),
});

export const schoolTermSchema = z.object({
  id: z.string(),
  label: z.string(),
  startDate: z.string(),
  endDate: z.string(),
});

export const schoolScheduleSchema = z.object({
  enabled: z.boolean(),
  weekdays: z.array(z.number().min(0).max(6)),
  start: z.string(),
  end: z.string(),
  terms: z.array(schoolTermSchema),
});

export const reservedCommitmentRuleSchema = z.object({
  id: z.string(),
  label: z.string(),
  durationMinutes: z.number().min(0),
  days: z.array(z.number().min(0).max(6)),
  appliesDuring: z.enum(["all", "school-term", "holiday"]),
  preferredStart: z.string(),
});

export const holidayScheduleSchema = z.object({
  enabled: z.boolean(),
  dailyStudyWindow: z.object({
    start: z.string(),
    end: z.string(),
  }),
  preferredDeepWorkWindows: z.array(timeWindowSchema),
  maxStudyHoursPerDay: z.number().nullable(),
});

export const sundayStudySchema = z.object({
  enabled: z.boolean(),
  workloadIntensity: z.number().min(0).max(1.5),
});

export const preferencesSchema = z.object({
  id: z.string(),
  dailyStudyWindow: z.object({
    start: z.string(),
    end: z.string(),
  }),
  preferredDeepWorkWindows: z.array(timeWindowSchema),
  lockedRecoveryWindows: z.array(timeWindowSchema),
  reservedCommitmentRules: z.array(reservedCommitmentRuleSchema).optional().default([
    {
      id: "piano-practice",
      label: "Piano",
      durationMinutes: 60,
      days: [0, 2, 3, 4, 5, 6],
      appliesDuring: "all",
      preferredStart: "18:00",
    },
    {
      id: "term-homework",
      label: "Homework",
      durationMinutes: 90,
      days: [0, 1, 2, 3, 4, 5, 6],
      appliesDuring: "school-term",
      preferredStart: "16:00",
    },
  ]),
  maxHeavySessionsPerDay: z.number(),
  maxStudyHoursPerDay: z.number(),
  minBreakMinutes: z.number(),
  weeklyBufferRatio: z.number(),
  bufferMinutesBeforeFixedEvent: z.number(),
  reserveSundayEvening: z.boolean(),
  autoReduceBeforeExamWeeks: z.boolean(),
  avoidLateNightHeavy: z.boolean(),
  lateNightCutoff: z.string(),
  subjectWeightOverrides: z.record(z.string(), z.number()),
  schoolSchedule: schoolScheduleSchema.optional().default({
    enabled: false,
    weekdays: [1, 2, 3, 4, 5],
    start: "08:00",
    end: "15:00",
    terms: [
      { id: "term-1", label: "Term 1", startDate: "", endDate: "" },
      { id: "term-2", label: "Term 2", startDate: "", endDate: "" },
      { id: "term-3", label: "Term 3", startDate: "", endDate: "" },
      { id: "term-4", label: "Term 4", startDate: "", endDate: "" },
    ],
  }),
  holidaySchedule: holidayScheduleSchema.optional().default({
    enabled: true,
    dailyStudyWindow: {
      start: "08:00",
      end: "22:30",
    },
    preferredDeepWorkWindows: [
      {
        label: "Holiday morning deep work",
        start: "08:00",
        end: "11:30",
        days: [0, 1, 2, 3, 4, 5, 6],
      },
      {
        label: "Holiday afternoon focus",
        start: "14:00",
        end: "17:00",
        days: [0, 1, 2, 3, 4, 5, 6],
      },
    ],
    maxStudyHoursPerDay: null,
  }),
  sundayStudy: sundayStudySchema.optional().default({
    enabled: true,
    workloadIntensity: 0.85,
  }),
});

export const plannerExportSchema = z.object({
  version: z.number(),
  exportedAt: z.string(),
  goals: z.array(goalSchema),
  subjects: z.array(subjectSchema),
  topics: z.array(topicSchema),
  fixedEvents: z.array(fixedEventSchema),
  studyBlocks: z.array(studyBlockSchema),
  completionLogs: z.array(completionLogSchema),
  weeklyPlans: z.array(weeklyPlanSchema),
  preferences: preferencesSchema,
});
